microsoft/accessibility-insights-service

README.md
Testing the PR build after the repo is public
=> Testing the PR build after the repo is public

packages/service-library/src/data-providers/page-document-provider.ts
=> Increased rescan time from 1 week to 2 weeks.

build.yaml, package.json, packages/resource-deployment/package.json, packages/resource-deployment/scripts/batch-account-create.sh, packages/resource-deployment/scripts/batch-pool-enable-msi.sh, packages/resource-deployment/scripts/install.sh, yarn.lock
=> adding build step for resource-deployment package

packages/azure-services/src/azure-cosmos/cosmos-client-wrapper.ts, packages/azure-services/src/index.ts, packages/azure-services/src/storage/client.ts, packages/azure-services/src/storage/storage-client.ts, packages/common/src/system/activator.spec.ts, packages/common/src/system/activator.ts, packages/resource-deployment/scripts/app-insights-create.sh, packages/resource-deployment/scripts/batch-pool-enable-msi.sh, packages/resource-deployment/scripts/create-queues.sh, packages/resource-deployment/scripts/create-resource-group.sh, packages/resource-deployment/scripts/install.sh, packages/resource-deployment/scripts/job-schedule-create.sh, packages/resource-deployment/scripts/restart-vm-pools.sh, packages/resource-deployment/scripts/setup-cosmos-db.sh, packages/resource-deployment/scripts/upload-files.sh, packages/runner/src/factories/website-factory.ts, packages/scan-request-sender/src/scan-request-entry-point.ts, packages/scan-request-sender/src/sender/dispatcher.spec.ts, packages/scan-request-sender/src/sender/dispatcher.ts, packages/scan-request-sender/src/source/seed-source.ts, packages/service-library/src/data-providers/page-document-provider.db.spec.ts, packages/service-library/src/data-providers/page-document-provider.spec.ts, packages/service-library/src/data-providers/page-document-provider.ts, packages/service-library/src/test-utilities/db-mock-helpers.ts, packages/storage-documents/src/website.ts
Added websites equal priority scan queuing
Removed deployment script byproduct output
Fixed deployment script messages
=> Added websites equal priority scan queuing

packages/common/package.json, packages/common/src/ciphers/hash-generator.spec.ts, packages/common/src/ciphers/hash-generator.ts, packages/service-library/src/data-providers/page-document-provider.ts, packages/storage-documents/src/website-page.ts, yarn.lock
Bucket hash generator. Base page processing only.
=> Bucket hash generator. Base page processing only.

packages/service-library/src/data-providers/page-document-provider.spec.ts, packages/service-library/src/data-providers/page-document-provider.ts
Preserve continuation token on retrieving websites documents.
=> Preserve continuation token

packages/job-manager/src/batch/batch.ts
Reducing max wait time from 10 mins to 3 mins.
=> Reducing max wait time from 10 mins to 3 mins.

packages/job-manager/src/batch/batch.ts, packages/service-library/src/data-providers/page-document-provider.ts
=> Scan every day.

packages/job-manager/src/batch/batch.ts
Bumping timeout back to 10 mins
=> Bumping timeout back to 10 mins

package.json, packages/logger/package.json, packages/runner/src/crawler/hc-crawler-options-factory.ts, yarn.lock
=> fixing yarn.lock file resolution

packages/job-manager/src/batch/batch.ts, packages/resource-deployment/templates/batch-account.template.json
=> Reducing max task count

packages/resource-deployment/README.md
update Readme in resource-deployment to mention the required permission user needs.
=> update Readme in resource-deployment

packages/resource-deployment/README.md, packages/runner/src/crawler/hc-crawler-options-factory.ts
Added Azure Marketplace legal terms readme section
Fixed URL RegEx to exclude unsupported pages
=> Added Azure Marketplace legal terms readme section

.gitattributes, packages/resource-deployment/scripts/pool-startup/pool-startup-internal.sh, packages/resource-deployment/scripts/pool-startup/pool-startup.sh
=> Adding retry for pool startup

packages/azure-services/src/azure-cosmos/cosmos-client-wrapper.spec.ts, packages/azure-services/src/azure-cosmos/cosmos-client-wrapper.ts, packages/logger/src/app-insights-logger-client.spec.ts, packages/logger/src/app-insights-logger-client.ts, packages/resource-deployment/scripts/upload-files.sh, packages/runner/src/runner/runner.spec.ts, packages/runner/src/runner/runner.ts
=> Avoiding calls for collection/db creation

packages/job-manager/webpack.config.js, packages/resource-deployment/scripts/pool-startup/pool-startup-internal.sh, packages/runner/webpack.config.js, packages/scan-request-sender/webpack.config.js
=> not bundling app insights

package.json
For header checks - Adding the dist folders to exclude in package json.
=> Fixing header check failures

packages/resource-deployment/scripts/app-insights-create.sh, packages/resource-deployment/scripts/batch-account-create.sh, packages/resource-deployment/scripts/batch-pool-enable-msi.sh, packages/resource-deployment/scripts/create-queues.sh, packages/resource-deployment/scripts/create-storage-account.sh, packages/resource-deployment/scripts/key-vault-enable-msi.sh, packages/resource-deployment/scripts/role-assign-for-sp.sh, packages/resource-deployment/scripts/setup-cosmos-db.sh
Added support of large Batch VMs pools allocation with support of Azure managed identity
=> Added support of large Batch VMs pools

packages/runner/src/crawler/hc-crawler-options-factory.ts, packages/runner/src/tasks/crawler-task.ts
renaming baseUrl => websiteUrl
=> renaming baseUrl => websiteUrl

packages/storage-documents/src/website.ts
Adding flag for deep scanning.
=> Adding flag for deep scanning.

packages/storage-documents/src/website-page.ts
Adding flag for unscannable page
=> Adding flag for unscannable page

packages/azure-services/package.json, packages/common/package.json, packages/job-manager/package.json, packages/logger/package.json, packages/runner/package.json, packages/scan-request-sender/package.json, packages/service-library/package.json, yarn.lock
=> upgrading lodash to fix security vulnerability

packages/service-library/src/data-providers/page-document-provider.db.spec.ts, packages/service-library/src/data-providers/page-document-provider.spec.ts, packages/service-library/src/data-providers/page-document-provider.ts, packages/service-library/src/test-utilities/db-mock-helpers.ts, tslint.json
=> fixing db queries to fetch unscanned pages first

packages/service-library/src/data-providers/page-document-provider.db.spec.ts, packages/service-library/src/data-providers/page-document-provider.spec.ts, packages/service-library/src/data-providers/page-document-provider.ts
Modify query to filter out unscannable pages
=> Modify query to filter out unscannable pages

packages/service-library/src/data-providers/page-document-provider.db.spec.ts
add testcase for when unscannable = false
=> add testcase for when unscannable = false

package.json, yarn.lock
=> upgrade lodash to fix security vulenaribility

packages/azure-services/src/register-azure-services-to-container.spec.ts, packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.spec.ts, packages/common/src/configuration/service-configuration.ts, packages/common/src/index.ts, packages/job-manager/src/setup-job-manager-container.ts, packages/logger/src/app-insights-logger-client.spec.ts, packages/logger/src/app-insights-logger-client.ts, packages/logger/src/console-logger-client.spec.ts, packages/logger/src/console-logger-client.ts, packages/logger/src/logger-client.ts, packages/logger/src/logger.spec.ts, packages/logger/src/logger.ts, packages/logger/src/register-logger-to-container.spec.ts, packages/service-library/src/process-entry-point-base.spec.ts, packages/service-library/src/process-entry-point-base.ts
=> using logInConsole property from runtime config

packages/resource-deployment/templates/scan-req-schedule.template.json, packages/scan-request-sender/src/sender/dispatcher.spec.ts, packages/scan-request-sender/src/sender/dispatcher.ts
As part of this, I have also refactored dispatcher tests to improve tests to cover all cases
=> using max queue size config from runtime config

packages/job-manager/src/batch/batch.spec.ts, packages/job-manager/src/batch/batch.ts
=> using maxTask duration from service config

packages/common/src/configuration/service-configuration.ts, packages/resource-deployment/README.md, packages/resource-deployment/package.json, packages/resource-deployment/runtime-config/runtime-config.ci.json, packages/resource-deployment/runtime-config/runtime-config.dev.json, packages/resource-deployment/runtime-config/runtime-config.ppe.json, packages/resource-deployment/runtime-config/runtime-config.prod.json, packages/resource-deployment/scripts/install.sh, packages/resource-deployment/scripts/upload-files.sh, packages/resource-deployment/templates/blob-storage.parameters.json, packages/resource-deployment/templates/blob-storage.template.json
modify upload script to upload runtime config file
=> modify upload script to upload config.json file

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.spec.ts, packages/common/src/configuration/service-configuration.ts, packages/logger/src/console-logger-client.spec.ts, packages/logger/src/console-logger-client.ts
=> moving logInConsole to logConfig section

packages/service-library/src/data-providers/page-document-provider.db.spec.ts, packages/service-library/src/data-providers/page-document-provider.spec.ts, packages/service-library/src/data-providers/page-document-provider.ts
=> using scan configuration from runtime config

packages/common/src/configuration/service-configuration.ts, packages/job-manager/src/index.ts, packages/runner/src/index.ts
bug fix: pass convict as param into ServiceConfiguration
=> bug fix: pass convict as param into ServiceConfiguration

packages/common/src/configuration/service-configuration.ts, packages/resource-deployment/templates/scan-req-schedule.template.json, packages/resource-deployment/templates/url-scan-schedule.template.json
fetch and load runtime configs
=> fetch and load runtime configs 

packages/runner/src/factories/axe-puppeteer-factory.spec.ts, packages/runner/src/factories/axe-puppeteer-factory.ts, packages/runner/src/scanner/page.spec.ts, packages/runner/src/scanner/page.ts, packages/runner/src/scanner/scanner.spec.ts, packages/runner/src/setup-runner-container.ts
Separated out AxePuppeteerFactory so we can disable rules at central
=> Separated out AxePuppeteerFactory so we can disable rules at central place

packages/resource-deployment/scripts/role-assign-for-sp.sh
=> fix bug in role assign script

packages/resource-deployment/runtime-config/runtime-config.selftest.json
=> Add selftest config

packages/common/src/index.ts, packages/common/src/setup-runtime-config-container.spec.ts, packages/common/src/setup-runtime-config-container.ts, packages/job-manager/src/batch/runner-task-config.spec.ts, packages/job-manager/src/batch/runner-task-config.ts, packages/job-manager/src/setup-job-manager-container.spec.ts, packages/job-manager/src/setup-job-manager-container.ts, packages/runner/src/setup-runner-container.spec.ts, packages/runner/src/setup-runner-container.ts, packages/scan-request-sender/src/setup-scan-request-sender-container.spec.ts, packages/scan-request-sender/src/setup-scan-request-sender-container.ts
copying service config file in tasks
=> making service config singleton;

.prettierignore, packages/resource-deployment/scripts/upload-config-files.sh, packages/resource-deployment/scripts/upload-files.sh
- Move config files upload in a separate script.
- Call that script in upload files script.
- Exclude .snap files from prettier.
=> Add script to upload only config files

README.md
=> fix contributing link in readme

.vscode/workspace.code-workspace, package.json, packages/web-api/package.json, packages/web-api/prettier.config.js, packages/web-api/scan-request/function.json, packages/web-api/scan-request/index.ts, packages/web-api/scan-request/scan-request-type.ts, packages/web-api/tsconfig.json, packages/web-api/webpack.config.js, yarn.lock
First sketch for scan request function
=> First sketch for scan request function

.prettierignore, .vscode/workspace.code-workspace, packages/api-contracts/README.md, packages/api-contracts/ai-scan-api.yaml
Swagger mock https://msswagger/designer/apis/sce4ik/publishedmock
=> Scan REST API contract

packages/web-api/webpack.config.js
Copying host.json to dist folder to make web-api/dist deployable
=> copying host.json to dist

packages/web-api/README.md, packages/web-api/get-report-func/function.json, packages/web-api/get-scan-func/function.json, packages/web-api/get-scans-batch-func/function.json, packages/web-api/post-scans-func/function.json
Use dist folder to deploy funcs
=> Use dist folder to deploy funcs

build.yaml
=> copy web-api dist to build artifact

.gitignore, packages/web-api/.vscode/tasks.json, packages/web-api/local.settings.json
Enable support local debugging of functions
=> Enable support local debugging of functions

packages/api-contracts/ai-scan-api.yaml, packages/web-api/src/api-contracts/scan-run-request.ts
=> Added scan run priority

jest.config.base.js, packages/azure-services/jest.config.js, packages/scan-request-sender/package.json, tsconfig.base.json
=> using base jest config in all packages;

packages/storage-documents/src/item-type.ts, packages/storage-documents/src/page-scan-run-result-map.ts, packages/storage-documents/src/page-scan-run-result.ts, packages/storage-documents/src/storage-document.ts, packages/web-api/src/api-contracts/scan-run-request.ts
Document types for persisting scan run result.
=> Document types for persisting scan run result

packages/api-contracts/ai-scan-api.yaml, packages/resource-deployment/scripts/setup-cosmos-db.sh, packages/web-api/get-report-func/function.json
Update /repors REST API
Add new Cosmos collection to support batch scans with item TTL set to 30 days. Update /reports REST API to include scan ID
=> Add new Cosmos collection with TTL preset. Update /reports REST API

build.yaml, packages/resource-deployment/scripts/function-app-create.sh
Add managed identity to the Function App
=> Add managed identity to the Function App

packages/azure-services/src/index.ts, packages/azure-services/src/ioc-types.ts, packages/azure-services/src/register-azure-services-to-container.spec.ts, packages/azure-services/src/register-azure-services-to-container.ts, packages/azure-services/src/storage/storage-client.spec.ts, packages/azure-services/src/storage/storage-client.ts, packages/runner/src/setup-runner-container.spec.ts, packages/runner/src/setup-runner-container.ts, packages/runner/src/tasks/page-state-updater-task.spec.ts, packages/runner/src/tasks/page-state-updater-task.ts, packages/runner/src/tasks/storage-task.ts, packages/runner/src/tasks/website-state-updater-task.spec.ts, packages/runner/src/tasks/website-state-updater-task.ts, packages/scan-request-sender/src/setup-scan-request-sender-container.spec.ts, packages/scan-request-sender/src/setup-scan-request-sender-container.ts, packages/scan-request-sender/src/source/seed-source.spec.ts, packages/scan-request-sender/src/source/seed-source.ts, packages/service-library/src/data-providers/page-document-provider.db.spec.ts, packages/service-library/src/data-providers/page-document-provider.spec.ts, packages/service-library/src/data-providers/page-document-provider.ts
=> adding support to create multiple storageclients

packages/storage-documents/src/index.ts, packages/storage-documents/src/on-demand-page-scan-map.ts, packages/storage-documents/src/on-demand-page-scan.ts
=> rename storage document types to avoid name conflicts with older types

build.yaml
=> enable conditional CG in CI

packages/resource-deployment/scripts/create-datalake-storage-account.sh, packages/resource-deployment/scripts/install.sh, packages/resource-deployment/templates/datalake-storage.parameters.json, packages/resource-deployment/templates/datalake-storage.template.json, yarn.lock
Added ARM template for datalake storage
Added script file to create the datalake storage account.
Modified install script to include datalake script.
=> Added arm template and script to create datalake storage account

packages/resource-deployment/scripts/setup-cosmos-db.sh
=> remove usused cosmos container creation

packages/resource-deployment/scripts/function-app-create.sh, packages/resource-deployment/scripts/install.sh, packages/resource-deployment/templates/function-app-template.json, packages/web-api/get-report-func/function.json, packages/web-api/get-scan-func/function.json, packages/web-api/get-scans-batch-func/function.json, packages/web-api/post-scans-func/function.json
- Add Authentication/Authorization for function app.
- Change managed identity creation to be in the ARM template.
- set web-api functions authlevel from the default "function to "anonymous" so no code would be generated in the the API link.
**Note:**
- Will need to create an App Registration in all our environments to be used in Auth (later we can add a script for automating this process). 
- Any CI/CD pipeline that uses the install script will need to add the new 2 parameters (clientId, tenantId).
=> Add Authentication/Authorization for function app 

packages/resource-deployment/templates/rest-api-templates/model-products.template.json
=> Removing unused properties from products template

packages/resource-deployment/scripts/function-app-create.sh
Handle the error when no previous deployment was created for the function app template.
=> Handle the error when no previous deployment was created for the function app template 

packages/resource-deployment/scripts/function-app-create.sh
Grant key vault access to function app
=> Grant key vault access to function app

packages/resource-deployment/scripts/app-insights-create.sh
Add parameter checking in app insights install script.
=> Add parameter checking in app insights install script

packages/resource-deployment/scripts/function-app-create.sh
Copy runtime config file to function dist folders
=> Copy runtime config file to function dist folders

packages/resource-deployment/scripts/install.sh
Fixing the CI Deployment validation error.
=> Changing the export order

packages/resource-deployment/scripts/function-app-create.sh, packages/resource-deployment/scripts/install.sh
=> Client ID isn't required

packages/resource-deployment/templates/function-app-template.json
=> adding cosmos connection string to function configuration

packages/job-manager/src/worker/worker.spec.ts, packages/job-manager/src/worker/worker.ts
Job manager will exit only if there are no active and running tasks.
=> Waiting till all running tasks are done.

build.yaml
This will add the job artifacts to the drop folder.
=> build yaml - drop on demand scan request artifacts

packages/azure-services/src/credentials/credentials-provider.spec.ts, packages/azure-services/src/credentials/credentials-provider.ts, packages/azure-services/src/credentials/msi-credential-provider.spec.ts, packages/azure-services/src/credentials/msi-credential-provider.ts, packages/azure-services/src/index.ts, packages/azure-services/src/ioc-types.ts, packages/azure-services/src/register-azure-services-to-container.spec.ts, packages/azure-services/src/register-azure-services-to-container.ts, packages/web-api/src/setup-ioc-container.spec.ts, packages/web-api/src/setup-ioc-container.ts, packages/web-workers/src/setup-ioc-container.spec.ts, packages/web-workers/src/setup-ioc-container.ts
=> adding support to use app service msi credentials

build.yaml
=> copying web-workers to build artifacts

packages/resource-deployment/scripts/app-insights-create.sh, packages/resource-deployment/scripts/batch-account-create.sh, packages/resource-deployment/scripts/batch-pool-enable-msi.sh, packages/resource-deployment/scripts/create-api-management.sh, packages/resource-deployment/scripts/create-datalake-storage-account.sh, packages/resource-deployment/scripts/create-queues.sh, packages/resource-deployment/scripts/create-resource-group.sh, packages/resource-deployment/scripts/create-sp-for-key-vault.sh, packages/resource-deployment/scripts/create-storage-account.sh, packages/resource-deployment/scripts/delete-resource-group.sh, packages/resource-deployment/scripts/deploy-rest-api.sh, packages/resource-deployment/scripts/function-app-create.sh, packages/resource-deployment/scripts/get-resource-name-from-resource-paths.sh, packages/resource-deployment/scripts/install.sh, packages/resource-deployment/scripts/job-schedule-create.sh, packages/resource-deployment/scripts/key-vault-enable-msi.sh, packages/resource-deployment/scripts/push-secrets-to-key-vault.sh, packages/resource-deployment/scripts/restart-vm-pools.sh, packages/resource-deployment/scripts/role-assign-for-sp.sh, packages/resource-deployment/scripts/setup-cosmos-db.sh, packages/resource-deployment/scripts/upload-config-files.sh, packages/resource-deployment/scripts/upload-files.sh, packages/resource-deployment/templates/function-web-api-app-template.json, packages/resource-deployment/templates/function-web-workers-app-template.json
Add key vault settings to func apps
Fixed bash script args validation
=> Add key vault settings to func apps

packages/resource-deployment/scripts/create-api-management.sh, packages/resource-deployment/scripts/deploy-rest-api.sh
Hide ARM template result printout
=> Hide ARM template result printout

packages/job-manager/src/worker/worker.spec.ts, packages/job-manager/src/worker/worker.ts
Terminate manager tasks only after executing child tasks.
=> Terminate manager tasks only after executing child tasks.

packages/resource-deployment/scripts/function-app-create.sh
Retry func tool deployment run
=> Retry func tool deployment run

packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts
=> Report only violations

packages/resource-deployment/templates/function-web-api-app-template.json, packages/resource-deployment/templates/function-web-workers-app-template.json
=> using westus for westus2 resource group azure functions

packages/service-library/src/data-service/page-scan-run-report-service.spec.ts, packages/service-library/src/data-service/page-scan-run-report-service.ts, packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts, packages/web-api/src/controllers/__snapshots__/batch-scan-result-controller.spec.ts.snap, packages/web-api/src/controllers/base-scan-result-controller.ts, packages/web-api/src/controllers/batch-scan-result-controller.spec.ts, packages/web-api/src/controllers/scan-result-controller.spec.ts
=> fix href and hide it in rest response

packages/azure-services/src/azure-cosmos/cosmos-client-wrapper.ts
=> fix max parallel calls made

packages/resource-deployment/scripts/setup-cosmos-db.sh
Setup throughput based on environment, higher throughput in prod.
=> Setup throughput based on environment.

packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts
- Go through all violations results and count how many nodes failed for same rule.
=> Fix issue count

packages/service-library/src/data-providers/page-scan-request-provider.db.spec.ts, packages/service-library/src/data-providers/page-scan-request-provider.spec.ts, packages/service-library/src/data-providers/page-scan-request-provider.ts
=> fetching highest priority values first

packages/storage-documents/src/on-demand-page-scan-batch-request.ts, packages/web-api/src/controllers/scan-request-controller.spec.ts, packages/web-api/src/controllers/scan-request-controller.ts, packages/web-api/src/providers/scan-data-provider.spec.ts, packages/web-api/src/providers/scan-data-provider.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.spec.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.ts
not storing requests that won't have scan id
=> storing priority in batch request document;

packages/resource-deployment/scripts/setup-cosmos-db.sh
Brought dev throughput for all collection to 2K
Brought prod throughput for scan collection to 10K and others to 2k
=> Bringing throughput down.

packages/resource-deployment/scripts/setup-cosmos-db.sh
=> increasing throughput for legacy service prod cosmos container

packages/api-contracts/ai-scan-api.yaml, packages/service-library/src/index.ts, packages/service-library/src/web-api/http-response.spec.ts, packages/service-library/src/web-api/http-response.ts, packages/service-library/src/web-api/scan-run-error-codes.ts, packages/service-library/src/web-api/web-api-error-codes.ts, packages/web-api/src/api-contracts/scan-result-response.ts, packages/web-api/src/api-contracts/scan-run-response.ts, packages/web-api/src/controllers/__snapshots__/batch-scan-result-controller.spec.ts.snap, packages/web-api/src/controllers/batch-scan-result-controller.ts, packages/web-api/src/controllers/scan-request-controller.spec.ts, packages/web-api/src/controllers/scan-request-controller.ts, packages/web-api/src/converters/scan-response-converter.spec.ts, packages/web-api/src/converters/scan-response-converter.ts, packages/web-api/src/converters/scan-run-error-converter.spec.ts, packages/web-api/src/converters/scan-run-error-converter.ts
Added scan run error code placeholder.
Unified all error response types.
Updated swagger schema.
=> Added scan run error code placeholder. Unified all error response types.

packages/resource-deployment/scripts/restart-vm-pools.sh
Restarting node with requeue option
=> Restarting node with requeue option

package.json, packages/resource-deployment/scripts/pool-startup/pool-startup-internal.sh, packages/runner/package.json, packages/scanner/package.json, packages/web-api-scan-runner/package.json, yarn.lock
Updated axe-core version from 3.2.2 to 3.3.2 (latest version)
=> Pownkel/axe core v3.3.2

packages/resource-deployment/scripts/install.sh
=> disabling datalake storage account creation

packages/service-library/src/web-api/web-controller.spec.ts, packages/service-library/src/web-api/web-controller.ts
Set default content type response header
=> Set default content type response header

packages/api-contracts/ai-scan-api.yaml, packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/resource-deployment/runtime-config/runtime-config.ci.json, packages/resource-deployment/runtime-config/runtime-config.dev.json, packages/resource-deployment/runtime-config/runtime-config.ppe.json, packages/resource-deployment/runtime-config/runtime-config.prod.json, packages/resource-deployment/runtime-config/runtime-config.selftest.json, packages/service-library/src/web-api/api-controller.spec.ts, packages/service-library/src/web-api/web-api-error-codes.ts, packages/web-api/src/controllers/base-scan-result-controller.ts, packages/web-api/src/controllers/batch-scan-result-controller.spec.ts, packages/web-api/src/controllers/scan-request-controller.spec.ts, packages/web-api/src/controllers/scan-request-controller.ts, packages/web-api/src/controllers/scan-result-controller.spec.ts
Validate scan request priority range input value.
Refactor web api config.
=> Validate scan request priority range

packages/resource-deployment/templates/batch-account.template.json
=> Update Batch Pools VMSS SKU

packages/web-api-scan-request-sender/src/sender/on-demand-dispatcher.ts
=> added log messages for queued messages

packages/resource-deployment/scripts/setup-cosmos-db.sh, packages/web-api-scan-request-sender/src/sender/on-demand-dispatcher.ts
=> Increased throughput to take load of 1K urls per request.

packages/logger/src/app-insights-logger-client.spec.ts, packages/logger/src/app-insights-logger-client.ts, packages/logger/src/console-logger-client.spec.ts, packages/logger/src/console-logger-client.ts, packages/logger/src/logger-client.ts, packages/logger/src/logger-event.ts, packages/logger/src/logger.spec.ts, packages/logger/src/logger.ts
Add LoggerEvent type as a string enum for event names and changed all event tracking methods to use the new type instead
=> Add LoggerEvent type

packages/web-workers/health-monitor-client-func/function.json, packages/web-workers/health-monitor-client-func/index.ts, packages/web-workers/health-monitor-orchestration-func/function.json, packages/web-workers/health-monitor-orchestration-func/index.ts, packages/web-workers/health-monitor-timer-func/function.json, packages/web-workers/health-monitor-timer-func/index.ts, packages/web-workers/src/controllers/health-monitor-client-controller.ts, packages/web-workers/src/controllers/health-monitor-orchestration-controller.ts, packages/web-workers/src/controllers/health-monitor-timer-controller.ts, packages/web-workers/src/setup-ioc-container.ts, packages/web-workers/webpack.config.js
Added health monitoring functions placeholders.
=> Added health monitoring functions placeholders

packages/logger/src/app-insights-logger-client.spec.ts, packages/logger/src/app-insights-logger-client.ts, packages/logger/src/console-logger-client.spec.ts, packages/logger/src/console-logger-client.ts, packages/logger/src/index.ts, packages/logger/src/logger-client.ts, packages/logger/src/logger-event-measurements.ts, packages/logger/src/logger-event.ts, packages/logger/src/logger.spec.ts, packages/logger/src/logger.ts, packages/web-api/src/controllers/scan-request-controller.spec.ts, packages/web-api/src/controllers/scan-request-controller.ts
=> Track Scan request batch submit event via app insights

packages/logger/src/app-insights-logger-client.spec.ts, packages/logger/src/app-insights-logger-client.ts, packages/logger/src/availablity-telemetry.ts, packages/logger/src/console-logger-client.ts, packages/logger/src/logger-client.ts
add trackAvailability() workaround
=> add trackAvailability() workaround

packages/logger/src/app-insights-logger-client.spec.ts, packages/logger/src/app-insights-logger-client.ts, packages/logger/src/base-logger.ts, packages/logger/src/context-aware-app-insights-logger-client.ts, packages/logger/src/index.ts, packages/logger/src/logger-client.ts, packages/logger/src/logger.ts, packages/service-library/src/web-api/api-controller.spec.ts, packages/service-library/src/web-api/web-controller-dispatcher.spec.ts, packages/service-library/src/web-api/web-controller.spec.ts, packages/service-library/src/web-api/web-controller.ts, packages/web-api/src/controllers/batch-scan-result-controller.spec.ts, packages/web-api/src/controllers/batch-scan-result-controller.ts, packages/web-api/src/controllers/health-check-controller.spec.ts, packages/web-api/src/controllers/health-check-controller.ts, packages/web-api/src/controllers/scan-report-controller.spec.ts, packages/web-api/src/controllers/scan-report-controller.ts, packages/web-api/src/controllers/scan-request-controller.spec.ts, packages/web-api/src/controllers/scan-request-controller.ts, packages/web-api/src/controllers/scan-result-controller.spec.ts, packages/web-api/src/controllers/scan-result-controller.ts, packages/web-api/src/process-request.ts, packages/web-workers/src/controllers/health-monitor-client-controller.ts, packages/web-workers/src/controllers/health-monitor-orchestration-controller.ts, packages/web-workers/src/controllers/health-monitor-timer-controller.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.spec.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.ts, packages/web-workers/src/process-request.ts
=> using context aware logger in web api & web-workers packages

packages/azure-services/src/storage/client.ts, packages/azure-services/src/storage/cosmos-container-client.spec.ts, packages/scan-request-sender/src/sender/dispatcher.spec.ts, packages/web-api-scan-request-sender/src/sender/on-demand-dispatcher.spec.ts
Fixing a bug in logging. response code was not logged
=> fix verror message

packages/resource-deployment/scripts/batch-pool-enable-msi.sh
When vmss deploys, only wait until the status is no longer "creating" or "updating"
=> vmss status wait

packages/resource-deployment/templates/function-web-workers-app-template.json, packages/web-workers/src/controllers/health-monitor-client-controller.spec.ts, packages/web-workers/src/controllers/health-monitor-client-controller.ts, packages/web-workers/src/get-process-life-cycle-container.spec.ts, packages/web-workers/src/get-process-life-cycle-container.ts
Expose web-api url to web-worker
=> Expose web-api url to web-worker

packages/service-library/src/web-api/web-controller-dispatcher.spec.ts, packages/service-library/src/web-api/web-controller-dispatcher.ts, packages/service-library/src/web-api/web-controller.spec.ts, packages/service-library/src/web-api/web-controller.ts, packages/web-api/src/process-request.ts, packages/web-workers/health-monitor-client-func/index.ts, packages/web-workers/src/controllers/health-monitor-client-controller.spec.ts, packages/web-workers/src/controllers/health-monitor-client-controller.ts, packages/web-workers/src/controllers/health-monitor-orchestration-controller.ts, packages/web-workers/src/process-request.ts
Refactor to return result of handleRequest to orchestrator function
=> return web controller response

packages/web-api-client/package.json, packages/web-api-client/src/a11y-service-client.spec.ts, packages/web-api-client/src/a11y-service-client.ts
=> added health check method 

packages/azure-services/src/key-vault/secret-names.ts
add app reg sec names in typing
=> add app reg sec names in typing

packages/logger/package.json, packages/logger/src/availablity-telemetry.ts, packages/logger/src/base-app-insights-logger-client.spec.ts, packages/logger/src/base-app-insights-logger-client.ts, yarn.lock
=> using trackAvailability api from sdk

packages/web-api-client/src/a11y-service-client.spec.ts, packages/web-api-client/src/a11y-service-client.ts
Do not throw on failed request, return result body as json
=> Do not throw on failed request, return result body as json

packages/resource-deployment/templates/dashboard.template.json
=> Add two charts - performance and failure requests by function

packages/resource-deployment/templates/dashboard.template.json
=> update target scan run time to 30s

packages/resource-deployment/scripts/batch-account-create.sh, packages/resource-deployment/scripts/deploy-rest-api.sh, packages/resource-deployment/scripts/function-app-create.sh, packages/resource-deployment/scripts/install-parallel.sh, packages/resource-deployment/scripts/install.sh, packages/resource-deployment/scripts/job-schedule-create.sh, packages/resource-deployment/scripts/push-secrets-to-key-vault.sh, packages/resource-deployment/templates/batch-account.template.json, packages/resource-deployment/templates/rest-api-templates/model-accessibility-insight-service-scan-api-api.template.json
Copying the required secrets for web-workers to call rest apis with authentication.
Fixed a race condition in deploying the apim health policy.
We still have a race condition in deploying code in to web api function app. (web api function app doesnt exist when trying to publish code) This will be addressed in next pr.
=> copying secrets for rest api authentications to keyvault

packages/scanner/src/page.spec.ts, packages/scanner/src/page.ts
=> increase document load timeout

packages/logger/src/base-logger.ts, packages/logger/src/logger.spec.ts, packages/service-library/src/process-entry-point-base.spec.ts, packages/service-library/src/process-entry-point-base.ts, packages/service-library/src/web-api/web-controller.ts, packages/web-api/src/controllers/scan-request-controller.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.ts
=> adding more logging

packages/web-workers/src/controllers/health-monitor-orchestration-controller.spec.ts, packages/web-workers/src/controllers/health-monitor-orchestration-controller.ts
=> using scan url from config

packages/api-contracts/ai-scan-api.yaml, packages/scanner/src/axe-scan-results.ts, packages/scanner/src/page.spec.ts, packages/scanner/src/page.ts, packages/service-library/src/web-api/scan-run-error-codes.ts, packages/storage-documents/src/on-demand-page-scan-result.ts
=> adding error code for unreachable url

packages/azure-services/src/azure-cosmos/cosmos-client-wrapper.spec.ts, packages/azure-services/src/azure-cosmos/cosmos-client-wrapper.ts, packages/azure-services/src/storage/client.ts, packages/azure-services/src/storage/cosmos-container-client.spec.ts, packages/service-library/src/test-utilities/db-mock-helpers.ts, packages/web-workers/health-monitor-client-func/index.ts, packages/web-workers/health-monitor-orchestration-func/index.ts, packages/web-workers/src/controllers/health-monitor-client-controller.spec.ts, packages/web-workers/src/controllers/health-monitor-client-controller.ts, packages/web-workers/src/controllers/health-monitor-orchestration-controller.spec.ts, packages/web-workers/src/orchestration-steps.spec.ts, packages/web-workers/src/process-request.ts
Add logging Cosmos DB failed requests
=> Add logging Cosmos DB failed requests

packages/resource-deployment/scripts/create-resource-group.sh
Check resource group provisioning state and wait until successful before continuing with resource deployment
=> Wait on resource group provisioning state

packages/resource-deployment/runtime-config/runtime-config.ppe.json, packages/resource-deployment/runtime-config/runtime-config.prod.json, packages/resource-deployment/templates/dashboard.template.json, packages/scanner/src/page.spec.ts, packages/scanner/src/page.ts
=> Updating Dashboard metrics graph & scan task timeout

README.md, packages/azure-services/src/ioc-types.ts, packages/azure-services/src/register-azure-services-to-container.ts, packages/resource-deployment/scripts/setup-cosmos-db.sh, packages/service-library/src/data-providers/batch-pool-load-snapshot-provider.spec.ts, packages/service-library/src/data-providers/batch-pool-load-snapshot-provider.ts, packages/service-library/src/data-providers/scan-data-provider.ts, packages/service-library/src/index.ts, packages/storage-documents/src/batch-pool-load-snapshot.ts, packages/storage-documents/src/index.ts, packages/storage-documents/src/item-type.ts, packages/storage-documents/src/partition-key.ts, packages/web-api-scan-job-manager/package.json, packages/web-api-scan-job-manager/src/batch/batch-config.spec.ts, packages/web-api-scan-job-manager/src/batch/batch-config.ts, packages/web-api-scan-job-manager/src/batch/batch.spec.ts, packages/web-api-scan-job-manager/src/batch/pool-load-generator.spec.ts, packages/web-api-scan-job-manager/src/batch/pool-load-generator.ts, packages/web-api-scan-job-manager/src/worker/worker.spec.ts, packages/web-api-scan-job-manager/src/worker/worker.ts
Persisting batch pool load snapshot for the future use by scan request sender to create dynamic queue
=> Persisting batch pool load snapshot

packages/job-manager/src/worker/worker.spec.ts, packages/job-manager/src/worker/worker.ts, packages/web-api-scan-job-manager/src/worker/worker.spec.ts, packages/web-api-scan-job-manager/src/worker/worker.ts
=> waiting for child tasks to complete before terminating job manager

packages/functional-tests/src/functional-test-group-types.ts, packages/service-library/src/index.ts, packages/service-library/src/web-api/api-contracts/health-report.ts, packages/web-api/.vscode/tasks.json, packages/web-api/src/controllers/health-check-controller.spec.ts, packages/web-api/src/controllers/health-check-controller.ts
Return health report in health check api
=> Return real health report in health check api

packages/cli/package.json
=> bumped cli version

packages/web-api-scan-runner/src/runner/runner.ts
=> Keep passed/incomplete/inapplicable checks in reports

build.yaml
=> Deploy health-client package

packages/service-library/src/web-api/api-contracts/health-report.ts, packages/web-api/src/controllers/health-check-controller.spec.ts, packages/web-api/src/controllers/health-check-controller.ts
Fail health tests result if not tests found in app insights
=> Fail health tests result if not tests found in app insights

packages/health-client/src/health-checker.ts
Set health client error exit code
=> Set health client error exit code

packages/resource-deployment/templates/rest-api-templates/model-accessibility-insight-service-scan-api-api.template.json
Add endpoints in apim for /health/release and /health/release/{targetId}
=> Added new health endpoints to template

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts
Update the default scan url in tests.
=> Update the default scan url in tests

packages/cli/.vscode/launch.json, packages/cli/.vscode/tasks.json, packages/cli/package.json, packages/cli/src/index.ts, packages/cli/src/report/report-generator.spec.ts, packages/cli/src/report/report-generator.ts, packages/web-api-scan-runner/package.json, packages/web-api-scan-runner/src/report-generator/axe-result-converter.ts, packages/web-api-scan-runner/src/report-generator/axe-result-to-html-converter.spec.ts, packages/web-api-scan-runner/src/report-generator/axe-result-to-html-converter.ts, packages/web-api-scan-runner/src/report-generator/axe-result-to-sarif-converter.spec.ts, yarn.lock
Yet to upgrade the verions. Will do it after report package is published.
- Fixed usage help message
- Fixed debug task for cli in vscode
- remove browserSpec property that is no longer used in report package
=> upgrading to latest report package

.gitignore, build.yaml, package.json, packages/cli/package.json, yarn.lock
=> adding command to pack report package

package.json, packages/cli/src/report/report-generator.spec.ts, packages/cli/src/report/report-generator.ts, yarn.lock
=> Downgrading axe version

packages/resource-deployment/scripts/push-secrets-to-key-vault.sh, packages/resource-deployment/scripts/setup-cosmos-db.sh
update az commands for cosmos api
=> update az commands for cosmos api

packages/web-api/src/controllers/scan-result-controller.spec.ts, packages/web-api/src/controllers/scan-result-controller.ts
=> send status as pending if the scan id is not found

packages/resource-deployment/templates/dashboard.template.json
=> Add release id to functional test widget in dashboard

packages/resource-deployment/templates/batch-account.template.json
Enable soft delete for keyvault
=> Enable soft delete for keyvault

packages/cli/package.json, packages/cli/src/cli.ts, packages/cli/src/command-runner.ts, packages/cli/src/index.ts, packages/cli/src/scanner/ai-scanner.ts, packages/cli/tsconfig.json, packages/cli/tsconfig.sdk.json, packages/cli/webpack.config.js, packages/service-library/src/web-api/web-controller-dispatcher.spec.ts, packages/web-workers/src/orchestration-steps.spec.ts, tsconfig.base.json, yarn.lock
=> feat: adding support to invoke via nodejs apps

packages/cli/package.json
- Increase AI Scan version to 0.2.0 after adding support to invoke via nodejs apps.
=> feat (GitHub action): Increase AI Scan version to 0.2.0

packages/resource-deployment/scripts/batch-account-create.sh, packages/resource-deployment/scripts/install-parallel.sh, packages/resource-deployment/templates/batch-account.template.json
=> chore: adding support to make keyvault soft delete configurable

build.yaml, package.json, yarn.lock
- Using codecov to publish code coverage.
- Removed publishing coverage to azure devops.
-  after this pr, a code coverage comment will be added in every PR with impacted files information.
This PR's code coverage comment may miss baseline information, as it is not run on master yet.
=> chore: add code coverage support using codecov

packages/resource-deployment/scripts/install-parallel.sh
=> fix: fix command line args parsing

packages/cli/src/scanner/ai-scanner.spec.ts, packages/cli/src/scanner/ai-scanner.ts, packages/cli/src/scanner/page.spec.ts, packages/cli/src/scanner/page.ts, packages/cli/src/web-driver/web-driver.spec.ts, packages/cli/src/web-driver/web-driver.ts
Add optional parameter for chrome path so the action can pass it, it will be used only for the library.
=> chore: Add optional parameter for chrome path

packages/cli/package.json
Increase version to publish anew release to have the new chrome path changes.
=> chore: Increase version to publish a new release

packages/service-library/src/process-entry-point-base.spec.ts, packages/service-library/src/process-entry-point-base.ts, packages/service-library/src/web-api/web-controller-dispatcher.spec.ts, packages/service-library/src/web-api/web-controller-dispatcher.ts
=> fix: should not exit for web api functions

packages/common/external/external.d.ts, packages/common/package.json, packages/common/src/index.ts, packages/common/src/why-node-running-logger.spec.ts, packages/common/src/why-node-running-logger.ts, packages/web-api-scan-job-manager/src/index.ts, packages/web-api-scan-request-sender/package.json, packages/web-api-scan-request-sender/src/index.ts, packages/web-api-scan-runner/src/index.ts, yarn.lock
=> add wtfnode logging & wait for 10 seconds before exiting

packages/common/src/why-node-running-logger.ts
=> chore: updating logging for open handles

packages/common/src/why-node-running-logger.spec.ts, packages/common/src/why-node-running-logger.ts, packages/web-api-scan-job-manager/src/index.ts, packages/web-api-scan-request-sender/src/index.ts, packages/web-api-scan-runner/src/index.ts
=> chore: remove interval logging for wtfnode

packages/cli/package.json
=> chore: update scan package version

packages/resource-deployment/scripts/batch-account-create.sh, packages/resource-deployment/scripts/batch-pool-enable-msi.sh, packages/resource-deployment/scripts/batch-pool-setup.sh
=> chore: Add Resource Group Name Tag To VMSS

.dependabot/config.yml
=> chore: add support to look for package updates in csproj

.dependabot/config.yml
=> chore: fix dependabot search path for csproj

packages/resource-deployment/scripts/function-app-create.sh
=> chore: fix retry publishing APIs to Function App

packages/resource-deployment/scripts/pool-startup/pool-startup-internal.sh
=> fix: wait for locks before configuring dpkg

packages/resource-deployment/scripts/function-app-create.sh
- Merge deploy arm template code for web worker and wep api in one function.
=> chore: Refactor create function app

packages/logger/src/logger-event-measurements.ts, packages/logger/src/logger-event.ts
- Add the notification events to logger events so we can use it later for tracking events.
=> feat (send notification): Add send notification events to logger

packages/storage-documents/src/on-demand-page-scan-result.ts
Adding notification state to the scan document interface
=> feat: add notification state to the scan document interface

.vscode/workspace.code-workspace
=> Update C# extension id

packages/service-library/src/web-api/api-contracts/scan-result-response.ts, packages/service-library/src/web-api/api-contracts/scan-run-request.ts, packages/service-library/src/web-api/web-api-error-codes.ts, packages/storage-documents/src/on-demand-page-scan-batch-request.ts, packages/storage-documents/src/on-demand-page-scan-request.ts, packages/storage-documents/src/on-demand-page-scan-result.ts, packages/web-api-send-notification-runner/src/notification-sender-config.spec.ts, packages/web-api-send-notification-runner/src/notification-sender-config.ts, packages/web-api-send-notification-runner/src/sender/notification-sender.spec.ts, packages/web-api-send-notification-runner/src/sender/notification-sender.ts, packages/web-api-send-notification-runner/src/types/notification-sender-metadata.ts, packages/web-api/src/controllers/scan-request-controller.spec.ts, packages/web-api/src/controllers/scan-request-controller.ts, packages/web-api/src/converters/scan-response-converter.spec.ts, packages/web-api/src/converters/scan-response-converter.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.spec.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.ts
Add notification in response if it presents, otherwise do not show it in the response.
=> feat (send-notification): Add notification in response

packages/resource-deployment/scripts/setup-cosmos-db.sh
Reduce cosmos container throughput to reduce cost for dev resource groups
=> fix: reduce cosmos container throughput

package.json, yarn.lock
=> fix: upgrade dot-prop for fixing security vulerability

packages/web-api-send-notification-job-manager/src/task/__snapshots__/send-notification-task-property-provider.spec.ts.snap, packages/web-api-send-notification-job-manager/src/task/send-notification-task-property-provider.spec.ts, packages/web-api-send-notification-job-manager/src/task/send-notification-task-property-provider.ts
=> feat(send-notification): fixing the notification runner task input options

packages/resource-deployment/scripts/setup-cosmos-db.sh
Update the cosmos throughput even if the container already exists
=> chore: update cosmos container throughput in setup script

packages/web-api-scan-job-manager/src/worker/worker.spec.ts, packages/web-api-scan-job-manager/src/worker/worker.ts, packages/web-api-send-notification-job-manager/src/task/send-notification-task-creator.spec.ts, packages/web-api-send-notification-job-manager/src/task/send-notification-task-creator.ts
Validated here - https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_releaseProgress?_a=release-pipeline-progress&releaseId=3432
=> fix: using getMessagesWithTotalCount to support count > 32

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/resource-deployment/runtime-config/runtime-config.ci.json, packages/resource-deployment/runtime-config/runtime-config.dev.json, packages/resource-deployment/runtime-config/runtime-config.ppe.json, packages/resource-deployment/runtime-config/runtime-config.prod.json, packages/resource-deployment/runtime-config/runtime-config.selftest.json
- Add feature flags in service config.
- Add send notification feature flag.
- send notification feature flag is false in all profiles except dev and selftest.
=> feat (send-notification): Add send notification feature flag in service config

packages/web-api/src/controllers/scan-result-controller.spec.ts, packages/web-api/src/controllers/scan-result-controller.ts
Always query db for scan queries.
We are going to check for status in cosmos and return it if the document is found.
If there's no document for this scan id, check if time is less than 5 minutes, if it''s less return "pending", otherwise return "not found"
=> feat(send-notification): Always query db for scan queries

packages/resource-deployment/scripts/create-api-management.sh
Downgrade the API Management tier from Standard to Developer in dev and ci environments
=> chore: downgrade apim tier in dev

packages/web-api-send-notification-job-manager/.vscode/launch.json, packages/web-api-send-notification-runner/.vscode/launch.json
=> Fix VS debug launch names

packages/web-api-scan-runner/src/tasks/notification-queue-message-sender.spec.ts, packages/web-api-scan-runner/src/tasks/notification-queue-message-sender.ts
fix: remove code that set response code in message queueing
=> fix: remove code that set response code in message queueing

packages/azure-services/src/azure-queue/queue.spec.ts, packages/service-library/src/web-api/get-global-web-controller-dispatcher.spec.ts, packages/web-api-send-notification-runner/src/tasks/notification-sender-web-api-client.spec.ts
=> fix: fix tests that are not executed

packages/logger/src/logger-properties.ts, packages/service-library/src/web-api/web-controller.spec.ts, packages/service-library/src/web-api/web-controller.ts
=> fix: set custom properties on context aware logger

packages/resource-deployment/templates/rest-api-templates/model-accessibility-insight-service-scan-api-api.template.json
Replace en dash in template with hyphen
=> fix: en dash in template

packages/azure-services/src/azure-queue/queue.spec.ts, packages/azure-services/src/azure-queue/queue.ts, packages/common/src/system/retry-helper.spec.ts, packages/common/src/system/retry-helper.ts, packages/web-api-scan-request-sender/src/sender/on-demand-scan-request-sender.spec.ts, packages/web-api-scan-request-sender/src/sender/on-demand-scan-request-sender.ts, packages/web-api-scan-runner/src/tasks/notification-queue-message-sender.spec.ts, packages/web-api-scan-runner/src/tasks/notification-queue-message-sender.ts
Add retry logic for message creation and keep scan request if queue fails
=> chore: Add retry logic for message creation and keep scan request if queue fails

packages/resource-deployment/runtime-config/runtime-config.ppe.json, packages/resource-deployment/runtime-config/runtime-config.prod.json
Since we increased the max node count from 3-6, we need to increase queue size as well.
=> chore: increase max queue size

packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts
=> fix: adding null check on scanResult

packages/web-api-scan-job-manager/src/index.ts, packages/web-api-scan-request-sender/src/index.ts, packages/web-api-scan-runner/src/index.ts, packages/web-api-send-notification-job-manager/src/index.ts, packages/web-api-send-notification-runner/src/index.ts
=> chore: decrease wait time for logging open handles

packages/resource-deployment/scripts/batch-account-create.sh, packages/resource-deployment/scripts/install-parallel.sh
Don't overwrite dropPools if it wasn't passed in as an environment variable
=> fix: dropPools environment variable

packages/resource-deployment/runtime-config/runtime-config.prod.json
=> feat (send-notification): enable feature flag for prod

packages/cli/package.json, packages/cli/src/report/summary-report/__snapshots__/console-summary-report-generator.spec.ts.snap, packages/cli/src/report/summary-report/console-summary-report-generator.spec.ts, packages/cli/src/report/summary-report/console-summary-report-generator.ts, packages/cli/src/report/summary-report/json-summary-report-generator.spec.ts, packages/cli/src/report/summary-report/json-summary-report-generator.ts, packages/cli/src/report/summary-report/summary-report-data.ts, packages/cli/src/report/summary-report/summary-report-generator.ts, yarn.lock
These report generators are not yet used.
=> chore: add console & json summary report generators.

packages/azure-services/src/key-vault/secret-names.ts
=> chore: removing unused secret names

packages/web-api/package.json, packages/web-api/src/controllers/scan-request-controller.spec.ts, packages/web-api/src/controllers/scan-request-controller.ts
(removing usage of cosmos feed trigger)
=> chore: write requests to permanent container in web api

packages/web-workers/scan-batch-requests-feed-func/function.json
=> Limit feed trigger to batch of 10 documents

packages/web-api/package.json, packages/web-api/src/controllers/scan-request-controller.spec.ts, packages/web-api/src/controllers/scan-request-controller.ts
This reverts commit d6d8531e28cf3e85c629948727696e5fade4d1a6.
=> Revert "chore: write requests to permanent container in web api (#781)"

packages/service-library/package.json, packages/service-library/src/dev-utilities/load-test.ts
=> chore: adding script to do load testing

packages/resource-deployment/scripts/delete-pools-if-needed.sh, packages/resource-deployment/templates/on-demand-scan-req-schedule.template.json, packages/resource-deployment/templates/on-demand-send-notification-schedule.template.json, packages/resource-deployment/templates/on-demand-url-scan-schedule.template.json
Reduce batch tacks log retention time.
Decrease frequency of sender notification job schedule.
Decrease pools drop interval.
=> Reduce batch tacks log retention time

packages/cli/package.json, packages/web-api-scan-runner/package.json, yarn.lock
Update report package so we get rid of office fabric console warnings.
**Before**
**After**
=> chore(scan-file): update report package

packages/cli/src/report/summary-report/__snapshots__/html-summary-report-generator.spec.ts.snap, packages/cli/src/report/summary-report/console-summary-report-generator.spec.ts, packages/cli/src/report/summary-report/html-summary-report-generator.spec.ts, packages/cli/src/report/summary-report/html-summary-report-generator.ts, packages/cli/src/report/summary-report/json-summary-report-generator.spec.ts, packages/cli/src/report/summary-report/summary-report-data.ts, packages/cli/src/runner/file-command-runner.spec.ts, packages/cli/src/runner/file-command-runner.ts
Add unScannable urls info in the html report summary
=> chore(scan-file): Add unScannable urls info in the html report summary

packages/resource-deployment/scripts/function-app-create.sh, packages/resource-deployment/templates/function-web-api-app-template.json
After this change, attempting to access the function app directly results in a 403 access denied
=> chore: restrict azure function access to APIM IP address

packages/crawler/package.json, packages/scanner/package.json, yarn.lock
=> Sync nmp versions

packages/scanner/src/page.ts
=> Fix log message

packages/web-api-scan-runner/docker-image-config/Dockerfile, packages/web-api-scan-runner/package.json, yarn.lock
Force axe package version when deploying in Docker container
=> Force axe package version when deploying in Docker container

packages/cli/.vscode/launch.json, packages/cli/.vscode/tasks.json, packages/cli/README.md, packages/cli/src/cli.ts, packages/cli/src/module-name-mapper.ts, packages/cli/src/scanner/page.spec.ts, packages/cli/src/scanner/page.ts, packages/cli/src/web-driver/web-driver.spec.ts, packages/cli/src/web-driver/web-driver.ts
Refactor web driver and page scanner to be in sync with service implementation and address false positive color-contrast issue.
=> Refactor web driver

packages/cli/package.json
Update cli package version to reflect axe update
=> Update cli package version

packages/crawler/src/crawler-entry-point.ts, packages/crawler/src/page-operations/accessibility-scan-operation.spec.ts, packages/crawler/src/page-operations/accessibility-scan-operation.ts, packages/crawler/src/page-processors/classic-page-processor.spec.ts, packages/crawler/src/page-processors/classic-page-processor.ts, packages/crawler/src/page-processors/page-processor-base.spec.ts, packages/crawler/src/page-processors/page-processor-base.ts, packages/crawler/src/page-processors/page-processor-factory.spec.ts, packages/crawler/src/page-processors/page-processor-factory.ts, packages/crawler/src/page-processors/simulator-page-processor.spec.ts, packages/crawler/src/page-processors/simulator-page-processor.ts, packages/crawler/src/setup-crawler-container.spec.ts, packages/crawler/src/setup-crawler-container.ts
- Follow CLI and use the console logger instead of the global logger to avoid the asynchronous issues and the other confusing prints associated with the service config.
- Refactoring logger in common is out of scope.
=> feat(port-crawler-to-cli): Use console for logging

packages/cli/src/cli.ts
=> feat(port-crawler-to-cli): Fix crawling condition

packages/resource-deployment/scripts/function-app-create.sh, packages/resource-deployment/templates/function-web-api-app-template.json, packages/resource-deployment/templates/function-web-workers-app-template.json, packages/web-api/.vscode/settings.json, packages/web-workers/.vscode/settings.json, packages/web-workers/src/contracts/function-timer.ts, packages/web-workers/src/controllers/health-monitor-timer-controller.spec.ts, packages/web-workers/src/controllers/health-monitor-timer-controller.ts
Migrate to [Azure functions v3](https://azure.microsoft.com/en-us/updates/announcing-go-live-release-for-azure-functions-v3/), which supports [node 12](https://medium.com/@nodejs/introducing-node-js-12-76c41a1b3f3f).
=> chore: migrate to Azure functions v3 and Node 12

packages/cli/.gitignore, packages/cli/src/cli-entry-point.spec.ts, packages/cli/src/cli-entry-point.ts, packages/cli/src/runner/url-command-runner.ts, packages/cli/src/setup-cli-container.spec.ts, packages/cli/src/setup-cli-container.ts, packages/crawler/.vscode/launch.json, packages/crawler/src/browser-components/active-elements-finder.ts, packages/crawler/src/index.ts, packages/crawler/src/main.ts, packages/crawler/src/page-processors/page-processor-base.spec.ts, packages/crawler/src/page-processors/page-processor-base.ts, packages/crawler/src/setup-crawler-container.spec.ts, packages/crawler/src/setup-crawler-container.ts
Update browser script to handle cross-origin frames.
Added crawler package test entry point.
Remove unnecessary container singleton bindings.
=> feat(port-crawler-to-cli): Update browser script to handle cross-origin frames

packages/cli/README.md, packages/cli/src/cli.ts, packages/crawler/src/crawler/crawler-configuration.spec.ts, packages/crawler/src/crawler/crawler-configuration.ts
=> feat(port-crawler-to-cli): Update CLI documentation

packages/resource-deployment/templates/dashboard.template.json
Update app insight dashboard query parameters to fix chart data
=> Update app insight dashboard query parameters

packages/cli/src/cli-entry-point.ts, packages/cli/src/report/report-disk-writer.ts, packages/cli/src/runner/crawler-command-runner.ts, packages/cli/src/runner/file-command-runner.spec.ts, packages/cli/src/runner/file-command-runner.ts, packages/cli/src/scanner/ai-scanner.ts, packages/cli/src/scanner/page.ts
This PR add the following feature for file scanning:
- Create html summary report.
- Create error log.
- Update CLI notification.
=> feat(cli-summary-report): Create summary reports (html summary and error log) for batch scanning 

packages/cli/src/runner/crawler-command-runner.ts, packages/cli/src/runner/file-command-runner.ts, packages/crawler/src/page-processors/classic-page-processor.spec.ts, packages/crawler/src/page-processors/page-processor-base.spec.ts, packages/crawler/src/page-processors/page-processor-base.ts, packages/crawler/src/page-processors/simulator-page-processor.spec.ts, packages/crawler/src/page-processors/simulator-page-processor.ts, packages/crawler/src/setup-crawler-container.ts, packages/logger/src/logger.ts, packages/scanner-global-library/src/page-handler.ts
Added page rendering handler
Fixed report data when `--simulate` option is selected
Added selector as bookmark part of a scanned URL `https://support.xbox.com/#selector|#Help-topics`
=> Added page rendering handler

packages/cli/README.md
=> feat(cli-summary-report): Update documentation

.vscode/workspace.code-workspace, packages/cli/README.md, packages/cli/package.json, packages/cli/src/cli-entry-point.ts, packages/cli/src/cli.ts, packages/cli/src/report/report-disk-writer.spec.ts, packages/cli/src/report/report-disk-writer.ts, packages/cli/src/runner/crawler-command-runner.spec.ts, packages/cli/src/runner/crawler-command-runner.ts, packages/cli/src/runner/file-command-runner.ts, packages/cli/src/scanner/scan-arguments.ts, packages/crawler/src/crawler-entry-point.ts, packages/crawler/src/index.ts, packages/crawler/src/level-storage/data-base.spec.ts, packages/crawler/src/level-storage/data-base.ts, packages/crawler/src/level-storage/storage-documents.ts, packages/crawler/src/page-processors/page-processor-base.spec.ts, packages/crawler/src/page-processors/page-processor-base.ts, packages/crawler/src/setup-crawler-container.ts, yarn.lock
Add continue option to crawler cli tool
Refactor store of a scan metadata
=> Add continue option to crawler cli tool

packages/cli/package.json, packages/crawler/package.json, packages/web-api-scan-runner/package.json, yarn.lock
=> Update AI report version

packages/cli/package.json, packages/crawler/package.json, packages/crawler/src/main.ts, yarn.lock
=> Fix CLI package dependencies

packages/cli/src/report/report-generator.spec.ts, packages/cli/src/report/report-generator.ts
=> feat(cli-summary-report): update service name used for reporter

packages/cli/README.md, packages/cli/src/cli.ts, packages/cli/src/runner/crawler-command-runner.ts
Update AI CLI tool run options
Updated README.md
=> Update AI CLI tool run options

packages/cli/package.json, packages/crawler/package.json, packages/web-api-scan-runner/package.json, yarn.lock
Update AI report package version
=> Update AI report package version

packages/cli/src/report/report-name-generator-builder.spec.ts, packages/cli/src/report/report-name-generator.spec.ts
- Rename two unit test files from *.test.ts to *.spec.ts to make sure jest will run them
- Add reflect-metadata imports
- Fix policheck alert caused by placement of special characters in a test string
=> fix: unit test fixes

packages/cli/README.md, packages/cli/package.json
=> Correct AI CLI readme

package.json, yarn.lock
=> chore: upgrade marked

packages/cli/.vscode/launch.json, packages/cli/README.md, packages/cli/package.json, packages/cli/src/report/report-generator.spec.ts, packages/cli/src/report/report-generator.ts
Sort failed result descending in consolidated report
=> Added report failed results sorting

packages/cli/package.json, packages/crawler/src/crawler/crawler-engine.spec.ts, packages/crawler/src/crawler/crawler-engine.ts, packages/crawler/src/main.ts, packages/crawler/src/page-processors/classic-page-processor.spec.ts, packages/crawler/src/page-processors/page-processor-base.spec.ts, packages/crawler/src/page-processors/page-processor-base.ts, packages/crawler/src/page-processors/simulator-page-processor.spec.ts, packages/crawler/src/page-processors/simulator-page-processor.ts, packages/crawler/src/types/crawler-run-options.ts, packages/scanner-global-library/src/index.ts, packages/scanner-global-library/src/page-navigator.spec.ts, packages/scanner-global-library/src/page-navigator.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts, packages/scanner-global-library/src/web-driver.ts
Changed page navigation timeout handling
Consolidated page navigation logic in PageNavigator
Extend page navigation timeouts
Update crawler debug options
=> Changed page navigation timeout handling

packages/cli/package.json, packages/crawler/package.json, packages/web-api-scan-runner/package.json, yarn.lock
Use most recent report package version and bump the cli package version to get a fix for a formatting issue in the summary report.
=> chore: use updated report package and bump cli package version

packages/azure-services/package.json, packages/azure-services/src/credentials/msi-credential-provider.spec.ts, packages/azure-services/src/credentials/msi-credential-provider.ts, packages/azure-services/src/register-azure-services-to-container.ts, packages/resource-deployment/scripts/create-env-file-for-debug.sh, packages/resource-deployment/scripts/create-sp-for-key-vault.sh, packages/resource-deployment/scripts/role-assign-for-sp.sh, packages/web-api-scan-job-manager/package.json, packages/web-api-scan-job-manager/webpack.config.js, packages/web-api-scan-request-sender/package.json, packages/web-api-scan-request-sender/webpack.config.js, packages/web-api-scan-runner/package.json, packages/web-api-scan-runner/webpack.config.js, packages/web-api-send-notification-job-manager/package.json, packages/web-api-send-notification-job-manager/webpack.config.js, packages/web-api-send-notification-runner/package.json, packages/web-api-send-notification-runner/webpack.config.js, packages/web-api/package.json, packages/web-api/webpack.config.js, packages/web-workers/package.json, packages/web-workers/webpack.config.js, yarn.lock
Convert to MSI SP to access Blob storage
=> Convert to MSI SP to access Blob storage

packages/resource-deployment/scripts/enable-system-identity-for-batch-vmss.sh, packages/resource-deployment/scripts/function-app-create.sh, packages/resource-deployment/scripts/role-assign-for-sp.sh
Enable MSI SP Blob storage access for service Azure function apps
=> Enable MSI SP Blob storage access for service Azure function apps

packages/azure-services/src/azure-batch/batch-task-config-generator.spec.ts, packages/azure-services/src/azure-batch/batch-task-config-generator.ts, packages/resource-deployment/templates/on-demand-scan-req-schedule.template.json, packages/resource-deployment/templates/on-demand-send-notification-schedule.template.json, packages/resource-deployment/templates/on-demand-url-scan-schedule.template.json, packages/web-api-scan-runner/docker-image-config/Dockerfile
Fixed chromium setup dependencies to resolve the error:
`chrome-linux/chrome: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory`
=> Extend chromium docker setup libraries

packages/resource-deployment/templates/model-accessibility-insight-service-scan-api-api.template.json
Limit API call rate to 1000 requests/min for all endpoints
=> fix: add rate limit for all API calls

packages/resource-deployment/scripts/key-vault-rotate-certificate.sh, packages/resource-deployment/templates/certificate-policy-ci.json, packages/resource-deployment/templates/certificate-policy-dev.json, packages/resource-deployment/templates/certificate-policy-ppe.json, packages/resource-deployment/templates/certificate-policy-prod.json, packages/resource-deployment/templates/certificate-policy-selftest.json
Added certificate policy to support certificate renewal automation
=> Added certificate policy to support certificate renewal automation

packages/resource-deployment/scripts/key-vault-rotate-certificate.sh
Added az command trace for certificate renewal
Added certificate renewal result validation
=> Added az command trace for certificate renewal

packages/common/tsconfig.json, packages/resource-deployment/scripts/restart-vm-pools.sh, packages/resource-deployment/scripts/run-command-when-batch-nodes-are-idle.sh, tsconfig.base.json
Added wait for stable pool nodes on restart
Match Node with TS target version per https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
=> Added wait for stable pool nodes on restart

packages/azure-services/src/azure-batch/batch-task-config-generator.ts, packages/azure-services/src/storage/cosmos-container-client.ts, packages/cli/src/cli.ts, packages/crawler/src/main.ts, packages/health-client/.vscode/launch.json, packages/health-client/.vscode/tasks.json, packages/health-client/src/health-checker.ts, packages/logger/src/base-app-insights-logger-client.ts, packages/logger/src/base-console-logger-client.ts, packages/logger/src/console-logger-client.ts, packages/logger/src/context-aware-app-insights-logger-client.ts, packages/logger/src/global-logger.spec.ts, packages/logger/src/global-logger.ts, packages/logger/src/logger-client.ts, packages/logger/src/logger.ts, packages/scanner-global-library/src/page-handler.ts, packages/scanner-global-library/src/page-navigator.ts, packages/scanner-global-library/src/page.ts
Fixed logger initialization timeout to ensure logger startup availability
Fixed waiting for async promises in Cosmos DB client
Handle browser page navigation errors
Handle page DOM evaluation errors
Handle axe core engine scan errors
=> Fixed logger initialization and async promise handling

packages/cli/package.json, packages/cli/src/report/report-generator.spec.ts, packages/cli/src/report/report-generator.ts, packages/cli/src/runner/crawler-command-runner.ts, packages/cli/src/runner/file-command-runner.ts, packages/crawler/package.json, packages/web-api-scan-runner/package.json, yarn.lock
Use the most recent version of the report package, which has a breaking change for the summary report interface
=> chore: upgrade report package to v3.0.1

packages/resource-deployment/scripts/restart-vm-pools.sh, packages/resource-deployment/scripts/run-command-when-batch-nodes-are-idle.sh, packages/web-api-send-notification-runner/src/notification-sender-config.spec.ts, packages/web-api-send-notification-runner/src/notification-sender-config.ts, packages/web-api-send-notification-runner/src/types/notification-sender-metadata.ts
Fixed notification task optional arguments
Set batch tasks to terminate on node reboot to allow reboot of long running jobs
Enable job schedule on restart timeout
=> Fixed notification task optional arguments

packages/resource-deployment/scripts/restart-vm-pools.sh
Increase wait timeout on batch node restart
=> Increase wait timeout on batch node restart

packages/resource-deployment/templates/dashboard.template.json
Since I moved the AI Service TSGs, I needed to update the link 
=> (chore): updated the TSG link in dashboard.template.json

packages/resource-deployment/README.md
Update Azure RM cmdlets in PowerShell according to https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/?view=azurermps-6.13.0: "All versions of the AzureRM PowerShell module are outdated, but not out of support. The Az PowerShell module is now the recommended PowerShell module for interacting with Azure."
Note: According to https://docs.microsoft.com/en-us/powershell/module/az.accounts/Set-AzContext?view=azps-5.0.0, the `-Subscription` parameter has aliases to `-SubscriptionName` and `-SubscriptionId`, and the `-Tenant` parameter has aliases to `-Domain` and `-TenantId`
=> docs: Update Azure Powershell commands in resource deployment README

packages/axe-result-converter/src/__snapshots__/combined-report-data-converter.spec.ts.snap, packages/axe-result-converter/src/axe-result-types.ts, packages/axe-result-converter/src/axe-results-reducer.spec.ts, packages/axe-result-converter/src/axe-results-reducer.ts, packages/axe-result-converter/src/combined-report-data-converter.spec.ts, packages/axe-result-converter/src/combined-report-data-converter.ts, packages/axe-result-converter/src/index.ts, packages/axe-result-converter/src/scan-result-data.ts, packages/cli/package.json, packages/cli/src/report/consolidated-report-generator.spec.ts, packages/cli/src/report/consolidated-report-generator.ts, packages/cli/src/runner/crawler-command-runner.spec.ts, packages/cli/src/runner/crawler-command-runner.ts, packages/cli/src/setup-cli-container.ts, packages/crawler/src/level-storage/data-base.ts, packages/crawler/src/main.ts, packages/crawler/src/setup-crawler-container.spec.ts, packages/crawler/src/setup-crawler-container.ts
Integrated consolidated report for CLI crawl tool option
=> Integrated consolidated report for CLI crawl tool option

packages/resource-deployment/scripts/enable-batch-provider.sh, packages/resource-deployment/scripts/setup-key-vault.sh, packages/resource-deployment/templates/function-web-api-app-template.json, packages/resource-deployment/templates/key-vault-create.template.json
Update tenant Id and Microsoft Batch object Id in case of ppe or prod to use PME configurations
=> feat (PME-migration): Update tenant Id and Microsoft Batch object Id

.gitignore, packages/axe-result-converter/src/axe-result-types.ts, packages/axe-result-converter/src/axe-results-reducer.spec.ts, packages/axe-result-converter/src/axe-results-reducer.ts, packages/axe-result-converter/src/combined-report-data-converter.spec.ts, packages/axe-result-converter/src/combined-report-data-converter.ts, packages/cli/package.json, packages/cli/src/report/consolidated-report-generator.spec.ts, packages/cli/src/report/consolidated-report-generator.ts, packages/cli/src/scan-result-providers/scan-result-reader.ts, packages/common/src/hash-set.spec.ts, packages/common/src/hash-set.ts, packages/common/src/index.ts, yarn.lock
Consolidated report generation performance optimization
=> Consolidated report generation performance optimization

packages/axe-result-converter/src/__snapshots__/combined-report-data-converter.spec.ts.snap, packages/axe-result-converter/src/combined-report-data-converter.spec.ts, packages/axe-result-converter/src/combined-report-data-converter.ts
- Make sure rules only appear in one of the failed/passed/inapplicable sections (#1140)
- Sort failure cards by number of URLs, then alphabetized by url (#1141)
=> fix: combined report fixes

packages/cli/package.json
Bump CLI version to release bugfixes (#1140 and #1141) and dependency updates (#1136 and #1137)
=> bump cli version to 0.5.1

packages/resource-deployment/scripts/delete-resource-group.sh
We are currently having issues where deleting the whole resource group puts the API management resource into a soft-delete state, so the resource can't be redeployed for two days because of naming collisions. Using the CLI command to delete the APIM individually before deleting the resource group will hard-delete the resource as before.
=> fix: delete APIM as part of clean script

packages/service-library/src/web-api/api-contracts/scan-result-response.ts, packages/storage-documents/src/on-demand-page-scan-result.ts, packages/web-api-scan-runner/src/report-generator/axe-result-to-consolidated-html-converter.spec.ts, packages/web-api-scan-runner/src/report-generator/axe-result-to-consolidated-html-converter.ts, packages/web-api-scan-runner/src/report-generator/register-report-generator-to-container.spec.ts, packages/web-api/src/converters/scan-response-converter.spec.ts, packages/web-api/src/converters/scan-response-converter.ts
Rename consolidated report type as per customer request
=> Rename consolidated report type

packages/resource-deployment/scripts/delete-resource-group.sh
Fix APIM existence query in delete-resource-group script
=> fix: APIM exists query

packages/axe-result-converter/package.json, packages/axe-result-converter/src/__snapshots__/combined-report-data-converter.spec.ts.snap, packages/axe-result-converter/src/combined-report-data-converter.spec.ts, packages/axe-result-converter/src/combined-report-data-converter.ts, packages/axe-result-converter/src/scan-result-data.ts, packages/cli/package.json, packages/cli/src/report/consolidated-report-generator.spec.ts, packages/cli/src/report/consolidated-report-generator.ts, packages/cli/src/report/report-generator.spec.ts, packages/cli/src/report/report-generator.ts, packages/crawler/package.json, packages/crawler/src/level-storage/storage-documents.ts, packages/crawler/src/page-processors/page-processor-base.spec.ts, packages/crawler/src/page-processors/page-processor-base.ts, packages/scanner-global-library/src/axe-scan-results.ts, packages/scanner-global-library/src/page-configurator.spec.ts, packages/scanner-global-library/src/page-configurator.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts, packages/web-api-scan-runner/package.json, packages/web-api-scan-runner/src/report-generator/axe-result-converter.ts, packages/web-api-scan-runner/src/report-generator/axe-result-to-consolidated-html-converter.spec.ts, packages/web-api-scan-runner/src/report-generator/axe-result-to-consolidated-html-converter.ts, packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts, yarn.lock
Upgrade report package to 4.0.0 to get UI changes from [this PR](https://github.com/microsoft/accessibility-insights-web/pull/3758)
=> chore: upgrade report package from 3.1.0 to 4.0.0

packages/resource-deployment/scripts/setup-cosmos-db.sh, packages/resource-deployment/templates/cosmos-db.template.json
Enable Cosmos DB autoscale throughput
=> Enable Cosmos DB autoscale throughput

.vscode/workspace.code-workspace, azure-pipeline/build-artifacts-and-run-tests-job.yaml
- Publish e2e-web-apis package in azure build pipeline artifact
- add e2e-web-apis folder to vscode workspace
=> fix: e2e-web-apis package

package.json, packages/e2e-web-apis/package.json, yarn.lock
=> Upgrade axios package version

packages/web-api/src/converters/scan-response-converter.spec.ts, packages/web-api/src/converters/scan-response-converter.ts
- Adding mock data for deep scan result, this should be deleted when the actual data is added.
=> feat(deepscan-contract): Add mock data for deepsScanResult

packages/azure-services/src/register-azure-services-to-container.spec.ts, packages/azure-services/src/register-azure-services-to-container.ts, packages/resource-deployment/scripts/create-env-file-for-debug.sh, packages/web-api-scan-runner/run-in-docker-container.sh
Fix to enable run scanner in dev environment
=> Fix to enable run scanner in dev environment

packages/service-library/src/data-providers/website-scan-result-provider.ts
Allow merge knownPages and discoveryPatterns in website document
=> feat(deepscan-contract): Merge knownPages and discoveryPatterns

packages/crawler/src/index.ts, packages/crawler/src/setup-crawler-container.spec.ts, packages/crawler/src/setup-crawler-container.ts
Function to register cloud crawler dependencies to the inversify container
=> feat(cloud-crawler): IOC dependencies for cloud crawler

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/resource-deployment/runtime-config/runtime-config.ci.json, packages/resource-deployment/runtime-config/runtime-config.dev.json, packages/resource-deployment/runtime-config/runtime-config.ppe.json, packages/resource-deployment/runtime-config/runtime-config.prod.json, packages/resource-deployment/runtime-config/runtime-config.selftest.json
Added crawl config with urlCrawlLimit to service configuration.
=> feat(cloud-crawler): add crawl config to service configuration

packages/resource-deployment/scripts/delete-resource-group.sh
Delete all Azure resources from resources group but keep API Management service intacat to support self test clean install while APIM soft delete feature in preview
=> Delete selected azure resources

packages/storage-documents/src/on-demand-scan-request-message.ts, packages/web-api-scan-request-sender/src/sender/on-demand-scan-request-sender.spec.ts, packages/web-api-scan-request-sender/src/sender/on-demand-scan-request-sender.ts, packages/web-api-scan-runner/src/scan-metadata-config.spec.ts, packages/web-api-scan-runner/src/types/scan-metadata.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.spec.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.ts
Make sure the deepScan flag is passed to the url scan runner
=> feat(cloud-crawler): add deep scan flag to scan queue message

package.json, yarn.lock
Component governance vulnerabilities fix
=> Component governance vulnerabilities fix

packages/scanner-global-library/src/page-navigator.ts
=> Handle null browser response

packages/cli/package.json, packages/web-api-scan-runner/package.json, packages/web-api-scan-runner/src/index.ts
Fix ts compile error: TS2503: Cannot find namespace 'cheerio'
=> Fix ts compile error

packages/web-api-scan-runner/src/runner/runner.ts
Validate axe result when generating combined report
=> Validate axe result when generating combined report

packages/resource-deployment/scripts/delete-resource-group.sh
Ignore empty resource id in deployment cleanup script
=> Ignore empty resource id in deployment cleanup script

packages/resource-deployment/scripts/delete-resource-group.sh
Increase resources delete timeout
=> Increase resources delete timeout

packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts
Trace page redirect when browser response has no redirection chain
=> Trace page redirect when browser response has no redirection chain

.github/pull_request_template.md
Add checklist item to ensure that the PR creator has validated their changes in an Azure resource group
In addition to the reminder for the PR creator, this also informs the reviewer that the changes were tested in Azure, so they are less likely to need to comment about validating changes.
No other context (see Motivation)
- [n/a] Ran precheckin (`yarn precheckin`)
=> chore: add checklist item to PR template

packages/axe-result-converter/src/axe-result-types.ts, packages/axe-result-converter/src/axe-results-reducer.spec.ts, packages/axe-result-converter/src/axe-results-reducer.ts, packages/axe-result-converter/src/combined-report-data-converter.spec.ts, packages/axe-result-converter/src/combined-report-data-converter.ts, packages/cli/src/crawler/ai-crawler.spec.ts, packages/cli/src/crawler/ai-crawler.ts, packages/cli/src/index.ts, packages/cli/src/report/consolidated-report-generator.spec.ts, packages/cli/src/setup-cli-container.ts, packages/common/src/ciphers/hash-generator.ts, packages/service-library/src/data-providers/combined-scan-results-provider.spec.ts, packages/service-library/src/data-providers/combined-scan-results-provider.ts, packages/web-api-scan-runner/src/report-generator/axe-result-to-consolidated-html-converter.spec.ts
- Expose AICrawler.
- Expose setCLIContainer.
- Fix few webpack build issues:
- Duplicate identifiers for AxeResults.
- Typing couldn't be generated for sha.ja
- Typing error for cheerio
Get the package ready to be consumed by external packages like AIAction.
=> Feat (Hackathon - AIAction): Expose AIcrawler

packages/cli/src/converter/ai-data-converter.spec.ts, packages/cli/src/converter/ai-data-converter.ts, packages/cli/src/index.ts
Expose AICombinedReportDataConverter to be used by external packages
Get the package ready to be consumed by external packages like AIAction
=> feat (Hackathon -- AIAction): Expose AICombinedReportDataConverter

packages/cli/src/crawler-parameters-builder.spec.ts, packages/cli/src/crawler-parameters-builder.ts, packages/cli/src/scan-arguments.ts, packages/crawler/src/apify/apify-settings.spec.ts, packages/crawler/src/apify/apify-settings.ts, packages/crawler/src/crawler/crawler-configuration.spec.ts, packages/crawler/src/crawler/crawler-configuration.ts, packages/crawler/src/crawler/puppeteer-crawler-engine.spec.ts, packages/crawler/src/crawler/puppeteer-crawler-engine.ts, packages/crawler/src/page-operations/accessibility-scan-operation.spec.ts, packages/crawler/src/page-operations/accessibility-scan-operation.ts, packages/crawler/src/page-processors/classic-page-processor.spec.ts, packages/crawler/src/page-processors/classic-page-processor.ts, packages/crawler/src/page-processors/simulator-page-processor.spec.ts, packages/crawler/src/page-processors/simulator-page-processor.ts, packages/crawler/src/scanners/page-scanner.spec.ts, packages/crawler/src/scanners/page-scanner.ts, packages/crawler/src/types/crawler-run-options.ts
Add axe source path and chrome executable options path in crawler
Get the package ready to be consumed by external packages like AIAction
=> feat (Hackathon -- AIAction): Accept axe source path and chrome executable path in crawler

packages/storage-documents/src/on-demand-page-scan-result.ts, packages/storage-documents/src/website-scan-result.ts, packages/web-api-scan-runner/src/crawl-runner/scan-feed-generator.spec.ts, packages/web-api-scan-runner/src/crawl-runner/scan-feed-generator.ts, packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts, packages/web-api/src/controllers/__snapshots__/batch-scan-result-controller.spec.ts.snap, packages/web-api/src/controllers/base-scan-result-controller.ts, packages/web-api/src/controllers/batch-scan-result-controller.spec.ts, packages/web-api/src/controllers/batch-scan-result-controller.ts, packages/web-api/src/controllers/scan-result-controller.spec.ts, packages/web-api/src/controllers/scan-result-controller.ts, packages/web-api/src/converters/scan-response-converter.spec.ts, packages/web-api/src/converters/scan-response-converter.ts
Returns deep scan REST API response
Fixed deep scan completion send notification
Feature work to enable deep scan functionality
=> Return deep scan REST API response

packages/web-api-scan-job-manager/docker-image-config/configure-docker-dns.ps1, packages/web-api-scan-job-manager/docker-image-config/web-api-scan-job-manager.ps1
Configure docker DNS to resolve "host.docker.internal" to the host machine IP address.
=> feat(host-browser-service): Configure Docker DNS

jest.config.base.js, packages/service-library/src/dev-utilities/load-test.ts, packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts, packages/web-api-scan-runner/src/sender/scan-notification-processor.spec.ts, packages/web-api-scan-runner/src/sender/scan-notification-processor.ts
Fixed deep scan notification validation data
Updated load test utility to support various request types
=> Fixed deep scan notification validation data

Contributing.md, README.md, azure-pipeline/TSAOptions.json, packages/web-api-scan-request-sender/package.json, packages/web-api/README.md, packages/web-workers/README.md
Updates all the points where we refer to our own default branch name to reflect recent rename.
Align name with Microsoft/GitHub policy
The rename in GitHub has already occurred and I've already updated our assorted DevOps pipelines accordingly.
=> chore: Rename default branch to main

yarn.lock
=> chore(deps): Upgrade xmldom from 0.3.0 to 0.5.0

packages/web-api-scan-job-manager/docker-image-config/Dockerfile, packages/web-api-scan-request-sender/docker-image-config/Dockerfile, packages/web-api-scan-runner/docker-image-config/Dockerfile, packages/web-api-send-notification-job-manager/docker-image-config/Dockerfile, packages/web-api-send-notification-runner/docker-image-config/Dockerfile
Migrate to new Linux container image to comply with security requirements
=> Migrate to new Linux container image

packages/web-api/src/converters/scan-response-converter.spec.ts, packages/web-api/src/converters/scan-response-converter.ts
Return overall deep scan state base on website URLs scan state
=> Return overall deep scan state

packages/resource-deployment/scripts/restart-vm-pools.sh
Increase batch pool wait timeout
Increase deployment pass rate
Current timeout of 25 minutes is short
=> Increase batch pool wait timeout

packages/cli/package.json, packages/cli/src/crawler/ai-crawler.spec.ts, packages/cli/src/crawler/ai-crawler.ts
Remove trace console output for AICrawler class since this is not part of CLI but external API used in action
=> Remove trace console output

packages/web-api-scan-job-manager/docker-image-config/Dockerfile, packages/web-api-scan-runner/docker-image-config/Add-Font.ps1, packages/web-api-scan-runner/docker-image-config/Dockerfile, packages/web-api-scan-runner/docker-image-config/web-api-scan-runner.ps1
Migrate to Windows Server core image
[Test Deployment](https://portal.azure.com/?feature.customportal=false#@microsoft.onmicrosoft.com/resource/subscriptions/76eb140e-abd4-4a17-ad98-534d0f8d2759/resourceGroups/maxl-a11y-2/overview)
Reduce Windows image size from 4GB to 1.7GB to speed up deployment and VM startup process
=> Migrate to Windows Server core image

packages/resource-deployment/scripts/push-image-to-container-registry.sh
Added error handling when upload image to Azure Container Registry to have descriptive message when upload fails.
=> Added error handling when upload image to Azure Container Registry

package.json, packages/crawler/src/level-storage/data-base.ts, yarn.lock
Patch security issues
Added yarn audit fix support
=> Patch security issues

packages/resource-deployment/scripts/push-image-to-container-registry.sh, packages/resource-deployment/scripts/push-secrets-to-key-vault.sh
Fix bash script trap error handler to run in subshell to not overlap due to its global scope.
[Validation deployment](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_releaseProgress?releaseId=8368&_a=release-pipeline-progress)
=> Fix trap error handler

package.json, yarn.lock
Patch @npmcli/git package version to fix vulnerability
=> Patch @npmcli/git package version

packages/resource-deployment/templates/function-e2e-web-apis-app-template.json, packages/resource-deployment/templates/function-web-api-app-template.json, packages/resource-deployment/templates/function-web-workers-app-template.json
Configure Azure function deployment to same service region
[Validation](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_releaseProgress?releaseId=8713&_a=release-pipeline-progress)
Mitigate network delay between different DCs
=> Configure Azure function deployment to same service region

packages/cli/package.json
bump scan package version.
feature work.
axe-core updated in previous PR.
=> feat(axe-core-4.3.2): bump scan package for axe-core update

yarn.lock
Upgrade @npmcli/arborist to version 2.8.2
Security fix
=> Upgrade @npmcli/arborist to version 2.8.2

package.json, packages/axe-result-converter/package.json, packages/azure-services/package.json, packages/cli/package.json, packages/common/package.json, packages/crawler/package.json, packages/e2e-web-apis/package.json, packages/functional-tests/package.json, packages/health-client/package.json, packages/logger/package.json, packages/scanner-global-library/package.json, packages/service-library/package.json, packages/storage-documents/package.json, packages/web-api-client/package.json, packages/web-api-scan-job-manager/package.json, packages/web-api-scan-runner/package.json, packages/web-api-send-notification-job-manager/package.json, packages/web-api-send-notification-runner/package.json, packages/web-api/package.json, packages/web-workers/package.json, yarn.lock
This PR was created by the Combine PRs action by combining the following PRs:
* #1700 chore(deps): bump @azure/storage-queue from 12.5.0 to 12.7.0
* #1695 chore(deps-dev): bump @types/node from 12.20.24 to 12.20.25
* #1694 chore(deps-dev): bump lerna-audit from 1.3.2 to 1.3.3
=> Update combined dependencies

packages/resource-deployment/scripts/enable-system-identity-for-batch-vmss.sh, packages/resource-deployment/scripts/function-app-create.sh
Fix RBAC role id query bug and wait for role to be created before assigning
Fix deployment pipeline failures when creating a new resource group
=> fix RBAC role id error

packages/resource-deployment/templates/function-e2e-web-apis-app-template.json, packages/resource-deployment/templates/function-web-api-app-template.json, packages/resource-deployment/templates/function-web-workers-app-template.json
Set Azure function node version to major only
Azure may fail to provide exact node version that results function availability failure
=> Set Azure function node version to major only

packages/cli/.vscode/launch.json, packages/cli/package.json, packages/cli/src/cli.ts, packages/cli/src/crawler/ai-crawler.spec.ts, packages/cli/src/crawler/ai-crawler.ts, packages/cli/src/runner/crawler-command-runner.spec.ts, packages/cli/src/runner/crawler-command-runner.ts, packages/crawler/.vscode/launch.json, packages/crawler/package.json, packages/crawler/rollup.config.js, packages/crawler/src/crawler/puppeteer-crawler-engine.spec.ts, packages/crawler/src/crawler/puppeteer-crawler-engine.ts, packages/crawler/src/crawler/simple-crawler-engine.ts, packages/crawler/src/page-processors/classic-page-processor.spec.ts, packages/crawler/src/page-processors/page-processor-base.spec.ts, packages/crawler/src/page-processors/page-processor-base.ts, packages/crawler/src/page-processors/simulator-page-processor.spec.ts, packages/service-library/package.json, yarn.lock
Handle navigation browser errors to proper reflect it in scan report
Addresses issue #1920
=> Handle navigation browser errors

packages/logger/src/index.ts, packages/logger/src/logger-event-measurements.ts, packages/logger/src/logger-event.ts, packages/report-generator-runner/src/report-generator-runner-telemetry-manager.spec.ts, packages/report-generator-runner/src/report-generator-runner-telemetry-manager.ts, packages/report-generator-runner/src/report-processor/report-processor.ts, packages/report-generator-runner/src/runner/request-selector.spec.ts, packages/report-generator-runner/src/runner/request-selector.ts, packages/report-generator-runner/src/runner/runner.spec.ts, packages/report-generator-runner/src/runner/runner.ts, packages/service-library/src/data-providers/on-demand-page-scan-run-result-provider.spec.ts, packages/service-library/src/data-providers/on-demand-page-scan-run-result-provider.ts, packages/service-library/src/data-providers/report-generator-request-data-provider.spec.ts, packages/service-library/src/data-providers/report-generator-request-data-provider.ts, packages/service-library/src/index.ts, packages/storage-documents/src/partition-key.ts, packages/storage-documents/src/report-generator-request.ts
Implemented runner workflow (excluding report processor)
=> Report generator runner

packages/crawler/src/page-processors/url-collection-request-processor.spec.ts, packages/crawler/src/page-processors/url-collection-request-processor.ts
Filter out .xml web page from crawl result to unblock wcp
=> Filter non-html page from crawl result

packages/resource-deployment/scripts/upload-files.sh
Force blob overwrite
The new az cli version will fail if blob already exists
=> Force blob overwrite

packages/api-contracts/ai-scan-api.yaml
Update swagger.yaml to include privacy scan fields
Make sure we have up-to-date documentation of our API
=> Update swagger document

.eslintrc.js, packages/crawler/src/crawler/simple-crawler-engine.spec.ts, packages/crawler/src/page-processors/page-processor-base.spec.ts, packages/health-client/src/deployment-health-checker.spec.ts, packages/logger/src/logger.ts, packages/privacy-scan-runner/src/combined-report/combined-privacy-scan-result-processor.spec.ts, packages/scanner-global-library/src/navigation-hooks.ts, packages/scanner-global-library/src/page-navigator.ts, packages/web-api-scan-runner/src/scanner/deep-scanner.spec.ts
- Fix missing promise awaits in NavigationHooks
- Add the no-floating-promises eslint rule to catch similar bugs
Bugfix for unreliable scans
=> Fix missing promise awaits

packages/common/src/system/system.spec.ts, packages/common/src/system/system.ts, packages/report-generator-runner/src/report-processor/accessibility-report-processor.ts, packages/report-generator-runner/src/report-processor/report-processor.ts, packages/report-generator-runner/src/runner/request-selector.spec.ts, packages/report-generator-runner/src/runner/request-selector.ts, packages/report-generator-runner/src/runner/runner.ts, packages/resource-deployment/scripts/create-env-file-for-debug.sh, packages/web-api/src/controllers/scan-request-controller.ts
Fixed HTTP response normalization to reduce log size
Fixed stale running report requests removal from a queue
Added logging to simplify debugging
=> Fixed HTTP response size normalization

README.md, package.json, packages/axe-result-converter/package.json, packages/cli/package.json, packages/crawler/package.json, packages/scanner-global-library/package.json, packages/service-library/package.json, packages/web-api-scan-runner/package.json, yarn.lock
This pull request updates the service to use axe-core@4.4.1. This latest version of axe-core includes bug fixes, 17 false-positive fixes, 1 rule change, and 1 general improvement. 
This pull request also updates adjacent packages which were also updated to use axe-core@4.4.1: accessibility-insights-report, @axe-core/puppeteer, and axe-sarif-converter.
Feature work.
axe-core [4.4.0](https://github.com/dequelabs/axe-core/releases/tag/v4.4.0) and [4.4.1](https://github.com/dequelabs/axe-core/releases/tag/v4.4.1) release notes
=> feat(axe-core-4.4): Update to axe-core@4.4.1

packages/crawler/src/page-processors/classic-page-processor.spec.ts, packages/crawler/src/page-processors/page-processor-base.spec.ts, packages/crawler/src/page-processors/page-processor-base.ts, packages/crawler/src/page-processors/simulator-page-processor.spec.ts, packages/crawler/src/page-processors/simulator-page-processor.ts, packages/privacy-scan-core/src/cookie-collector.ts, packages/privacy-scan-core/src/privacy-page-scanner.ts, packages/scanner-global-library/src/index.ts, packages/scanner-global-library/src/navigation-hooks.spec.ts, packages/scanner-global-library/src/navigation-hooks.ts, packages/scanner-global-library/src/page-configurator.spec.ts, packages/scanner-global-library/src/page-configurator.ts, packages/scanner-global-library/src/page-handler.spec.ts, packages/scanner-global-library/src/page-handler.ts, packages/scanner-global-library/src/page-navigation-error-patterns.ts, packages/scanner-global-library/src/page-navigation-hooks.spec.ts, packages/scanner-global-library/src/page-navigation-hooks.ts, packages/scanner-global-library/src/page-navigator.spec.ts, packages/scanner-global-library/src/page-navigator.ts, packages/scanner-global-library/src/page-response-processor.ts, packages/scanner-global-library/src/page-timeout-config.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts, packages/scanner-global-library/src/web-driver.ts, packages/service-library/src/dev-utilities/banner-detection-test.ts, packages/web-api-scan-runner/.vscode/tasks.json
Updated page navigation logic to reduce navigation wait time and false failure path
Updated page scrolling logic to ensure scroll completion detection
Fixed page resizing to match browser viewport
=> Fixed page navigation logic

packages/cli/package.json
Bump scan package version for axe-core 4.4.1 update
Part of feature work
axe-core and other relevant packages updated in #2058
=> feat(axe-core-4.4.1): bump scan package for axe-core update

packages/service-library/src/dev-utilities/README.md
=> Added dev tools readme file

packages/service-library/src/dev-utilities/README.md
=> Updated dev tools readme.md

packages/service-library/src/dev-utilities/README.md, packages/service-library/src/dev-utilities/common-lib.ts, packages/service-library/src/dev-utilities/service-client.ts, packages/service-library/src/dev-utilities/wcp-data-parser.ts, packages/service-library/src/dev-utilities/wcp-types.ts
Updated dev tool to support full privacy report.
=> Updated dev tool to support full privacy report

packages/service-library/src/dev-utilities/wcp-types.ts
=> PoliCheck fix

packages/resource-deployment/templates/batch-account-prod.parameters.json
Reduced batch pool size to be below subscription limit
=> Reduced batch pool size

packages/resource-deployment/templates/batch-account-dev.parameters.json, packages/web-api-scan-runner/src/scanner/deep-scanner.spec.ts, packages/web-api-scan-runner/src/scanner/deep-scanner.ts
Update deep scan skip workflow logic to avoid heavy db reads.
=> Update deep scan skip workflow logic

SECURITY.md, packages/privacy-scan-runner/package.json, packages/privacy-scan-runner/src/runner/runner.spec.ts, packages/privacy-scan-runner/src/runner/runner.ts, packages/privacy-scan-runner/src/scan-metadata-config.spec.ts, packages/privacy-scan-runner/src/scan-metadata-config.ts, packages/privacy-scan-runner/src/scanner/page-scan-processor.spec.ts, packages/privacy-scan-runner/src/scanner/page-scan-processor.ts, packages/privacy-scan-runner/src/scanner/page-scan-scheduler.spec.ts, packages/privacy-scan-runner/src/scanner/page-scan-scheduler.ts, packages/privacy-scan-runner/src/scanner/scan-feed-generator.spec.ts, packages/privacy-scan-runner/src/scanner/scan-feed-generator.ts, packages/privacy-scan-runner/src/types/privacy-scan-metadata.ts, packages/web-api-scan-request-sender/src/sender/on-demand-dispatcher.ts
Added privacy known pages list scan scheduling to support multi-pages scan scenario
Added mandatory SECURITY.md
=> Scan known pages for privacy scan request

package.json, packages/azure-services/src/register-azure-services-to-container.ts, packages/crawler/src/page-processors/page-processor-base.spec.ts, packages/crawler/src/page-processors/page-processor-base.ts, packages/scanner-global-library/src/page-client-lib.ts, packages/scanner-global-library/src/page-configurator.spec.ts, packages/scanner-global-library/src/page-configurator.ts, packages/scanner-global-library/src/page-handler.spec.ts, packages/scanner-global-library/src/page-handler.ts, packages/scanner-global-library/src/page-navigator.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts, packages/scanner-global-library/src/puppeteer-options.ts, packages/web-api-scan-runner/package.json, packages/web-api-scan-runner/src/scanner/page-scan-processor.ts, yarn.lock
Enabled page screenshot report
Added page scroll support for custom scrolling elements
Updated lerna to 5.x to fix security issues
=> Enabled page screenshot report

packages/privacy-scan-runner/src/scanner/page-scan-scheduler.ts, packages/resource-deployment/templates/batch-account-ppe-pr.parameters.json
Fix to enable privacy list scan
=> Enable privacy list scan

packages/cli/package.json
this bumps the accessibility-insights-scan package version for release.
feature work
=> feat(ado-auth-part-2): bump scan package version

package.json, packages/azure-services/package.json, packages/privacy-scan-core/src/privacy-scanner-core.spec.ts, packages/privacy-scan-core/src/privacy-scanner-core.ts, packages/privacy-scan-core/src/privacy-scenario-runner.spec.ts, packages/privacy-scan-core/src/privacy-scenario-runner.ts, packages/privacy-scan-runner/src/combined-report/privacy-report-reducer.spec.ts, packages/privacy-scan-runner/src/combined-report/privacy-report-reducer.ts, packages/privacy-scan-runner/src/runner/runner.spec.ts, packages/privacy-scan-runner/src/runner/runner.ts, packages/privacy-scan-runner/src/scanner/page-scan-processor.spec.ts, packages/privacy-scan-runner/src/scanner/page-scan-processor.ts, packages/privacy-scan-runner/src/scanner/privacy-scanner.spec.ts, packages/privacy-scan-runner/src/scanner/privacy-scanner.ts, packages/scanner-global-library/src/browser-error.ts, packages/scanner-global-library/src/privacy-scan-result.ts, packages/service-library/package.json, packages/service-library/src/dev-utilities/banner-detection-test.ts, packages/service-library/src/web-api/scan-run-error-codes.ts, packages/storage-documents/src/on-demand-page-scan-result.ts, packages/storage-documents/src/privacy-scan-types/privacy-scan-combined-report.ts, yarn.lock
Normalize privacy report to use request URL when generating consolidated result.
Remove banner detection error from a consolidated report result.
=> Normalize privacy report to use request URL

packages/azure-services/src/credentials/managed-identity-credential-cache.spec.ts, packages/azure-services/src/credentials/managed-identity-credential-cache.ts, packages/resource-deployment/templates/batch-account-ppe-pr.parameters.json, packages/resource-deployment/templates/batch-account-prod-pr.parameters.json, packages/scanner-global-library/src/page-client-lib.ts
Updated page scroll js script to better detect scroll HTML element
Extended prod privacy scan pool size
Reduce AAD token cache timeout
=> Updated page scroll script

packages/cli/package.json
This bumps the scan package version in preparation for release.
feature work
=> chore: bump scan package version

packages/cli/package.json, packages/common/package.json, packages/common/src/system/url.spec.ts, packages/common/src/system/url.ts, packages/privacy-scan-runner/src/runner/runner.ts, packages/privacy-scan-runner/src/scanner/page-scan-processor.spec.ts, packages/privacy-scan-runner/src/scanner/page-scan-processor.ts, packages/service-library/src/web-api/web-api-error-codes.ts, packages/web-api-scan-runner/src/scanner/page-scan-processor.spec.ts, packages/web-api-scan-runner/src/scanner/page-scan-processor.ts, packages/web-api/src/controllers/scan-request-controller.spec.ts, packages/web-api/src/controllers/scan-request-controller.ts
Handle page navigation error when starting page scan processing.
=> Handle page navigation error when starting page scan processing

packages/web-api/src/controllers/scan-request-controller.spec.ts, packages/web-api/src/controllers/scan-request-controller.ts
Disabled rejection of duplicate URLs
=> Disabled rejection of duplicate URLs

packages/resource-deployment/scripts/pool-startup/pull-image-from-container-registry.ps1
Fail custom startup script to let batch service retry VM setup
=> Fail custom startup script

packages/resource-deployment/scripts/add-tags-for-batch-vmss.sh, packages/resource-deployment/scripts/enable-system-identity-for-batch-vmss.sh, packages/resource-deployment/scripts/setup-all-pools-for-batch.sh
Extended VMSS service principal assignment validation to increase deployment resilience
=> Extended VMSS service principal assignment validation

packages/cli/package.json
Bump the scan package version so the GitHub Action and ADO Extension can enable two new automated checks rules.
Feature work 🚀 
=> feat(implement-new-checks): bump scan package version

packages/cli/package.json, packages/crawler/src/page-processors/page-processor-base.spec.ts, packages/crawler/src/page-processors/page-processor-base.ts
Added wait condition on page navigation to get navigation response for dynamic pages.
=> Added wait condition on page navigation

packages/resource-deployment/scripts/batch-account-create.sh
Set batch pool public IP DNS unique name
=> Set batch pool public IP DNS unique name

packages/resource-deployment/templates/batch-account-dev.parameters.json, packages/resource-deployment/templates/batch-account-ppe-pr.parameters.json, packages/resource-deployment/templates/batch-account-ppe.parameters.json, packages/resource-deployment/templates/batch-account-prod-pr.parameters.json, packages/resource-deployment/templates/batch-account-prod.parameters.json, packages/resource-deployment/templates/batch-account.template.json, packages/scanner-global-library/src/page-navigation-hooks.ts
Disable page animation effects to prevent false positive color contrast accessibility issues
=> Disable page animation effects

packages/resource-deployment/templates/batch-account-ppe-pr.parameters.json, packages/resource-deployment/templates/batch-account-ppe.parameters.json, packages/resource-deployment/templates/batch-account-prod-pr.parameters.json, packages/resource-deployment/templates/batch-account-prod.parameters.json
Increased batch pool node redundancy to prevent node configuration reset
=> Increased batch pool node redundancy

packages/privacy-scan-core/src/privacy-scanner-core.spec.ts, packages/privacy-scan-core/src/privacy-scanner-core.ts, packages/privacy-scan-runner/src/combined-report/privacy-report-reducer.spec.ts, packages/privacy-scan-runner/src/combined-report/privacy-report-reducer.ts, packages/privacy-scan-runner/src/runner/runner.spec.ts, packages/privacy-scan-runner/src/runner/runner.ts, packages/scanner-global-library/src/browser-error.ts, packages/scanner-global-library/src/privacy-scan-result.ts, packages/service-library/src/dev-utilities/banner-detection-test.ts, packages/storage-documents/src/privacy-scan-types/privacy-scan-combined-report.ts
Enforce privacy scan error type to BrowserType only
=> Enforce privacy scan error type

packages/azure-services/src/credentials/managed-identity-credential-cache.ts, packages/cli/package.json, packages/common/src/system/retry-helper.spec.ts, packages/common/src/system/retry-helper.ts, packages/crawler/package.json, packages/crawler/src/page-processors/page-processor-base.spec.ts, packages/crawler/src/page-processors/page-processor-base.ts, packages/privacy-scan-runner/package.json, packages/privacy-scan-runner/src/runner/runner.spec.ts, packages/privacy-scan-runner/src/runner/runner.ts, packages/scanner-global-library/package.json, packages/web-api-scan-runner/package.json, packages/web-api-scan-runner/src/crawl-runner/crawl-runner.ts, yarn.lock
Override puppeteer version for apify package.
=> Override puppeteer version for apify package

packages/common/src/system/system.ts, packages/scanner-global-library/src/page-handler.spec.ts, packages/scanner-global-library/src/page-handler.ts
Fixed page scroll timeout validation to support infinite page scroll cases.
=> Fixed page scroll timeout validation

packages/scanner-global-library/src/page-navigator.ts
Ensure page status code returns in navigation result
=> Ensure page status code returns in navigation result

packages/scanner-global-library/src/page-navigation-hooks.spec.ts, packages/scanner-global-library/src/page-navigation-hooks.ts, packages/scanner-global-library/src/page-navigator.ts
Close browser JavaScript alert box to prevent page navigation timeout.
=> Close browser JavaScript alert box

package.json, packages/cli/package.json, yarn.lock
Updated json5 npm version to resolve vulnerabilities.
=> Updated json5 npm version

.gitignore, packages/azure-services/src/azure-batch/batch-task-config-generator.spec.ts, packages/azure-services/src/azure-batch/batch-task-config-generator.ts, packages/azure-services/src/ioc-types.ts, packages/azure-services/src/key-vault/secret-names.ts, packages/azure-services/src/register-azure-services-to-container.ts, packages/privacy-scan-runner/src/runner/runner.ts, packages/scanner-global-library/src/index.ts, packages/scanner-global-library/src/ioc-types.ts, packages/scanner-global-library/src/page.ts, packages/scanner-global-library/src/setup-scanner-container.ts, packages/scanner-global-library/src/user-agent-plugin.spec.ts, packages/scanner-global-library/src/user-agent-plugin.ts, packages/scanner-global-library/src/web-driver.spec.ts, packages/scanner-global-library/src/web-driver.ts, packages/service-library/src/dev-utilities/banner-detection-test.ts, packages/web-api-scan-runner/src/runner/runner.ts, packages/web-api-send-notification-runner/src/sender/notification-sender.ts
Added scanner id to browser user agent string.
Fixed docker command parameters encoding.
=> Added scanner id to browser user agent string

packages/resource-deployment/scripts/setup-key-vault.sh
Disable az cli key vault api since it is blocked by ADO release
=> Disable key vault failed api

package.json, packages/resource-deployment/scripts/run-command-on-all-vmss-for-pool.sh, packages/resource-deployment/templates/batch-account-prod-pr.parameters.json, yarn.lock
Fixed wait condition for pool's VMSS deployment.
Scale out privacy scan pool.
=> Fixed wait condition for pool's VMSS deployment

.vscode/workspace.code-workspace, packages/privacy-scan-runner/.vscode/tasks.json, packages/scanner-global-library/src/browser-cache.spec.ts, packages/scanner-global-library/src/browser-cache.ts, packages/scanner-global-library/src/page-navigator.spec.ts, packages/scanner-global-library/src/page-navigator.ts, packages/scanner-global-library/src/web-driver.spec.ts, packages/scanner-global-library/src/web-driver.ts, packages/service-library/package.json
Clear browser cache for the active browser instance to avoid browser restart on page reload.
=> Clear browser cache for active instance

packages/azure-services/src/register-azure-services-to-container.ts, packages/common/src/system/system.spec.ts, packages/common/src/system/system.ts, packages/logger/src/global-logger.spec.ts, packages/logger/src/logger.ts, packages/scanner-global-library/src/page-timeout-config.ts, packages/scanner-global-library/src/web-driver.ts, packages/service-library/package.json, packages/service-library/src/data-providers/website-scan-result-aggregator.ts
Fixed detection of node debug mode.
Increase page scroll timeout to mitigate axe core hanging.
=> Fixed detection of node debug mode

packages/privacy-scan-runner/src/scanner/privacy-scanner.spec.ts, packages/privacy-scan-runner/src/scanner/privacy-scanner.ts, packages/scanner-global-library/src/page-navigator.ts
Increase timeout for privacy scan task
=> Increase timeout for privacy scan task

packages/resource-deployment/README.md
=> Fixed README link

packages/resource-deployment/README.md
Added missing deployment steps to deployment readme documentation.
=> Added missing deployment steps to deployment documentation

packages/resource-deployment/scripts/enable-os-image-upgrade.sh, packages/resource-deployment/scripts/setup-all-pools-for-batch.sh, packages/resource-deployment/templates/vmss-health-extension.json
Enable VMSS automatic OS image upgrades
=> Enable VMSS automatic OS image upgrades

packages/resource-deployment/templates/vmss-health-extension.json
Configure correct Application Health Extension health probe endpoint to enable a consistent probe response.
=> Configure Application Health Extension health probe endpoint

packages/scanner-global-library/src/page.ts
Handle large page screenshot generation error to allow scanner to continue
=> Handle large page screenshot generation

packages/resource-deployment/scripts/pool-startup/install-docker-engine.ps1
Script based restart on Hyper-V install to better handle script exit on restart.
=> Script restart on Hyper-V install

packages/report-generator-runner/src/report-processor/accessibility-report-processor.spec.ts, packages/report-generator-runner/src/report-processor/accessibility-report-processor.ts, packages/report-generator-runner/src/report-processor/report-processor.spec.ts, packages/report-generator-runner/src/report-processor/report-processor.ts, packages/report-generator-runner/src/runner/runner.spec.ts, packages/report-generator-runner/src/runner/runner.ts, packages/resource-deployment/templates/batch-account-prod-pr.parameters.json, packages/resource-deployment/templates/batch-account-prod.parameters.json, packages/scanner-global-library/src/network/page-request-interceptor.spec.ts, packages/scanner-global-library/src/network/page-request-interceptor.ts, packages/scanner-global-library/src/page.ts, packages/service-library/src/combined-report-provider/combined-report-generator.spec.ts, packages/service-library/src/combined-report-provider/combined-report-generator.ts, packages/service-library/src/combined-report-provider/combined-scan-result-processor.spec.ts, packages/service-library/src/combined-report-provider/combined-scan-result-processor.ts, packages/storage-documents/src/report-generator-request.ts, packages/storage-documents/src/website-scan-result.ts, packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts
- Fixed request interception timeout on page reload
- Scale up batch pools
- Fixed report runner parameter decoding
=> Fixed request interception timeout on page reload

packages/cli/package.json, packages/crawler/package.json, packages/privacy-scan-core/package.json, packages/privacy-scan-job-manager/docker-image-config/Dockerfile, packages/privacy-scan-runner/docker-image-config/Dockerfile, packages/privacy-scan-runner/package.json, packages/report-generator-job-manager/docker-image-config/Dockerfile, packages/report-generator-runner/docker-image-config/Dockerfile, packages/report-generator-runner/package.json, packages/scanner-global-library/package.json, packages/scanner-global-library/src/browser-cache.spec.ts, packages/scanner-global-library/src/browser-cache.ts, packages/scanner-global-library/src/dev-tools-session.spec.ts, packages/scanner-global-library/src/dev-tools-session.ts, packages/scanner-global-library/src/network/page-operation-handler.ts, packages/scanner-global-library/src/network/page-request-interceptor.spec.ts, packages/scanner-global-library/src/network/page-request-interceptor.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts, packages/scanner-global-library/src/web-driver.ts, packages/service-library/package.json, packages/web-api-scan-job-manager/docker-image-config/Dockerfile, packages/web-api-scan-request-sender/docker-image-config/Dockerfile, packages/web-api-scan-runner/docker-image-config/Dockerfile, packages/web-api-scan-runner/package.json, packages/web-api-send-notification-job-manager/docker-image-config/Dockerfile, packages/web-api-send-notification-runner/docker-image-config/Dockerfile, yarn.lock
- Added CDP session wrapper to mitigate uncaught timeout exception
- Updated puppeteer version
- Updated nodejs docker version
=> Added CDP session wrapper

packages/scanner-global-library/src/network/page-request-interceptor.spec.ts, packages/scanner-global-library/src/network/page-request-interceptor.ts
Set bypass service worker using new puppeteer API to restore functionality.
=> Set bypass service worker

packages/cli/README.md, packages/cli/package.json, packages/cli/src/cli.ts, packages/cli/src/crawler/crawler-parameters-builder.ts, packages/cli/src/scan-arguments.ts, packages/crawler/package.json, packages/crawler/src/crawler/crawler-configuration.spec.ts, packages/crawler/src/crawler/crawler-configuration.ts, packages/crawler/src/main.ts, packages/crawler/src/page-processors/page-processor-base.spec.ts, packages/crawler/src/page-processors/page-processor-base.ts, packages/crawler/src/types/crawler-run-options.ts, yarn.lock
Workaround of crawlee href bug. The crawlee fails to properly generate absolute URL from relative href link.
=> Workaround of crawlee href bug

packages/cli/README.md, packages/cli/package.json, packages/cli/src/cli.ts, packages/crawler/src/apify/discovery-patterns.spec.ts, packages/crawler/src/apify/discovery-patterns.ts, packages/crawler/src/crawler/crawler-configuration.spec.ts, packages/crawler/src/crawler/crawler-configuration.ts, packages/logger/src/apify-console-logger-client.ts, packages/scanner-global-library/src/network/page-request-interceptor.ts, packages/scanner-global-library/src/page.ts
Fixed page instance trace on network requests trace to avoid delay on page reload.
=> Fixed page instance trace on network requests trace

packages/logger/src/logger-client.ts, packages/logger/src/logger.ts, packages/logger/src/otel-config-provider.ts, packages/logger/src/otel-logger-client.ts, packages/logger/src/register-logger-to-container.spec.ts, packages/logger/src/register-logger-to-container.ts, packages/resource-deployment/README.md, packages/resource-deployment/custom-scripts/docker-image/Add-Font.ps1, packages/resource-deployment/custom-scripts/docker-image/Fonts.tar, packages/resource-deployment/custom-scripts/prepare-deployment.sh, packages/resource-deployment/custom-scripts/resource-deployment/templates/web-api-aad-acl-dev.json, packages/resource-deployment/custom-scripts/resource-deployment/templates/web-api-aad-acl-ppe.json, packages/resource-deployment/custom-scripts/resource-deployment/templates/web-api-aad-acl-prod.json, packages/resource-deployment/custom-scripts/setup-configuration.sh, packages/resource-deployment/scripts/pool-startup/custom-pool-post-startup.ps1
Added custom scripts facility to support independent deployment.
Enabled OTelLoggerClient
=> Added custom scripts facility

packages/scanner-global-library/src/page-client-lib.ts, packages/scanner-global-library/src/page-navigator.spec.ts, packages/scanner-global-library/src/page-navigator.ts, packages/scanner-global-library/src/puppeteer-options.ts, packages/scanner-global-library/src/web-driver.ts
Switch to new chrome headless mode https://developer.chrome.com/articles/new-headless/
Run page context scripts with timeout to unblock page scanning.
=> Switch to new chrome headless mode

packages/logger/src/logger-event-measurements.ts, packages/logger/src/logger-event.ts, packages/logger/src/otel-config-provider.spec.ts, packages/logger/src/otel-config-provider.ts, packages/logger/src/otel-logger-client.ts, packages/privacy-scan-runner/src/runner/runner.spec.ts, packages/privacy-scan-runner/src/runner/runner.ts, packages/report-generator-runner/src/runner/request-selector.ts, packages/web-api-scan-request-sender/src/sender/on-demand-dispatcher.ts, packages/web-api-scan-request-sender/src/sender/scan-request-selector.ts
=> Added new metrics events

packages/cli/package.json, packages/common/src/system/system.spec.ts, packages/common/src/system/system.ts, packages/logger/package.json, packages/logger/src/otel-config-provider.spec.ts, packages/logger/src/otel-config-provider.ts, packages/logger/src/otel-logger-client.ts, packages/scanner-global-library/src/page.ts, yarn.lock
Migrated to use machine info from environment settings to reduce container startup time.
=> Migrated to use machine info from environment settings

packages/resource-deployment/scripts/function-app-create.sh, packages/resource-deployment/templates/e2e-site-storage.template.json
Fixed template update to prevent double append.
=> Fixed template update

azure-pipeline/build-artifacts-and-run-tests-job.yaml, packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/resource-deployment/custom-scripts/docker-image/Add-Font.ps1, packages/resource-deployment/custom-scripts/docker-image/Fonts.tar, packages/resource-deployment/custom-scripts/docker-image/README.md, packages/resource-deployment/scripts/deploy-e2e-test-site.sh, packages/resource-deployment/scripts/function-app-create.sh, packages/resource-deployment/scripts/install-parallel.sh, packages/resource-deployment/scripts/push-image-to-container-registry.sh, packages/resource-deployment/templates/e2e-site-storage.template.json
- Added deployment of E2E test website under service resource group to use dedicated test website per deployed service instance.
- Added docker image prerequisite validation.
=> Added deployment of test website

packages/scanner-global-library/src/network/page-request-interceptor.spec.ts, packages/scanner-global-library/src/network/page-request-interceptor.ts, packages/scanner-global-library/src/page-navigator.ts
Added page reload retry on reload error to unblock scanner workflow.
=> Added page reload retry on reload error

.vscode/workspace.code-workspace, packages/cli/README.md, packages/cli/package.json, packages/cli/src/cli.ts, packages/cli/src/crawler/crawler-parameters-builder.ts, packages/cli/src/scan-arguments.ts, packages/crawler/src/crawler/site-crawler-engine.ts, packages/crawler/src/logger/apify-console-logger-client.ts, packages/crawler/src/main.ts, packages/crawler/src/page-handler/page-response-processor.spec.ts, packages/crawler/src/page-handler/page-response-processor.ts, packages/crawler/src/page-processors/page-processor-base.ts, packages/crawler/src/types/crawler-run-options.ts, yarn.lock
Handle HTTP 304 response code.
=> Handle HTTP 304 response code

packages/web-api-scan-runner/src/scanner/deep-scanner.spec.ts, packages/web-api-scan-runner/src/scanner/deep-scanner.ts, packages/web-api-scan-runner/src/scanner/page-scan-processor.spec.ts, packages/web-api-scan-runner/src/scanner/page-scan-processor.ts, packages/web-workers/extensions.csproj
Enabled scan of know pages without page crawling.
=> Enabled scan of know pages without page crawling

packages/cli/package.json, packages/crawler/src/authenticator/azure-active-directory-authenticator.ts
Support CORS for page authentication.
=> Support CORS for page authentication 

packages/resource-deployment/scripts/create-function-app.sh, packages/resource-deployment/scripts/create-public-ip.sh, packages/resource-deployment/scripts/install-parallel.sh
Fixed DNS name generation to conform to DNS name convention.
Added .NET SDK availability check.
=> Fixed DNS name generation

packages/axe-core-scanner/package.json, packages/cli/package.json, packages/crawler/package.json, packages/privacy-scan-core/package.json, packages/privacy-scan-runner/package.json, packages/report-generator-runner/package.json, packages/scanner-global-library/package.json, packages/scanner-global-library/src/authenticator/login-page-detector.ts, packages/scanner-global-library/src/network/page-analyzer.spec.ts, packages/scanner-global-library/src/network/page-request-interceptor.spec.ts, packages/scanner-global-library/src/page.spec.ts, packages/service-library/package.json, packages/web-api-scan-runner/package.json, yarn.lock
Updated puppeteer npm version.
=> Updated puppeteer npm version

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/scanner-global-library/src/page-navigator.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts, packages/scanner-global-library/src/puppeteer-options.ts, packages/web-api-scan-runner/src/crawler/discovered-url-processor.spec.ts, packages/web-api-scan-runner/src/crawler/discovered-url-processor.ts, packages/web-api-scan-runner/src/scanner/deep-scanner.spec.ts, packages/web-api-scan-runner/src/scanner/deep-scanner.ts, packages/web-api-scan-runner/src/scanner/page-scan-processor.spec.ts, packages/web-api-scan-runner/src/scanner/page-scan-processor.ts, packages/web-api-scan-runner/src/website-builder/page-metadata-generator.spec.ts, packages/web-api-scan-runner/src/website-builder/page-metadata-generator.ts, packages/web-api-scan-runner/src/website-builder/url-location-validator.spec.ts, packages/web-api-scan-runner/src/website-builder/url-location-validator.ts
Ensure single browser instance is created per scan.
Added URL validator.
Extended banner detection timeout.
Refactoring.
=> Ensure single browser instance

packages/web-api-scan-runner/src/scanner/page-scan-processor.spec.ts, packages/web-api-scan-runner/src/scanner/page-scan-processor.ts
Skip scanning unknown authenticated URLs
=> Skip scanning unknown authenticated URLs

.gitignore, packages/axe-result-converter/package.json, packages/cli/package.json, packages/cli/src/package.json.spec.ts, packages/scanner-global-library/open-browser.sh, packages/scanner-global-library/src/authenticator/resource-authenticator.spec.ts, packages/scanner-global-library/src/authenticator/resource-authenticator.ts, packages/scanner-global-library/src/page-navigator.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts, packages/web-api-scan-runner/src/scanner/page-scan-processor.ts, yarn.lock
Navigate to URL for authentication when supported authentication was detected.
=> Navigate to URL for authentication

packages/web-workers/src/controllers/scan-batch-request-feed-controller.spec.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.ts
Remove deep scan id for a single type scan.
=> Remove deep scan id for a single type scan

packages/web-api-client/package.json, packages/web-api-client/src/a11y-service-credential.spec.ts, packages/web-api-client/src/a11y-service-credential.ts, yarn.lock
=> Migrated to MSAL node package

packages/resource-deployment/scripts/enable-system-identity-for-batch-vmss.sh
Fixed scope parameter for az cli command
=> Fixed scope parameter

packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts, packages/web-api-scan-runner/.vscode/launch.json, packages/web-api-scan-runner/docker-image-config/Dockerfile, packages/web-api-scan-runner/docker-image-config/Dockerfile.debug, packages/web-api-scan-runner/docker-image-config/web-api-scan-runner.ps1, packages/web-api-scan-runner/run-in-docker-container.cmd
- Support debugging in docker container
- Reload browser on page authentication
=> Support debugging in docker container

packages/scanner-global-library/src/page-navigation-error-patterns.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts
- Added browser error patterns
- Fixed page analysis on reloads
=> Added browser error patterns

.github/CODEOWNERS, .vscode/workspace.code-workspace, packages/common/src/system/url.spec.ts, packages/common/src/system/url.ts, packages/resource-deployment/templates/batch-account-ppe-pr.parameters.json, packages/resource-deployment/templates/batch-account-ppe.parameters.json, packages/scanner-global-library/src/network/page-analyzer.ts, packages/service-library/src/crawler/page-crawler-engine.spec.ts, packages/web-api-scan-runner/src/scanner/deep-scanner.spec.ts, packages/web-api-scan-runner/src/scanner/deep-scanner.ts
Removed duplicate URL from crawl result when discovered URL has hash fragment.
=> Removed duplicate URL from crawl result

packages/scanner-global-library/src/puppeteer-options.ts, packages/web-api-scan-runner/src/scanner/deep-scanner.spec.ts, packages/web-api-scan-runner/src/scanner/deep-scanner.ts
Enabled Web GL support for a browser.
=> Enabled Web GL support

packages/scanner-global-library/src/page-navigator.spec.ts, packages/scanner-global-library/src/page-navigator.ts, packages/scanner-global-library/src/page-timeout-config.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts
Fallback to default network browser options to reduce page load wait time.
=> Fallback to default network browser options

packages/scanner-global-library/src/network/page-event-handler.ts, packages/scanner-global-library/src/network/page-request-interceptor.spec.ts, packages/scanner-global-library/src/network/page-request-interceptor.ts, packages/scanner-global-library/src/page-timeout-config.ts, packages/scanner-global-library/src/puppeteer-options.ts, yarn.lock
Handle multiple redirects to the same URL to reduce page load time.
=> Handle multiple redirects to the same URL

packages/scanner-global-library/src/page.ts
=> Restricted page snapshot size

packages/azure-services/src/azure-batch/batch-task-config-generator.spec.ts, packages/azure-services/src/azure-batch/batch-task-config-generator.ts, packages/resource-deployment/templates/batch-account-dev.parameters.json, packages/resource-deployment/templates/batch-account-ppe-pr.parameters.json, packages/resource-deployment/templates/batch-account-ppe.parameters.json, packages/resource-deployment/templates/batch-account-prod-pr.parameters.json, packages/resource-deployment/templates/batch-account-prod.parameters.json, packages/resource-deployment/templates/batch-account.template.json, packages/resource-deployment/templates/blob-storage.template.json, packages/resource-deployment/templates/e2e-site-storage.template.json
Disable shared key authorization for storage accounts
=> Disable shared key authorization for web storage account

packages/resource-deployment/scripts/create-batch-account.sh, packages/resource-deployment/scripts/create-key-vault.sh, packages/resource-deployment/templates/batch-account-dev.parameters.json, packages/resource-deployment/templates/batch-account-ppe-pr.parameters.json, packages/resource-deployment/templates/batch-account-ppe.parameters.json, packages/resource-deployment/templates/batch-account-prod-pr.parameters.json, packages/resource-deployment/templates/batch-account-prod.parameters.json, packages/resource-deployment/templates/batch-account.template.json, packages/resource-deployment/templates/vnet.template.json
Disable Batch pool virtual network for dev environment.
=> Disable Batch pool virtual network for dev environment

packages/resource-deployment/scripts/pool-startup/install-docker-engine.ps1, packages/resource-deployment/templates/batch-account.template.json
Handle VM network adapter availability.
=> Handle VM network adapter availability

packages/resource-deployment/scripts/pool-startup/install-docker-engine.ps1, packages/resource-deployment/templates/batch-account.template.json
Disabled VMSS accelerated networking as it fails to create network adapter.
=> Disabled VMSS accelerated networking

packages/resource-deployment/templates/blob-storage.template.json, yarn.lock
Disabled storage shared key access.
=> Disabled storage shared key access

packages/resource-deployment/templates/batch-account-ci.parameters.json, packages/resource-deployment/templates/batch-account-dev.parameters.json, packages/resource-deployment/templates/batch-account-ppe-eu.parameters.json, packages/resource-deployment/templates/batch-account-ppe.parameters.json, packages/resource-deployment/templates/batch-account-prod-eu.parameters.json, packages/resource-deployment/templates/batch-account-prod.parameters.json, packages/resource-deployment/templates/batch-account.template.json
Switched to widely available VM SKU version.
=> Switched to available VM SKU version

packages/resource-deployment/templates/cosmos-db.template.json
=> Disabled Cosmos local auth

packages/resource-deployment/scripts/create-container-registry.sh, packages/resource-deployment/scripts/create-role-assignment.sh, packages/resource-deployment/scripts/enable-batch-node-identity.sh, packages/resource-deployment/scripts/pool-startup/pull-image-from-registry.ps1, packages/resource-deployment/scripts/push-secrets-to-key-vault.sh, packages/resource-deployment/templates/batch-account-custom-role.json, packages/resource-deployment/templates/container-registry.template.json, yarn.lock
Migrated to use managed Identity with Azure Container Registry.
Added Batch service custom role.
=> Migrated to use managed Identity with Azure Container Registry

packages/resource-deployment/scripts/enable-batch-node-identity.sh, packages/resource-deployment/templates/batch-account-custom-role.json
Create custom RBAC role per subscription scope.
=> Create custom RBAC role per subscription scope

packages/api-contracts/openapi.json, packages/service-library/src/scanner/scan-feed-generator.ts, packages/service-library/src/web-api/api-contracts/scan-result-response.ts, packages/storage-documents/src/index.ts, packages/storage-documents/src/on-demand-page-scan-result.ts, packages/storage-documents/src/request-type-converter.spec.ts, packages/storage-documents/src/request-type-converter.ts, packages/web-api-scan-runner/src/processor/high-contrast-scanner.ts, packages/web-api-scan-runner/src/processor/page-scan-processor.ts, packages/web-api-scan-runner/src/runner/runner.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.ts
Enabled browser validation for a deep scan request.
=> Enabled browser validation for a deep scan request

packages/cli/package.json, packages/cli/src/axe/axe-info.ts, packages/cli/src/baseline/baseline-file-updater.ts, packages/cli/src/baseline/baseline-options-builder.ts, packages/cli/src/crawler/crawler-parameters-builder.ts, packages/cli/src/files/output-file-writer.ts, packages/cli/src/runner/crawler-command-runner.ts, packages/crawler/src/apify/apify-request-queue-creator.ts, packages/crawler/src/common/hash-generator.ts, packages/crawler/src/common/promise-utils.ts, packages/crawler/src/crawler/crawler-configuration.ts, packages/crawler/src/crawler/site-crawler-engine.ts, packages/crawler/src/level-storage/data-base.ts, packages/crawler/src/logger/apify-console-logger-client.ts, packages/crawler/src/logger/logger.ts, packages/crawler/src/page-handler/page-handler.spec.ts, packages/crawler/src/page-handler/page-handler.ts, packages/crawler/src/page-handler/page-navigation-hooks.ts, packages/crawler/src/page-handler/page-response-processor.spec.ts, packages/crawler/src/page-handler/page-response-processor.ts, packages/crawler/src/page-processors/page-processor-base.ts, packages/crawler/src/page-processors/simulator-page-processor.ts
Converted optional ctor parameters to inversify optional.
=> Converted optional ctor parameters to inversify optional

package.json, packages/axe-core-scanner/package.json, packages/azure-services/package.json, packages/cli/package.json, packages/common/package.json, packages/crawler/package.json, packages/e2e-web-apis/package.json, packages/health-client/package.json, packages/logger/package.json, packages/parallel-workers/package.json, packages/privacy-scan-core/package.json, packages/privacy-scan-job-manager/package.json, packages/privacy-scan-runner/package.json, packages/report-generator-job-manager/package.json, packages/report-generator-runner/package.json, packages/scanner-global-library/package.json, packages/service-library/package.json, packages/web-api-scan-job-manager/package.json, packages/web-api-scan-request-sender/package.json, packages/web-api-scan-runner/package.json, packages/web-api-send-notification-job-manager/package.json, packages/web-api-send-notification-runner/package.json, packages/web-api/package.json, packages/web-workers/package.json, yarn.lock
Combined dependabot PRs.
dependabot/npm_and_yarn/puppeteer-23.9.0
dependabot/npm_and_yarn/shellcheck-3.0.0
dependabot/npm_and_yarn/eslint-plugin-import-2.31.0
dependabot/npm_and_yarn/rollup/plugin-node-resolve-15.3.0
dependabot/npm_and_yarn/commander-12.1.0
dependabot/npm_and_yarn/pretty-format-29.7.0
dependabot/npm_and_yarn/types/convict-6.1.6
dependabot/npm_and_yarn/azure/core-auth-1.9.0
dependabot/npm_and_yarn/webpack-cli-5.1.4
dependabot/npm_and_yarn/ts-loader-9.5.1
dependabot/npm_and_yarn/azure-functions-core-tools-4.0.6610
dependabot/npm_and_yarn/playwright/test-1.49.0
dependabot/npm_and_yarn/opentelemetry/sdk-metrics-1.28.0
dependabot/npm_and_yarn/ajv-8.17.1
dependabot/npm_and_yarn/types/escape-html-1.0.4
dependabot/npm_and_yarn/typescript-eslint/parser-8.16.0
=> Combined dependabot PRs

azure-pipeline/Accessibility_Insights_Service_CI_1ESPT_Official.yml, package.json, yarn.lock
- Added official template yml for production ci pipeline.
- Enabling `PoliCheck` and `TSAUpload` task in official template to remove the dependency from classic pipeline [Accessibility Insights Service SDT CI](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build?definitionId=22&_a=summary).
- added `pac-resolver` and `socks` in resolution to fix the CG alert. Currently referred version of these packages has dependency on `ip` which is unmaintained and having vulnerability which trigger CG alert in pipeline and breaking the pipeline run [#main_20250130.2](https://dev.azure.com/mseng/1ES/_build/results?buildId=29559677&view=logs&j=e8e57932-801d-572a-bfac-91f751751770&t=7e20f90f-3861-5987-6717-85a5ed8c3233&l=9424). These packages have removed the …
=> chore: Added official template yml for production ci pipeline

packages/scanner-global-library/src/authenticator/azure-login-page-client.spec.ts, packages/scanner-global-library/src/authenticator/azure-login-page-client.ts
Added support of optional app permission request at sign-in.
=> Added support of app permission request at sign-in

packages/privacy-scan-runner/run-in-docker-container.cmd, packages/resource-deployment/scripts/docker-scanner-image/Dockerfile.scanner, packages/resource-deployment/scripts/docker-scanner-image/enable-virtual-display.ps1, packages/resource-deployment/scripts/docker-scanner-image/install-font-packages.ps1, packages/resource-deployment/scripts/pool-startup/install-docker-engine.ps1, packages/resource-deployment/scripts/pool-startup/pull-image-from-registry.ps1, packages/scanner-global-library/src/page-handler.spec.ts, packages/scanner-global-library/src/page-handler.ts, packages/scanner-global-library/src/page-navigation-hooks.ts, packages/scanner-global-library/src/page-timeout-config.ts, packages/scanner-global-library/src/page-webgl-client-lib.ts, packages/scanner-global-library/src/puppeteer-options.ts, packages/scanner-global-library/src/web-driver.spec.ts, packages/web-api-scan-runner/docker-image-config/Dockerfile, packages/web-api-scan-runner/docker-image-config/Dockerfile.debug, packages/web-api-scan-runner/docker-image-config/web-api-scan-runner.ps1, packages/web-api-scan-runner/run-in-docker-container.cmd
- Enhance Docker configuration and WebGL optimizations for improved performance
- Enable font installation during scanner image build process
=> feat: enhance Docker configuration and WebGL optimizations for improved performance

packages/scanner-global-library/src/authenticator/login-page-detector.spec.ts, packages/scanner-global-library/src/authenticator/login-page-detector.ts
Enhance login page detection for various authentication providers.
=> feat: enhance login page detection for various authentication providers

packages/api-contracts/openapi.json, packages/service-library/src/web-api/api-contracts/scan-result-response.ts, packages/service-library/src/web-api/api-contracts/scan-run-request.spec.ts, packages/service-library/src/web-api/api-contracts/scan-run-request.ts, packages/storage-documents/src/on-demand-page-scan-request.ts, packages/storage-documents/src/on-demand-page-scan-result.ts, packages/web-api-scan-request-sender/src/sender/on-demand-dispatcher.spec.ts, packages/web-api-scan-request-sender/src/sender/on-demand-dispatcher.ts, packages/web-api/src/controllers/scan-request-controller.spec.ts, packages/web-api/src/controllers/scan-request-controller.ts, packages/web-api/src/converters/scan-response-converter.spec.ts, packages/web-api/src/converters/scan-response-converter.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.spec.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.ts
- Added ScanDefinition to support arbitrary scan definition
- Added scanRunDetails to API contracts for enhanced scanner results
=> feat: Update REST API to support arbitrary scan definition

yarn.lock
Update tmp npm to version 0.2.4
=> chore(deps): update tmp to version 0.2.4
