packages/logger/src/app-insights-logger-client.spec.ts, packages/logger/src/app-insights-logger-client.ts
Change app insights config so that console/logger activity and requests will be sent to Application Insights, so that we can get tracking events details for failed tasks.
=> Enable app insights auto collect console and requests

packages/runner/src/crawler/hc-crawler-options-factory.ts, packages/runner/src/crawler/launch-options-factory.spec.ts, packages/runner/src/crawler/link-explorer.spec.ts, packages/runner/src/runner/runner.spec.ts, packages/runner/src/runner/runner.ts, packages/runner/src/scanner/page.ts, packages/runner/src/tasks/crawler-task.spec.ts, packages/runner/src/tasks/crawler-task.ts, packages/runner/test-utilities/common-mock-methods.ts
Currently we only check if the url is supported when we are about to crawl the page, but we are not excluding unsupported pages in the crawl result. Thus those unsupported pages are still being scanned.
1. ignore urls end with .yaml;
2. Avoid adding urls that are not allowed into the crawl result.
=> Avoid scanning on unsupported pages

package.json, packages/scan-request-sender/src/sender/scan-request-sender.spec.ts, packages/scan-request-sender/src/sender/scan-request-sender.ts, packages/storage-documents/src/index.ts, packages/storage-documents/src/scan-request-message.ts
Only a subset of the data will now be enqueued. This will help us queue more items.
This includes - 
- websiteId
- baseUrl
- url
=> Queued messages are now smaller

packages/runner/src/factories/page-scan-result-factory.spec.ts, packages/runner/src/factories/page-scan-result-factory.ts, packages/runner/src/scanner/axe-scan-results.ts, packages/runner/src/scanner/page.spec.ts, packages/runner/src/scanner/page.ts, packages/runner/src/scanner/scanner.spec.ts, packages/runner/src/scanner/scanner.ts, packages/runner/src/tasks/data-factory-task.spec.ts, packages/runner/src/tasks/data-factory-task.ts, packages/runner/src/tasks/page-state-updater-task.spec.ts, packages/runner/src/tasks/page-state-updater-task.ts, packages/storage-documents/src/issue-scan-result.ts, packages/storage-documents/src/run-result.ts, packages/storage-documents/src/website-page.ts
Before we run a11y scan on a page, I'm making the change to check the response header of the page, if it is not 'text/html', we return error information and skip the scan.
Then the page document will have a flag ``unscannable = true`` in its last run property.
=> Mark unscannable pages

packages/service-library/src/data-providers/page-document-provider.db.spec.ts, packages/service-library/src/data-providers/page-document-provider.spec.ts, packages/service-library/src/data-providers/page-document-provider.ts, packages/service-library/src/test-utilities/db-mock-helpers.ts
Updated to run query differently based on deep scanning flag.
=> Updated to run query differently based on deep scanning flag.

.github/CODEOWNERS
We've started updating all the accessibility insights repos to use a shared CODEOWNERS team, rather than maintaining separate ones per project. This brings accessibility-insights-service up to date with this new policy.
- [n/a] Ran precheckin (`yarn precheckin`)
=> Generalize CODEOWNERS to use whole-team instead of service-specific team

packages/job-manager/webpack.config.js, packages/runner/webpack.config.js, packages/scan-request-sender/webpack.config.js
The problem is that Webpack favors modules import over CommonJS by default. This is different from Node which results in mixing import and require.
When Node sees require("node-fetch), it'll pick the main config while Webpack picks module.
So we need to reconfigure webpack to pick main config.
=> Fix for TypeError: fetch is not a function

packages/job-manager/src/worker/worker.spec.ts, packages/job-manager/src/worker/worker.ts
`if (poolMetricsInfo.load.activeTasks === 0 && poolMetricsInfo.load.runningTasks === 0)`
Will always be false because running task will be at least 1 which is the job-manager task itself so this is gonna cause infinite loop and the job will never end, it should be 
`if (poolMetricsInfo.load.activeTasks === 0 && poolMetricsInfo.load.runningTasks === 1)`
=> Fix infinite loop in worker "wait till all running tasks are done"

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/general_question.md
Updated the help text in GitHub bug report, feature request, and general question templates as comments so they don't appear in the issue that gets filed if the user doesn't remove it.
**Note:** I also changed the section headings in the bug report and feature request templates to markdown headings (##) for consistency with AI Web repo. If there is a preference for using emphasis (**) instead, I can change these back.
- [n/a] Ran precheckin (`yarn precheckin`)
=> chore: update templates to use headings and comments

packages/azure-services/src/storage/cosmos-container-client.spec.ts, packages/azure-services/src/storage/cosmos-container-client.ts, packages/service-library/src/data-providers/on-demand-page-scan-run-result-provider.db.spec.ts, packages/service-library/src/data-providers/on-demand-page-scan-run-result-provider.spec.ts, packages/service-library/src/data-providers/on-demand-page-scan-run-result-provider.ts, packages/web-api-scan-job-manager/.vscode/launch.json, packages/web-api-scan-job-manager/.vscode/tasks.json, packages/web-api-scan-request-sender/.vscode/launch.json, packages/web-api-scan-request-sender/.vscode/tasks.json, packages/web-api-scan-runner/.vscode/launch.json, packages/web-api-scan-runner/.vscode/tasks.json, packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts
Reduce number of calls to Cosmos DB in scan runner
Enable Cosmos DB document merge with properties reset
Fix dev debug experience
=> Reduce number of calls to Cosmos DB in scan runner

packages/resource-deployment/templates/rest-api-templates/model-accessibility-insight-service-scan-api-api.template.json
Add the redirect-content-urls policy to API manager so that the scan response report link points to the API gateway url instead of the function app url. (Fixes #349)
=> add redirect-content-urls policy to APIM

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts
Reducing batch request size from 1000 to 250, which will help us improve design going forward. 
If we decided to send request directly to storage queue, we need to make sure request size is not more than 80KB.
=> reducing the default batch size from 1000 to 250.

packages/logger/src/app-insights-logger-client.spec.ts, packages/logger/src/app-insights-logger-client.ts, packages/logger/src/console-logger-client.spec.ts, packages/logger/src/console-logger-client.ts, packages/logger/src/index.ts, packages/logger/src/logger-client.ts, packages/logger/src/logger-event-measurements.ts, packages/logger/src/logger-event.ts, packages/logger/src/logger.spec.ts, packages/logger/src/logger.ts, packages/web-api-scan-job-manager/src/worker/worker.spec.ts, packages/web-api-scan-job-manager/src/worker/worker.ts
- Make measurements data more strongly typed so that anyone cannot pass random dictionary into the ``trackEvent()`` function as event data.
- Add batch pool stat track events in web-api work flow.
- Update relevant unit tests.
- Validated it locally & in Azure:
=> Track batch pool metrics when job manager queues tasks

packages/logger/src/index.ts, packages/logger/src/logger-event-measurements.ts, packages/logger/src/logger-event.ts, packages/web-api-scan-request-sender/src/sender/on-demand-dispatcher.spec.ts, packages/web-api-scan-request-sender/src/sender/on-demand-dispatcher.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.spec.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.ts
- Track scan urls added for processing events in web workers.
- ``ScanUrlsAddedForProcessing`` events will be sent per ``OnDemandPageScanBatchRequest`` document processed.
=> Telemetry events added for web worker and request sender

package.json, packages/web-workers/package.json, yarn.lock
Upgrading puppeteer to 2.x & using 3.x version of https-proxy-agent
Both the package' breaking changes doesnt seem to affect our usage.
I will trigger a deployment to validate this
=> fix vulnerability issue caused by https-proxy-agent

packages/resource-deployment/templates/dashboard.template.json
Add availability and reliability place holder chart to dashboard.
These two charts will be finalized when we have real availability data.
=> Add availability and reliability place holder chart to dashboard

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/common/src/index.ts, packages/scanner/src/axe-scan-results.ts, packages/scanner/src/index.ts, packages/scanner/src/page.spec.ts, packages/scanner/src/page.ts, packages/service-library/src/web-api/api-controller.spec.ts, packages/service-library/src/web-api/scan-run-error-codes.ts, packages/storage-documents/src/issue-scan-result.ts, packages/storage-documents/src/on-demand-page-scan-result.ts, packages/storage-documents/src/run-result.ts, packages/web-api-scan-runner/src/runner/runner.ts, packages/web-api/src/converters/scan-run-error-converter.spec.ts, packages/web-api/src/converters/scan-run-error-converter.ts, packages/web-workers/src/controllers/health-monitor-orchestration-controller.spec.ts, packages/web-workers/src/controllers/health-monitor-orchestration-controller.ts, packages/web-workers/src/orchestration-steps.spec.ts, packages/web-workers/src/orchestration-steps.ts
- Fixed a bug in sending the navigation failure response code. (#415)
- Storing parsed error object instead of storing error string. I am also handling back compatibility.
- added availability test config - Using scan interval time of 1 min & configurable scan url.
(Triggered deployment on my private resource group for validation)
=> Storing parsed scan error object in storage document

package.json, yarn.lock
Fix for serialize-javascript npm vulnerability as per https://github.com/microsoft/accessibility-insights-service/network/alert/yarn.lock/serialize-javascript/open
=> Fix for serialize-javascript npm vulnerability

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/web-api/src/controllers/health-check-controller.spec.ts, packages/web-api/src/controllers/health-check-controller.ts
Reduce timespan queried for e2e test runs and make this value configurable
=> Add query timespan to serviceConfig

packages/resource-deployment/templates/dashboard.template.json
Added new tiles to dashboard to show most recent test runs ans passes/failures over time:
=> Add E2E results to dashboard

packages/health-client/src/health-checker.ts
When request fails, if we log the whole response object it will include the request itself which contains the bearer token, we do not want the token to be logged in the pipeline. 
The response body has enough info already.
=> Log response body only

packages/health-client/src/health-checker.ts
Fix error message when the functional tests are not passing. When we get 'warn' or no result yet, we should not say they are failing.
=> Fix logging message

packages/api-contracts/ai-scan-api.yaml, packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/common/src/index.ts, packages/common/src/system/promise-utils.spec.ts, packages/common/src/system/promise-utils.ts, packages/scanner/src/axe-scan-results.ts, packages/scanner/src/factories/axe-puppeteer-factory.spec.ts, packages/scanner/src/scanner.spec.ts, packages/scanner/src/scanner.ts, packages/service-library/src/data-providers/page-document-provider.db.spec.ts, packages/service-library/src/data-providers/page-document-provider.spec.ts, packages/service-library/src/web-api/scan-run-error-codes.ts, packages/storage-documents/src/on-demand-page-scan-result.ts
This PR adds a timeout around scanning. If configured timeout is reached, the scanner completes with a successful promise object that contains error object set to scanTimeout.
=> adding timeout for scaning

packages/functional-tests/src/test-groups/scan-status-test-group.ts, packages/web-api/package.json, packages/web-api/src/controllers/base-scan-result-controller.ts, packages/web-api/src/controllers/batch-scan-result-controller.spec.ts, packages/web-api/src/controllers/scan-result-controller.spec.ts
Validate the timestamp in the guid is in the past and return invalid guid response if it's not.
Also since we are using moment for time manipulation, I replaced some Date usage with moment.
=> Validate the timestamp in the guid

packages/resource-deployment/scripts/function-app-create.sh
- So we are downgrading the Azure Function Core Tool version to avoid this issue for now: https://github.com/Azure/azure-functions-core-tools/issues/1793
- We should revert this change once this PR is merged: https://github.com/Azure/azure-functions-core-tools/issues/1793
=> Downgrade Azure Functions Core Tool to 2.7.1948-1

packages/resource-deployment/scripts/function-app-create.sh, packages/service-library/src/web-api/web-controller.spec.ts, packages/service-library/src/web-api/web-controller.ts
Set 'X-Content-Type-Options' to 'nosniff' 
Required as a part of our compliance process, on-boarding to web-scout tool.
=> Set HTTP response header 'X-Content-Type-Options' to 'nosniff'

packages/cli/package.json, packages/cli/webpack.config.js
- Remove '#!/usr/bin/env node' banner from the library.
- Increase tje minor version to push a new release.
=> chore: Use node banner plugin only for CLI

packages/service-library/src/process-entry-point-base.spec.ts, packages/service-library/src/process-entry-point-base.ts
We are temporarily fixing the node process not getting killed issue by terminating it after task completion. we need to identify what causes this issue. But, temporarily we are doing this to unblock us.
=> fix: fixing node process not exiting after complete

packages/cli/package.json, packages/cli/src/factories/axe-puppeteer-factory.spec.ts, packages/cli/src/factories/axe-puppeteer-factory.ts, packages/cli/src/scanner/ai-scanner.spec.ts, packages/cli/src/scanner/ai-scanner.ts, packages/cli/src/scanner/page.spec.ts, packages/cli/src/scanner/page.ts
Add a parameter for axe source code file path so we can use it in case calling the library through a GitHub action.
=> chore: Add a parameter for axe source code file path

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/logger/package.json, packages/logger/src/base-app-insights-logger-client.spec.ts, packages/logger/src/base-app-insights-logger-client.ts, packages/logger/src/base-console-logger-client.ts, packages/logger/src/global-logger.spec.ts, packages/logger/src/logger-client.ts, packages/logger/src/logger.ts, packages/resource-deployment/runtime-config/runtime-config.prod.json, packages/service-library/src/process-entry-point-base.spec.ts, packages/service-library/src/process-entry-point-base.ts, yarn.lock
- We should wait for the app insights log flush before exiting, as it is asynchronous operation.
- Making process exit configurable, we only enable this on prod, so that we can investigate if this happens again in ppe.
=> fix: wait till app insights log flush before process exit

packages/service-library/src/web-api/web-controller-dispatcher.spec.ts, packages/service-library/src/web-api/web-controller-dispatcher.ts
This fixes the bug where the contextAwareLogger throws if setup is not called before logging.
=> fix: setup request context logger before using

packages/web-workers/extensions.csproj
Downgrade ExtensionsMetadataGenerator since a recent update was causing canary to break.
=> fix: downgrade ExtensionsMetadataGenerator

packages/resource-deployment/scripts/batch-account-create.sh, packages/resource-deployment/scripts/install-parallel.sh, packages/resource-deployment/scripts/pool-startup/pool-startup-internal.sh, packages/resource-deployment/scripts/pool-startup/pool-startup.sh, packages/resource-deployment/scripts/process-utilities.sh, packages/resource-deployment/scripts/recreate-vmss-for-pools.sh, packages/resource-deployment/scripts/restart-vm-pools.sh, packages/resource-deployment/scripts/run-command-on-all-vmss-for-pool.sh, packages/resource-deployment/scripts/run-command-when-batch-nodes-are-idle.sh, packages/resource-deployment/scripts/setup-all-pools-for-batch.sh
reset dpkg configuration in pool startup script (If we reboot a node, when installation is happening, it corrupts the dpkg configuration. To solve this, we need to run dpkg configure -a). 
moved common script utitlies like runinparallel & waitForProcess to a new file (process-utilities.sh)
Triggered validation here - https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_releaseProgress?_a=release-environment-logs&releaseId=3247&environmentId=4746
=> chore: refactor restart & recreate pools;

packages/web-api-scan-request-sender/src/sender/on-demand-dispatcher.spec.ts, packages/web-api-scan-request-sender/src/sender/on-demand-dispatcher.ts
we were always adding items to queue in multiples of 100. So, even if we set maxQueueSize to 20, we will end up adding 100
=> fix: fix bug in total items added to queue.

package.json, yarn.lock
Upgrade minimist dependency to 1.2.2 to fix github security alert
=> chore: upgrade minimist to 1.2.2

packages/service-library/src/web-api/api-contracts/scan-run-request.ts, packages/service-library/src/web-api/web-api-error-codes.ts, packages/storage-documents/src/on-demand-page-scan-batch-request.ts, packages/storage-documents/src/on-demand-page-scan-request.ts, packages/web-api/src/controllers/scan-request-controller.spec.ts, packages/web-api/src/controllers/scan-request-controller.ts
Accept reply url sending with the request and save it into the database. 
Will check if the reply url is valid if the user does provide it. If not, will return an error response.
Api version management refactor will be a separate PR. We might need to put that in the service config.
=> feat (send-notification): update post scan api to accept reply url

packages/web-api-send-notification-job-manager/src/index.ts, packages/web-api-send-notification-job-manager/src/send-notification-job-manager-entry-point.spec.ts, packages/web-api-send-notification-job-manager/src/send-notification-job-manager-entry-point.ts, packages/web-api-send-notification-job-manager/src/setup-send-notification-job-manager-container.spec.ts, packages/web-api-send-notification-job-manager/src/setup-send-notification-job-manager-container.ts, packages/web-api-send-notification-job-manager/src/task/send-notification-task-creator.spec.ts, packages/web-api-send-notification-job-manager/src/task/send-notification-task-creator.ts, packages/web-api-send-notification-job-manager/src/test-utilities/mockable-logger.ts
This PR doesnt have changes required to create the notification runner tasks. It just adds the setup code for dependency injection & execution.
=> feat (send-notification): adding initial setup code for send notification job manager

packages/azure-services/src/credentials/msi-credential-provider.spec.ts, packages/azure-services/src/credentials/msi-credential-provider.ts, packages/common/src/system/retry-helper.ts
Retry on errors when fetching token in MSICredentialsProvider
=> fix: add retry to MsiCredentialProvider

packages/functional-tests/src/test-groups/scan-reports-test-group.ts, packages/functional-tests/src/test-groups/scan-status-test-group.ts, packages/web-api/get-report-func/function.json, packages/web-api/get-scan-func/function.json
Previously we were throwing 404 if the user asked for scan status or report with anything not formatted as a guid. This will allow us to return an error message instead, as was intended.
=> fix: return InvalidResourceId on invalid guid

packages/azure-services/src/azure-queue/queue.spec.ts, packages/azure-services/src/azure-queue/queue.ts, packages/logger/src/logger-properties.ts, packages/service-library/src/batch/batch-task-creator.spec.ts, packages/service-library/src/batch/batch-task-creator.ts, packages/service-library/src/index.ts
Adding base class for creating tasks under batch job manager task.
The base class is created from https://github.com/microsoft/accessibility-insights-service/blob/master/packages/web-api-scan-job-manager/src/worker/worker.ts
(I will be refactoring this file to extend the base class in next pr)
This class is not used yet. the task creator in web-api-job-manager & notification job manager will extend this class.
Added getMessages by message count on queue to support making multiple calls
=> feat (send-notification): adding base class for creating tasks

packages/azure-services/src/azure-batch/pool-load-generator.spec.ts, packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/job-manager/src/batch/pool-load-generator.spec.ts, packages/job-manager/src/worker/worker.spec.ts, packages/service-library/src/batch/batch-task-creator.ts, packages/web-api-scan-job-manager/src/web-api-scan-job-manager-entry-point.spec.ts, packages/web-api-scan-job-manager/src/web-api-scan-job-manager-entry-point.ts, packages/web-api-scan-job-manager/src/worker/__snapshots__/worker.spec.ts.snap, packages/web-api-scan-job-manager/src/worker/worker.spec.ts, packages/web-api-scan-job-manager/src/worker/worker.ts, packages/web-api-send-notification-job-manager/src/send-notification-job-manager-entry-point.spec.ts, packages/web-api-send-notification-job-manager/src/send-notification-job-manager-entry-point.ts, packages/web-api-send-notification-job-manager/src/task/send-notification-task-creator.spec.ts, packages/web-api-send-notification-job-manager/src/task/send-notification-task-creator.ts
refactored web-api-job-manager's Worker to use the base class BatchTaskCreator.
This pr also fixes not to add more tasks than the maximum allowed running tasks. 
=> feat(send-notification): adding scan notification task creator

packages/service-library/src/data-providers/on-demand-page-scan-run-result-provider.spec.ts, packages/service-library/src/data-providers/on-demand-page-scan-run-result-provider.ts, packages/storage-documents/src/on-demand-page-scan-result.ts, packages/storage-documents/src/on-demand-scan-request-message.ts, packages/web-api-scan-request-sender/src/sender/on-demand-scan-request-sender.spec.ts, packages/web-api-scan-request-sender/src/sender/on-demand-scan-request-sender.ts, packages/web-api-scan-runner/run-script/start-web-api-scan-runner.sh, packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts, packages/web-api-scan-runner/src/scan-metadata-config.spec.ts, packages/web-api-scan-runner/src/scan-metadata-config.ts, packages/web-api-scan-runner/src/types/scan-metadata.ts, packages/web-api-send-notification-runner/src/sender/notification-sender.spec.ts, packages/web-api-send-notification-runner/src/sender/notification-sender.ts
- Remove unused priority field from OnDemandScanRequestMessage
- Add batchRequestId to OnDemandScanRequestMessage
- Refactor updateScanRuns to accept a partial document (with only id required)
- Refactor runner to update the scan run document without first reading it
=> fix: update scan run without reading first

packages/resource-deployment/scripts/batch-account-create.sh, packages/resource-deployment/scripts/recreate-vmss-for-pools.sh, packages/resource-deployment/templates/batch-account-dev.parameters.json, packages/resource-deployment/templates/batch-account-prod.parameters.json, packages/resource-deployment/templates/batch-account.template.json
- Resize all batch pools to 1 node for dev and ci environments
- Scale up url-scan-pool from 3 to 6 nodes in prod and ppe
This should bring batch costs down by more than half in dev resource groups (from ~$17 to ~$8 per day)
=> fix: resize batch pools

packages/azure-services/src/azure-queue/queue.spec.ts, packages/azure-services/src/azure-queue/queue.ts, packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/common/src/index.ts, packages/resource-deployment/runtime-config/runtime-config.ci.json, packages/resource-deployment/runtime-config/runtime-config.dev.json, packages/resource-deployment/runtime-config/runtime-config.ppe.json, packages/resource-deployment/runtime-config/runtime-config.prod.json, packages/resource-deployment/runtime-config/runtime-config.selftest.json, packages/resource-deployment/templates/on-demand-send-notification-schedule.template.json, packages/scan-request-sender/src/sender/scan-request-sender.spec.ts, packages/scanner/src/factories/axe-puppeteer-factory.spec.ts, packages/service-library/src/data-providers/page-document-provider.db.spec.ts, packages/service-library/src/data-providers/page-document-provider.spec.ts, packages/storage-documents/src/index.ts, packages/storage-documents/src/on-demand-notification-request-message.ts, packages/web-api-scan-request-sender/src/sender/on-demand-scan-request-sender.spec.ts, packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts, packages/web-api-scan-runner/src/tasks/notification-dispatcher.spec.ts, packages/web-api-scan-runner/src/tasks/notification-dispatcher.ts, packages/web-api-scan-runner/src/tasks/notification-queue-message-sender.spec.ts, packages/web-api-scan-runner/src/tasks/notification-queue-message-sender.ts, packages/web-api-send-notification-runner/src/sender/notification-sender.spec.ts, packages/web-api-send-notification-runner/src/sender/notification-sender.ts
- Create notification message on scan completion at the end of web-api-scan-runner if the send-notification feature flag is on and the scan-notify-url isn't empty!
=> feat (send-notification): create notification message on scan completion

packages/resource-deployment/scripts/app-insights-create.sh, packages/resource-deployment/scripts/batch-account-create.sh, packages/resource-deployment/scripts/create-api-management.sh, packages/resource-deployment/scripts/create-dashboard.sh, packages/resource-deployment/scripts/create-datalake-storage-account.sh, packages/resource-deployment/scripts/create-storage-account.sh, packages/resource-deployment/scripts/create-vnet.sh, packages/resource-deployment/scripts/deploy-rest-api.sh, packages/resource-deployment/scripts/function-app-create.sh, packages/resource-deployment/scripts/setup-cosmos-db.sh
The `group deployment` command is deprecated in the most recent version of the azure cli. This will replace it with the new `deployment group` command.
=> fix: use deployment group instead of group deployment

packages/resource-deployment/templates/batch-account-dev.parameters.json, packages/web-api-send-notification-job-manager/src/index.ts
- change OnDemandScanRequestPool from 1 to 2 nodes because the notification sender will have 2 tasks
- Remove "not implemented" error from send notification job manager
=> fix: scale up scan request pool to 2 nodes

packages/resource-deployment/templates/on-demand-scan-req-schedule.template.json
- Set scan request sender job priority to 1000, while notification job is still 0, so scan request sender won't starve if too many notifications are being sent.
=> chore: Set Scan Request Sender Job Priority to Maximum

packages/web-api/src/converters/scan-error-converter.ts, packages/web-api/src/converters/scan-response-converter.spec.ts, packages/web-api/src/converters/scan-response-converter.ts
fix: only add error prop in get scan response if there is error in db document
=> fix: only add error prop in get scan response if there is error in db document

packages/web-api/src/process-request.spec.ts, packages/web-workers/src/process-web-request.spec.ts
these tests loads the whole framework causing the test to take more time causing flakiness
=> fix: increase timeout for controller tests

packages/storage-documents/src/on-demand-page-scan-result.ts, packages/web-api-scan-request-sender/package.json, packages/web-api-scan-request-sender/src/sender/on-demand-scan-request-sender.spec.ts, packages/web-api-scan-request-sender/src/sender/on-demand-scan-request-sender.ts
Mark scans that failed to enqueue as failed with error info and delete them in the scan request container.
=> chore: Mark scans that failed to enqueue as failure with error info

jest.config.base.js, package.json, yarn.lock
We added this to make it easy to identify the slow running tests to fix https://github.com/microsoft/accessibility-insights-service/issues/601
Now except for the processWebRequest (which is like integration test, all other tests take < 100ms)
=> chore: remove jest-slow-test-reporter

packages/azure-services/src/azure-cosmos/cosmos-client-wrapper.ts, packages/azure-services/src/storage/client.ts, packages/web-api-send-notification-runner/src/sender/notification-sender.spec.ts, packages/web-api-send-notification-runner/src/sender/notification-sender.ts
This PR extends considering all result codes between 200-299 as successful instead of just 200.
=> fix: check successful response code instead of 200 for notification

packages/resource-deployment/package.json, packages/web-workers/src/controllers/health-monitor-orchestration-controller.ts, yarn.lock
cpx uses chokidar 1.7 which has vulnerability. The package has not been updated for past 4 years.
So, using cpy-cli package instead.
Also, upgraded all dependencies by deleting lock file & creating it again.
=> chore (deps): using cpy-cli instead of cpx package

package.json, yarn.lock
Using resolutions approach as some of the dependencies are depending on older major versions.
Validated here - https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_releaseProgress?_a=release-pipeline-progress&releaseId=3771
=> chore(deps): Force upgrade kind-of & yargs-parser to fix vulnerabilities

packages/resource-deployment/runtime-config/runtime-config.ci.json, packages/resource-deployment/runtime-config/runtime-config.dev.json, packages/resource-deployment/runtime-config/runtime-config.ppe.json, packages/resource-deployment/runtime-config/runtime-config.prod.json, packages/resource-deployment/runtime-config/runtime-config.selftest.json, packages/web-api-send-notification-runner/src/tasks/notification-sender-web-api-client.spec.ts, packages/web-api-send-notification-runner/src/tasks/notification-sender-web-api-client.ts
- If we don’t set time out, time out might take too much time especially if we keep retrying, so the task itself times out before the post request does, so it exists without updating the notification state.
=> fix: Set timeout when sending the notification request

packages/web-workers/host.json, packages/web-workers/scan-batch-requests-feed-func/function.json
Enable Cosmos feed to start from beginning of batch collection if restarted.
Increase function runtime limit.
=> Enable Cosmos feed to start from beginning

packages/cli/package.json, packages/cli/src/report/report-disk-writer.spec.ts, packages/cli/src/report/report-disk-writer.ts, packages/cli/src/report/summary-report/__snapshots__/html-summary-report-generator.spec.ts.snap, packages/cli/src/report/summary-report/console-summary-report-generator.spec.ts, packages/cli/src/report/summary-report/html-summary-report-generator.spec.ts, packages/cli/src/report/summary-report/html-summary-report-generator.ts, packages/cli/src/report/summary-report/json-summary-report-generator.spec.ts, packages/cli/src/report/summary-report/summary-report-data.ts, packages/cli/src/runner/file-command-runner.spec.ts, packages/cli/src/runner/file-command-runner.ts, yarn.lock
This will generate a basic summary html file. Look at the jest snapshot file to get  idea on how it will look.
Refactored file-command-runner & added support to capture unscannable urls
(unscannable urls list is not surfaced anywhere in the report yet)
Refactored unit tests for file-command-runner for better coverage
=> chore: adding support to generate summary html

packages/cli/src/scanner/page.spec.ts, packages/cli/src/scanner/page.ts, packages/scanner/src/page.spec.ts, packages/scanner/src/page.ts
- For a case like internal server error, the response code will be 500 and the page content will not be html.
- If we check the content first as we used to do, the error will be 'InvalidContentType' which is wrong.
- It should be 'HttpErrorCode', so if we check the reponse code first, we should be able to get the right error code.
=> fix: Check response code before checking page content type

packages/resource-deployment/templates/on-demand-url-scan-schedule.template.json
Set job manager max wall clock in sync with task run time
=> Set job manager max wall clock in sync with task run time

packages/resource-deployment/templates/function-web-api-app-template.json, packages/resource-deployment/templates/function-web-workers-app-template.json
Enable https only on azure functions
=> chore: enable https only on azure functions

packages/resource-deployment/scripts/deploy-rest-api.sh, packages/resource-deployment/scripts/function-app-create.sh
This will fix deployment failures in selftest due to accessing the APIM instance's IP address before it has been deployed
=> fix: move ip restriction step to API deployment

packages/crawler/src/apify-settings.spec.ts, packages/crawler/src/apify-settings.ts, packages/crawler/src/crawler-engine.spec.ts, packages/crawler/src/crawler-engine.ts
Apify doesn't provide a way to set the output directory besides setting the APIFY_LOCAL_STORAGE_DIR environment variable. This PR will allow us to pass in an outputDirectory parameter and set the env variable as part of running the crawler.
This PR also sets APIFY_HEADLESS to true by default.
=> feat(port-crawler-to-cli): set apify output directory

packages/crawler/src/apify-resources/resource-creator.spec.ts, packages/crawler/src/apify-resources/resource-creator.ts, packages/crawler/src/apify-settings.spec.ts, packages/crawler/src/apify-settings.ts, packages/crawler/src/crawler/crawler-configuration.spec.ts, packages/crawler/src/crawler/crawler-configuration.ts, packages/crawler/src/crawler/crawler-engine.spec.ts, packages/crawler/src/crawler/crawler-engine.ts, packages/crawler/src/index.ts, packages/crawler/src/types/run-options.ts
Add the --restart flag and empty the request queue by deleting that directory if it is provided. Otherwise, the crawl will continue from the last request in the queue.
=> feat(port-crawler-to-cli): Add option to restart crawl

packages/crawler/src/apify/apify-resource-creator.spec.ts, packages/crawler/src/apify/apify-resource-creator.ts, packages/crawler/src/crawler/crawler-engine.spec.ts, packages/crawler/src/crawler/crawler-engine.ts, packages/crawler/src/index.ts, packages/crawler/src/page-processors/page-processor-factory.spec.ts, packages/crawler/src/page-processors/page-processor-factory.ts, packages/crawler/src/types/resource-creator.ts, packages/crawler/src/types/run-options.ts
This PR add list of URLs to crawl/scan in addition to URLs discovered from crawling base URL by passing a link to an input file path or an array of urls in the arguments or both.
Also Add the option to pass more discovery patterns to be crawled in addition to the base url.
=> feat(port-crawler-to-cli): Add List of URLs to crawl 

packages/cli/src/report/report-formats.ts, packages/cli/src/report/summary-report/__snapshots__/html-summary-report-generator.spec.ts.snap, packages/cli/src/report/summary-report/console-summary-report-generator.spec.ts, packages/cli/src/report/summary-report/html-summary-report-generator.spec.ts, packages/cli/src/report/summary-report/html-summary-report-generator.ts, packages/cli/src/report/summary-report/json-summary-report-generator.spec.ts, packages/cli/src/report/summary-report/summary-report-data.ts, packages/cli/src/runner/file-command-runner.spec.ts, packages/cli/src/runner/file-command-runner.ts
This PR creates a log file for each failed scan url with the error details and add it in the html summary report.
=> feat(port-crawler-to-cli): Create an error log for each unscannable url while running file scan without crawling

packages/cli/src/module-name-mapper.ts, packages/crawler/src/global-overrides.ts, packages/web-api-scan-runner/src/module-name-mapper.ts
Added OS lib path dependent resolution to redirect package mapping respectively
=> Added OS lib path dependent resolution

packages/cli/src/cli-entry-point.spec.ts, packages/cli/src/cli-entry-point.ts, packages/cli/src/cli.ts, packages/cli/src/report/report-disk-writer.spec.ts, packages/cli/src/report/report-disk-writer.ts, packages/cli/src/report/report-formats.ts, packages/cli/src/report/report-name-generator-builder.test.ts, packages/cli/src/report/report-name-generator-builder.ts, packages/cli/src/report/report-name-generator.test.ts, packages/cli/src/report/report-name-generator.ts, packages/cli/src/runner/crawler-command-runner.spec.ts, packages/cli/src/runner/crawler-command-runner.ts
- Create new Crawler command runner.
- Create Report name builder.
- Create report name generator.
- Create an error log for the whole CLI run if it fails.
- Fix create directory to be recursive.
=> feat (cli-summary-report): Create error log for the whole CLI run

packages/cli/package.json, packages/crawler/package.json, yarn.lock
This reverts commit 8231ba1578f70cf67121e8ee62eaed5a9f0ed7a7.
Revert this update before we release the cli package
=> chore: Revert "chore(deps): bump apify-shared from 0.2.17 to 0.4.5 (#1030)"

.vscode/launch.json, packages/logger/src/index.ts, packages/logger/src/logger-event-measurements.ts, packages/logger/src/logger-event.ts, packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts
This change is to separate browser originates scan issues (page not found, timeout, etc,..) from service unhandled errors. This is prerequisite for service availability based on all scan requests in addition to synthetic availability metrics
=> Log browser scan error event

package.json, packages/cli/package.json, packages/crawler/package.json, packages/scanner-global-library/package.json, packages/web-api-scan-runner/package.json, yarn.lock
Updates usages of axe-core 4.0.1 to 4.0.2
Out of scope/separate PR:
- consume new report package when it's ready with `link-name` updates
- re-enable `link-name` rule
=> feat(axe-core-4.0.2): update to axe-core 4.0.2

packages/resource-deployment/templates/vnet.template.json
Create a network security group for our vnet with rules needed to allow azure batch to access the vm nodes. This fixes an alert from the Armory tool for ARM template scanning, which is now required in our SDL pipeline.
=> fix: add network security group to vnet template

package.json, packages/cli/package.json, packages/crawler/package.json, yarn.lock
In the most recent version of apify-shared (0.5.0), they have removed a dependency on a package that is creating an alert for us in Component Governance.
=> chore: update apify-shared to v0.5.0

packages/api-contracts/ai-scan-api.yaml, packages/service-library/src/web-api/web-api-error-codes.ts, packages/web-api/src/controllers/scan-request-controller.spec.ts, packages/web-api/src/controllers/scan-request-controller.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.spec.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.ts
- Updated `ScanRunRequest` schema in ai-scan-api.yaml to include properties from `ScanRunBatchRequest`
- Saved 'site' and 'reportGroups' properties from request in scan-request-controller and scan-batch-request-feed-controller
- Added check to validate that both 'site' and 'reportGroups' properties are present if either one is present
=> feat: save site and reportGroups data from scan run request

packages/web-api-scan-runner/src/report-generator/axe-result-to-consolidated-html-converter.spec.ts, packages/web-api-scan-runner/src/report-generator/axe-result-to-consolidated-html-converter.ts, packages/web-api-scan-runner/src/report-generator/register-report-generator-to-container.spec.ts, packages/web-api-scan-runner/src/report-generator/register-report-generator-to-container.ts, packages/web-api/src/converters/scan-response-converter.spec.ts, packages/web-api/src/converters/scan-response-converter.ts
- Created axe-result-to-consolidated-html-converter that currently converts axe results to html report (will be updated in another feature to convert to an actual consolidated report)
- Registered the axe-result-to-consolidated-html-converter
- Updated scan-response-converter to include the consolidated-html report only if there is a consolidatedId
=> feat: return mock consolidated html report link

packages/azure-services/src/azure-cosmos/cosmos-key-provider.spec.ts, packages/azure-services/src/azure-cosmos/cosmos-key-provider.ts, packages/azure-services/src/credentials/arm-service-token-provider.spec.ts, packages/azure-services/src/credentials/arm-service-token-provider.ts, packages/azure-services/src/key-vault/secret-names.ts, packages/azure-services/src/register-azure-services-to-container.spec.ts, packages/azure-services/src/register-azure-services-to-container.ts, packages/resource-deployment/scripts/create-env-file-for-debug.sh, packages/resource-deployment/scripts/enable-system-identity-for-batch-vmss.sh, packages/resource-deployment/scripts/function-app-create.sh, packages/resource-deployment/scripts/push-secrets-to-key-vault.sh
Instead of storing the cosmosdb access key in keyvault, use [MSI and the azure REST API](https://docs.microsoft.com/en-us/azure/cosmos-db/managed-identity-based-authentication) to retrieve the key at runtime.
- Add cosmosDB contributor roles for function apps and batch pools
- Add classes to retrieve the cosmosdb access key
- Remove the cosmosdb key from keyvault and store the base URL for the listKeys REST call instead
- Refactor azure services setup code to fetch the key with an MSI token instead of pulling the key from keyvault
=> Use MSI to access CosmosDB

packages/azure-services/package.json, packages/azure-services/src/credentials/credentials-provider.spec.ts, packages/azure-services/src/credentials/credentials-provider.ts, packages/azure-services/src/ioc-types.ts, packages/azure-services/src/key-vault/secret-provider.spec.ts, packages/azure-services/src/key-vault/secret-provider.ts, packages/azure-services/src/register-azure-services-to-container.spec.ts, packages/azure-services/src/register-azure-services-to-container.ts, yarn.lock
Replace the deprecated @azure/keyvault package with @azure/keyvault-secrets. This will partially unblock #1122.
=> chore(deps): Use @azure/keyvault-secrets

packages/cli/src/runner/file-command-runner.spec.ts, packages/cli/src/runner/file-command-runner.ts
- Use AxeResultReducer to combine results after scans in a CLI file scan
=> feat: integrate axe result reducer into cli file scan

packages/azure-services/package.json, packages/azure-services/src/azure-queue/queue.spec.ts, packages/azure-services/src/azure-queue/queue.ts, packages/azure-services/src/ioc-types.ts, packages/azure-services/src/register-azure-services-to-container.spec.ts, packages/azure-services/src/register-azure-services-to-container.ts, packages/resource-deployment/scripts/enable-system-identity-for-batch-vmss.sh, yarn.lock
This started as a package update in #1125, and became a larger overhaul of our storage queue client wrapper
- Update @azure/storage-queue from 10.3.0 to 12.2.0
- Refactor Queue class to use the new SDK interface
- Use MSI instead of storage key and shared key credential to authenticate to storage queue
=> Update storage queue SDK and use MSI to access queue

packages/axe-result-converter/src/combined-report-data-converter.spec.ts, packages/axe-result-converter/src/combined-report-data-converter.ts
currently, the combined report failures are sorted by the number of cards, not by the number of failure instances (sum of #urls for each card). Since we display the number of failure instances, in the report, the failed rules appear to be unsorted or sorted badly:
This PR will make sure we sort by number of failure instances instead.
=> fix: combined report failure sorting

packages/scanner-global-library/src/page-handler.spec.ts, packages/scanner-global-library/src/page-handler.ts, packages/web-api-send-notification-runner/package.json
Fixed puppeteer obsolete API `waitFor` warning message. See https://github.com/puppeteer/puppeteer/issues/6214
=> Fixed puppeteer obsolete API `waitFor` warning message

packages/resource-deployment/templates/model-accessibility-insight-service-scan-api-api.template.json
Increase max calls per minute for API calls to be 3000 request per minute instead of 1000.
=> Fix: Increase max calls per minute for API calls

packages/logger/package.json, packages/logger/src/logger-types.ts, packages/logger/src/register-logger-to-container.spec.ts, packages/logger/src/register-logger-to-container.ts, packages/web-api-scan-runner/src/scan-metadata-config.ts, packages/web-api-send-notification-runner/src/notification-sender-config.ts, packages/web-workers/webpack.config.js
Remove unnecessary yargs dependency from logger package to exclude from webpack when building Azure function bundle
=> Remove unnecessary yargs dependency from logger package

packages/azure-services/src/azure-blob/blob-storage-client.spec.ts, packages/azure-services/src/azure-blob/blob-storage-client.ts, packages/azure-services/src/index.ts, packages/common/src/hash-set.spec.ts, packages/common/src/hash-set.ts, packages/common/src/index.ts, packages/resource-deployment/templates/blob-storage.template.json, packages/service-library/package.json, packages/service-library/src/data-providers/combined-scan-results-provider.spec.ts, packages/service-library/src/data-providers/combined-scan-results-provider.ts, packages/service-library/src/data-providers/data-providers-common.spec.ts, packages/service-library/src/data-providers/data-providers-common.ts, packages/service-library/src/data-providers/page-scan-run-report-provider.spec.ts, packages/service-library/src/data-providers/page-scan-run-report-provider.ts, packages/service-library/src/index.ts, packages/storage-documents/package.json, packages/storage-documents/src/combined-scan-results.ts, packages/storage-documents/src/index.ts, packages/storage-documents/src/website-scan-result.ts, packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts
Create a CombinedScanResultsProvider, add a new storage blob container, and save an empty scan results object for each website scan
Future work:
- Merge axe results into combined results blob
- Handle concurrent blob accesses
=> Save empty combined results to storage blob

packages/cli/src/report/report-disk-writer.spec.ts
When running `yarn precheckin` for #1168, I noticed that there was a test case failing locally that didn't seem related to the change. It looks like there was a pre-existing case that only worked on `/`-path-separator-based filesystems; this corrects the test to match the production filepath normalization behavior.
=> chore: fix windows compat with report-disk-writer.spec.ts

packages/cli/package.json, packages/crawler/package.json, packages/functional-tests/package.json, packages/health-client/package.json, packages/service-library/package.json, packages/web-api-scan-job-manager/package.json, packages/web-api-scan-request-sender/package.json, packages/web-api-scan-runner/package.json, packages/web-api-send-notification-job-manager/package.json, packages/web-api-send-notification-runner/package.json, yarn.lock
The yargs upgrade introduced a bug where capitalization is stripped on env variables, which caused args with capitalization in their names to not be found. This caused the notification sender tasks to fail, since their required parameters were not found.
=> Revert "chore(deps): bump yargs from 15.4.1 to 16.1.1 (#1147)"

packages/azure-services/src/azure-blob/blob-storage-client.spec.ts, packages/azure-services/src/azure-blob/blob-storage-client.ts, packages/common/package.json, packages/common/src/body-parser.ts, packages/common/src/index.ts, packages/service-library/src/data-providers/combined-scan-results-provider.spec.ts, packages/service-library/src/data-providers/combined-scan-results-provider.ts, packages/web-api/package.json, packages/web-api/src/controllers/scan-report-controller.spec.ts, packages/web-api/src/controllers/scan-report-controller.ts
- Add etags to response object for all CombinedScanResultProvider operations
- Fix a bug reading the combined results blob
=> Improvements and fixes to CombinedScanResultProvider

packages/cli/package.json, packages/crawler/package.json, packages/functional-tests/package.json, packages/health-client/package.json, packages/service-library/package.json, packages/web-api-scan-job-manager/package.json, packages/web-api-scan-request-sender/package.json, packages/web-api-scan-runner/package.json, packages/web-api-scan-runner/src/scan-metadata-config.spec.ts, packages/web-api-send-notification-job-manager/package.json, packages/web-api-send-notification-runner/package.json, packages/web-api-send-notification-runner/src/notification-sender-config.spec.ts, packages/web-api-send-notification-runner/src/notification-sender-config.ts, yarn.lock
- Undo the revert of #1147 (in #1176) so that we use the more recent version of yargs (16.1.1)
- Add workaround for the bug that appeared after the yargs commit (#1832) (workaround may be removed if a future release of yargs fixes the issue)
- Add unit tests to verify yargs behavior for batch task arguments and prevent similar issues in the future
=> chore: upgrade to yargs 16.1.1

packages/resource-deployment/scripts/delete-resource-group.sh, packages/resource-deployment/scripts/setup-key-vault.sh
At the end of this year, soft-delete will be enabled for all existing keyvaults and the option to opt out of soft delete will be deprecated ([more info on soft delete here](https://docs.microsoft.com/en-us/azure/key-vault/general/soft-delete-change)). Soft delete is currently disabled for our dev testing and selftest pipelines. Since our dev and selftest resources are more frequently deleted and recreated, enabling soft-delete will likely cause name collisions which would break our deployment pipelines. This PR will prepare those pipelines to handle name collisions for soft-deleted keyvaults.
- When we attempt to deploy a keyvault, if a deleted keyvault is found with the same name, restore the deleted one instead of attempting to redeploy (the deleted keyvault can be manually purged if …
=> chore: prepare installation scripts for mandatory keyvault soft-delete

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/functional-tests/src/test-group-data.ts, packages/functional-tests/src/test-groups/functional-test-group.ts, packages/functional-tests/src/test-groups/scan-reports-test-group.ts, packages/web-api-client/src/a11y-service-client.spec.ts, packages/web-api-client/src/a11y-service-client.ts, packages/web-api/src/controllers/health-check-controller.spec.ts, packages/web-workers/src/contracts/activity-actions.ts, packages/web-workers/src/controllers/activity-request-data.ts, packages/web-workers/src/controllers/health-monitor-client-controller.spec.ts, packages/web-workers/src/controllers/health-monitor-client-controller.ts, packages/web-workers/src/controllers/health-monitor-orchestration-controller.spec.ts, packages/web-workers/src/controllers/health-monitor-orchestration-controller.ts, packages/web-workers/src/orchestration-steps.spec.ts, packages/web-workers/src/orchestration-steps.ts
This adds an additional test to validate the consolidated report api. Specifically, we're checking to see that we're returned 3 reports as a result.
=> feat(ai-service-dedupe-e2e): added e2e tests for consolidated scan report

packages/resource-deployment/scripts/delete-resource-group.sh
This will prevent status conflict errors when deleting resource groups (i.e. APIM is in deleting state when we try to delete the resource group)
=> fix: wait for APIM instance to finish deleting before deleting resource group

packages/resource-deployment/scripts/delete-resource-group.sh
Fix typos in script when waiting for APIM instance to delete
=> fix: typos in delete-resource-group script

packages/resource-deployment/scripts/delete-resource-group.sh, packages/resource-deployment/scripts/get-resource-names.sh
Fixes a case when running delete-resource-group where the resource group exists, but is empty, so the script errors when trying to get resource names
=> fix: handle empty resource group

packages/cli/package.json
- Minor version bump because it uses updated packages axe-core 4.1.1 and accessibility-insights-report 4.0.0
=> chore: bump ai-scan package minor version to 0.6.0

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/e2e-web-apis/scan-notification-client-func-fail/function.json, packages/e2e-web-apis/scan-notification-client-func-fail/index.ts, packages/e2e-web-apis/webpack.config.js, packages/functional-tests/src/test-groups/scan-completion-notification-test-group.ts, packages/resource-deployment/scripts/deploy-rest-api.sh, packages/resource-deployment/templates/model-accessibility-insight-service-scan-api-api.template.json, packages/web-api-client/src/a11y-service-client.spec.ts, packages/web-api-client/src/a11y-service-client.ts, packages/web-api/src/controllers/health-check-controller.spec.ts, packages/web-workers/src/controllers/health-monitor-client-controller.spec.ts, packages/web-workers/src/controllers/health-monitor-client-controller.ts, packages/web-workers/src/controllers/health-monitor-orchestration-controller.spec.ts, packages/web-workers/src/controllers/health-monitor-orchestration-controller.ts, packages/web-workers/src/orchestration-steps.spec.ts, packages/web-workers/src/orchestration-steps.ts
Creates another function in e2e-web-apis to send a non-200 response for scan notification fail case. This api/url is passed for the consolidated scan.
=> feat(ai-service-dedupe-e2e): added fail scan notification e2e test

packages/api-contracts/ai-scan-api.yaml
In #1212 `deepScanResult` was incorrectly added to the response for the initial scan-request endpoint; this was meant to be on `ScanRunResultResponse` alongside the other `scanResult` info. This PR corrects the issue.
=> feat(deepscan-contract): fix incorrect location of deepScanResult in API contract

packages/cli/src/runner/crawler-command-runner.spec.ts, packages/cli/src/runner/crawler-command-runner.ts, packages/cli/src/setup-cli-container.ts, packages/crawler/src/crawler.spec.ts, packages/crawler/src/crawler.ts, packages/crawler/src/crawler/crawler-engine.ts, packages/crawler/src/crawler/puppeteer-crawler-engine.spec.ts, packages/crawler/src/crawler/puppeteer-crawler-engine.ts, packages/crawler/src/crawler/simple-crawler-engine.spec.ts, packages/crawler/src/crawler/simple-crawler-engine.ts, packages/crawler/src/index.ts, packages/crawler/src/main.ts, packages/crawler/src/setup-crawler-container.spec.ts, packages/crawler/src/setup-crawler-container.ts, packages/crawler/src/types/ioc-types.ts
- Create a new SimpleCrawlerEngine class to be used to crawl pages in the service
- Rename existing CrawlerEngine to PuppeteerCrawlerEngine and create a generic CrawlerEngine interface
- Make the Crawler class accept and run any arbitrary CrawlerEngine
=> feat(cloud-crawler): SimpleCrawlerEngine

packages/api-contracts/ai-scan-api.yaml, packages/service-library/src/web-api/api-contracts/scan-run-request.ts, packages/storage-documents/src/on-demand-page-scan-batch-request.ts, packages/storage-documents/src/website-scan-result.ts, packages/web-api/src/controllers/scan-request-controller.spec.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.spec.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.ts
We need to add discovery patterns property to AI REST API for the deep scan since we might have more complicated scenario when sending website crawl request.
`// RegEx patterns used by web crawler to specify which URLs should website include`
`discoveryPatterns?: string[]; `
=> feat(deepscan-contract): Add discoveryPatterns to scan request API

packages/cli/src/scanner/ai-scanner.spec.ts, packages/cli/src/scanner/ai-scanner.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts, packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts, packages/web-api-scan-runner/src/scanner/scanner.spec.ts, packages/web-api-scan-runner/src/scanner/scanner.ts
- Separate page scanning from page navigation
- Expose the underlying puppeteer page so we can access it when crawling
- Move Page from Scanner into Runner, so it can be passed to the crawler when we add that step
=> feat(cloud-crawler): expose underlying puppeteer page to Runner

packages/web-api-scan-runner/src/index.ts, packages/web-api-scan-runner/src/setup-web-api-scan-runner-container.spec.ts, packages/web-api-scan-runner/src/setup-web-api-scan-runner-container.ts
Rename the container setup function in web-api-scan-runner to "setupWebApiScanRunnerContainer"
=> fix: container setup function name

package.json, packages/azure-services/package.json, packages/azure-services/src/azure-queue/queue.spec.ts, packages/azure-services/src/azure-queue/queue.ts, packages/resource-deployment/scripts/create-sp-for-debug.sh, packages/resource-deployment/scripts/delete-pools-if-needed.sh, packages/resource-deployment/templates/function-e2e-web-apis-app-template.json, packages/resource-deployment/templates/function-web-api-app-template.json, packages/web-api-scan-job-manager/src/worker/worker.ts, packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts, yarn.lock
Fixed Azure storage queue wrapper to set correct queue message visibility timeout to prevent duplicate scan of the same scan request
Update Azure Function API version to resolve server farm duplicate deployment error
Update dev .env setup script to grant Azure queue access
Increase VMs recycle frequency
=> Azure storage queue message visibility timeout fix

packages/web-api-scan-runner/src/runner/combined-report-generator.spec.ts, packages/web-api-scan-runner/src/runner/combined-report-generator.ts, packages/web-api-scan-runner/src/runner/report-saver.spec.ts, packages/web-api-scan-runner/src/runner/report-saver.ts
This is creating a component responsible for generating combined scan report (currently done in runner).
This does not update the runner as this will not be consumed by the runner (but another component instead).
=> refactor(cloud-crawler): create combined report generator

packages/crawler/src/crawler.ts, packages/crawler/src/index.ts, packages/crawler/src/setup-crawler-container.ts, packages/crawler/src/types/ioc-types.ts, packages/web-api-scan-runner/package.json, packages/web-api-scan-runner/src/crawl-runner/crawl-runner.spec.ts, packages/web-api-scan-runner/src/crawl-runner/crawl-runner.ts, packages/web-api-scan-runner/src/setup-web-api-scan-runner-container.ts, packages/web-api-scan-runner/webpack.config.js
At present, this class manages logging and error handling for crawling during a run. In future, it can also manage adding known urls to scan results.
Note: In a few places, the use of `inversify.Container` was changed to `inversify.interfaces.Container` because functions which create the crawler only have the interface type available.
=> feat(cloud-crawler): Create CrawlRunner class to manage crawling during a run

packages/web-api-scan-runner/src/runner/axe-result-merger.spec.ts, packages/web-api-scan-runner/src/runner/axe-result-merger.ts, packages/web-api-scan-runner/src/runner/combined-results-blob-getter.spec.ts, packages/web-api-scan-runner/src/runner/combined-results-blob-getter.ts
I modified the logic slightly as there was a bit of redundancy in the checks.
=> refactor(cloud-crawler): refactor out axe result merger of runner

packages/web-api-scan-runner/package.json, packages/web-api-scan-runner/webpack.config.js
Add leveldown as external in batch workers to fix "No native build was found" errors
=> fix: add leveldown as external

packages/crawler/src/apify/apify-resource-creator.spec.ts, packages/crawler/src/apify/apify-resource-creator.ts, packages/crawler/src/crawler/simple-crawler-engine.spec.ts, packages/crawler/src/crawler/simple-crawler-engine.ts, packages/crawler/src/index.ts, packages/crawler/src/setup-crawler-container.ts, packages/crawler/src/types/crawler-run-options.ts, packages/crawler/src/types/resource-creator.ts, packages/web-api-scan-runner/src/crawl-runner/crawl-runner.spec.ts, packages/web-api-scan-runner/src/crawl-runner/crawl-runner.ts
- Add baseCrawlPage to CrawlerRunOptions, instead of having a separate SimpleCrawlerRunOptions type
- Move initial enqueueLinks call from SimpleCrawlerEngine to ApifyResourceProvider. ApifyResourceProvider now enqueues the baseUrl, enqueues any urls in urlList if it exists, and enqueues any links discovered on the puppeteer page if it exists
=> refactor(cloud-crawler): Crawler baseCrawlPage option

packages/azure-services/src/azure-batch/batch-config.spec.ts, packages/azure-services/src/azure-batch/batch-config.ts, packages/azure-services/src/azure-batch/batch.spec.ts, packages/service-library/src/batch/batch-task-creator.spec.ts, packages/web-api-scan-job-manager/src/worker/worker.spec.ts, packages/web-api-scan-runner/docker-image-config/Dockerfile, packages/web-api-scan-runner/src/crawl-runner/crawl-runner.spec.ts, packages/web-api-scan-runner/src/crawl-runner/crawl-runner.ts, packages/web-api-send-notification-job-manager/src/task/send-notification-task-creator.spec.ts
- make sure ps is installed on the docker image for scan runner (required for Apify)
- Set the local storage directory for the crawl to the working directory for the task (fixes permissions error)
=> feat(cloud-crawler): fix cloud crawler settings

packages/logger/src/index.ts, packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts, packages/web-api-scan-runner/src/scan-runner-telemetry-manager.spec.ts, packages/web-api-scan-runner/src/scan-runner-telemetry-manager.ts
Extract the trackEvent calls in runner.ts to another class, ScanRunnerTelemetryManager. The new class is also responsible for managing the "scan started" and "scan completed" timestamps. This simplifies the Runner unit tests, since it a) removes the need to mock Date.now() calls in runner tests, and b) reduces the number of logger calls to be verified.
=> refactor: ScanRunnerTelemetryManager

packages/cli/src/scanner/ai-scanner.spec.ts, packages/cli/src/scanner/ai-scanner.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts, packages/scanner-global-library/src/puppeteer-options.ts, packages/scanner-global-library/src/web-driver.spec.ts, packages/scanner-global-library/src/web-driver.ts, packages/web-api-scan-runner/src/runner/ws-endpoint-fetcher.ts
This PR adds `puppeteer.connect` functionality to inner `webdriver` and `page` classes.
`puppeteer-options` is moved into its own file so that the `host-browser-service` can reuse it eventually.
The coniditional `launch/connect` decision is in `page` for now.
Enable `web-api-scan-runner` to run scans via `puppeteer.connect` in future PRs
This PR only adds new methods & updates existing usages - production behavior should not be changed in this PR. All scans still use `launch`, not `connect` yet.
=> feat(host-browser-service): update webdriver to accept ws-endpoint for puppeteer connection

packages/web-api-scan-runner/src/scan-metadata-config.ts, packages/web-api-send-notification-runner/src/notification-sender-config.ts, yarn.lock
Update yargs-parser from 20.2.4 to 20.2.6 and remove temporary workaround for camel case arguments.
yargs-parser 20.2.6 contains a fix for an [issue with camel case arguments](https://github.com/yargs/yargs-parser/issues/345). Since the bug has been fixed, we no longer need the workaround in our code.
=> chore: yargs-parser v20.2.6

packages/web-api-scan-runner/docker-image-config/Dockerfile
Force our dockerfile to use npm-force-resolutions v0.0.3 instead of pulling the most recent version from npm
Version 0.0.4 of npm-force-resolutions contains a bug when running it with npx.  Because we currently don't specify the version of npm-force-resolutions, our docker build started failing shortly after it was published.
=> fix: pin npm-force-resolutions to v0.0.3

packages/azure-services/src/azure-queue/queue.ts
Sometimes when we set the visibility time out to 5 minutes, the task fails and then when we retry, it will be more than 5 mins, so at the end of the second task when we try to delete the message, it will be already expired and deleted so the task will crash and stop all other active runner tasks which cause some scans to be in running status forever.
=> fix: Handle error when message already expired

yarn.lock
This PR updates the transitive dependency url-parse:
1. Removed url-parse from yarn.lock
2. Ran `yarn`
3. Verified that url-parse in yarn.lock points to its latest version, 1.5.1
Addresses [CVE-2021-27515](https://nvd.nist.gov/vuln/detail/CVE-2021-27515): url-parse before 1.5.0 mishandles certain uses of backslash such as http:\/ and interprets the URI as a relative path.
Did not update other dependencies of root dependency `@azure/batch`
=> chore(deps): upgrade url-parse for security fix

packages/resource-deployment/scripts/setup-key-vault.sh
Enable keyvault encryption in deployment script
We added keyvault encryption as part of the switch to Windows VMs. Currently, for existing resource groups, encryption must be enabled manually for deployment to succeed.
=> fix: keyvault encryption

.vscode/workspace.code-workspace, azure-pipeline/build-artifacts-and-run-tests-job.yaml, packages/common/src/build-utilities/monorepo-packages.spec.ts, packages/host-browser-service/jest.config.js, packages/host-browser-service/package.json, packages/host-browser-service/prettier.config.js, packages/host-browser-service/src/browser-server.spec.ts, packages/host-browser-service/src/browser-server.ts, packages/host-browser-service/src/host-browser-service-entry-point.spec.ts, packages/host-browser-service/src/host-browser-service-entry-point.ts, packages/host-browser-service/src/index.ts, packages/host-browser-service/src/promisable-mock.ts, packages/host-browser-service/src/setup-host-browser-service-container.ts, packages/host-browser-service/src/setup-host-browser-service.container.spec.ts, packages/host-browser-service/tsconfig.json, packages/host-browser-service/webpack.config.js
This PR includes initial placeholder/config files to set up the host-browser-server folder.
This PR has placeholder functionality to get some config files out of the way. The project is not used and no production behavior should change.
This package will eventually produce a file that accepts puppeteer.connect() requests from the web-api-scan-runner (in docker) and routes them to new browser connections. The server will run on the host outside the docker container. In this PR, the 'server' does nothing except log that it was run.
=> feat(host-browser-service): add initial skeleton for host-browser-server package

packages/resource-deployment/scripts/restart-vm-pools.sh, packages/resource-deployment/scripts/run-command-when-batch-nodes-are-idle.sh, packages/resource-deployment/scripts/setup-key-vault.sh
- Increase timeouts for batch nodes to become stable
- Suppress the output of `az keyvault update` in deployment scripts
- The new Windows VMs start up slower than the old Linux ones, so sometimes a restart times out and causes the deployment pipeline to fail when nothing has actually gone wrong and the restart completes successfully a few minutes later.
- The output of `az keyvault update` is very long and not useful for our purposes, so this will remove the chore of having to scroll past it in deployment logs.
=> chore: edit deployment scripts to better fit the new Windows VMs

packages/resource-deployment/scripts/run-command-when-batch-nodes-are-idle.sh
Increase timeout for nodes to become idle after disabling job schedules from 10 to 30 minutes, and log node states after the wait either succeeds or fails.
Recently, many of our builds have been timing out while waiting for nodes to become idle, even when nothing is wrong with the nodes themselves. The increased wait should prevent this from happening so often, and the log statements will give us more information to debug if it does keep happening.
The source of this problem is that scan tasks take longer on the new Windows VMs. This means that, during the space of a running task, more new tasks get queued, so some jobs have a lot more tasks than we saw on the old Linux VMs. This means that jobs take longer overall, and continue for longer than expected after the job schedules are …
=> chore: increase timeout for nodes to become idle

packages/service-library/src/batch/batch-task-creator.spec.ts, packages/service-library/src/batch/batch-task-creator.ts
The job manager task timesout sometimes before hitting the code that check for that, and that causes some scans to be pending forever since some of the tasks will be terminated before even starting or while running.
So in this PR we will give some margin to the job manager task and pending runner tasks to end before the max clock wall time expires.
=> Chore: Reduce Job Manager Task Restart Time

packages/scanner-global-library/src/puppeteer-options.ts
Increase the maximum threshold of memory available to Chromium to 8GB.
For some URLs (ex. https://dotnet.microsoft.com/learn/dotnet/in-browser-tutorial/2), we see a sudden spike in memory use when scanning, which causes chromium to run out of memory and crash when running on the VMs. After this change, we can successfully scan those URLs.
The current default memory limit for Chromium is dependent on the specific machine and environment. Our VMs have enough memory available to complete these scans, but it the current defaults prevent enough memory from being allocated to chromium.
=> fix: increase max memory allocated to chromium

packages/service-library/src/batch/batch-task-creator.spec.ts, packages/service-library/src/batch/batch-task-creator.ts
In the deployment, we still fail at restarting VMs task, the reason is sometimes job manager task might take more than half an hour because many jobs were piled up which leads to timeout on waiting for node to be idle, to avoid that we decided to reduce the job manager task restart time.
=> Chore: Reduce Job Manager Task Restart Time 

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/web-api/src/controllers/health-check-controller.spec.ts, packages/web-workers/src/controllers/health-monitor-orchestration-controller.spec.ts, packages/web-workers/src/controllers/health-monitor-orchestration-controller.ts, packages/web-workers/src/orchestration-steps.spec.ts
Instead of always reusing the same id for the consolidated scan e2e test, append the release id to the consolidated id so we use a different id on each release.
Currently, all e2e tests reuse the same static consolidated id, and therefore the same WebsiteScanResult document. This can be a problem if the structure of WebsiteScanResult changes in a way that is not backwards-compatible with existing documents, as we saw in a recent canary release.
This PR will make sure a new WebsiteScanResult document is created for e2e tests on each release, so that changes to the document structure will not cause e2e tests to fail.
=> refactor: refresh e2e consolidated scan id after each release

packages/resource-deployment/scripts/run-command-when-batch-nodes-are-idle.sh
This is a follow-up from #1316 - we are noticing cases where the deployment fails because the node took too long to get to the start task when it is created in custom install. Therefore the 'restart VM' step times out. This increases the idle timeout further as a mitigation to allow deployments to pass. Usually the deployment fails because of the timeout but the node does start as expected, just later. It's unclear why the nodes are taking this long in 'starting'.
=> chore: increase idle timeout in deployment

packages/resource-deployment/scripts/delete-pools-if-needed.sh, packages/resource-deployment/templates/batch-account-dev.parameters.json, packages/resource-deployment/templates/batch-account-prod.parameters.json, packages/resource-deployment/templates/batch-account.template.json
Use taskSlotsPerNode instead of maxTasksPerNode in our deployment scripts
The updated batch API uses taskSlotsPerNode instead of maxTasksPerNode. In our scripts that check whether the pool config has been updated, maxTasksPerNode is no longer found, so we always detect that the config has changed and the pools need to be deleted. This change will fix that, so that we only recycle pools when needed, which should reduce the usual deployment time.
=> fix: use taskSlotsPerNode instead of maxTasksPerNode

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/resource-deployment/runtime-config/runtime-config.ci.json, packages/resource-deployment/runtime-config/runtime-config.dev.json, packages/resource-deployment/runtime-config/runtime-config.ppe.json, packages/resource-deployment/runtime-config/runtime-config.selftest.json, packages/service-library/src/data-providers/website-scan-result-provider.spec.ts, packages/service-library/src/data-providers/website-scan-result-provider.ts, packages/web-api-scan-runner/src/crawl-runner/discovered-url-processor.ts, packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts, packages/web-api-scan-runner/src/scanner/deep-scanner.spec.ts, packages/web-api-scan-runner/src/scanner/deep-scanner.ts, packages/web-api-scan-runner/src/sender/scan-notification-processor.ts
Reload website document on write db operation
Set lower deep scan limit for dev environment 
Fix deep scan notification event sequence to ensure notification is sent when deep scan completed
=> Reload website document on write db operation

packages/service-library/src/data-providers/website-scan-result-aggregator.spec.ts, packages/service-library/src/data-providers/website-scan-result-aggregator.ts
Fixed deep scan URLs comparison rule to handle same URLs with different case
=> Fixed deep scan URLs comparison rule

packages/resource-deployment/scripts/pool-startup/pool-startup.ps1
This removes `az upgrade` from the Powershell script. The existing MSI installation should handle updates for us ([documentation](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-powershell#powershell-command)).
When upgrading 2.19 to 2.20 locally, several iterations of `az upgrade` with `--yes`, or `--show-errors-only` still showed a user dialog that required input to move forward. This causes the agent to wait for start task until we manually reboot it, at which point the update has been installed already.
Stop nodes from waiting for start task
=> chore: remove az upgrade step in startup script

packages/scanner-global-library/src/web-driver.spec.ts, packages/scanner-global-library/src/web-driver.ts
Close all open pages before closing the browser
Due to a puppeteer issue on Windows 10, browser.close() sometimes causes the browser to crash and attempt to write crash data to protected files, causing a permissions error in the CLI tool and service. Closing all pages before closing the browser is the current workaround for this issue.
=> fix: close all pages before closing browser to prevent crash

package.json, packages/web-api-scan-job-manager/docker-image-config/Dockerfile, packages/web-api-scan-request-sender/docker-image-config/Dockerfile, packages/web-api-scan-runner/docker-image-config/Dockerfile, packages/web-api-send-notification-job-manager/docker-image-config/Dockerfile, packages/web-api-send-notification-runner/docker-image-config/Dockerfile, yarn.lock
Switch Linux container to use official Node Docker image
Upgrade ssri to fix security vulnerabilities
The current Linux Docker image is not supported and has missing security patches
=> Switch Linux container to use official Node Docker image

packages/cli/package.json, packages/cli/src/cli.ts, packages/cli/src/crawler-parameters-builder.ts, packages/cli/src/scan-arguments.ts, packages/crawler/src/crawler/puppeteer-crawler-engine.spec.ts, packages/crawler/src/crawler/puppeteer-crawler-engine.ts
Add CLI command option aliasing to support lower casing
Added hidden debug option to display chromium instance for web page debugging
Avoid user confusion over CLI options camel casing
=> Add CLI command option aliasing to support lower casing

packages/resource-deployment/templates/key-vault-create.template.json
Grant the batch service principal "recover" permissions to the keyvault
This is now [required ](https://docs.microsoft.com/en-us/azure/batch/batch-account-create-portal?WT.mc_id=Portal-Microsoft_Azure_Batch#create-a-key-vault)for user subscription batch accounts to access a keyvault with soft delete enabled. This change will fix current deployment pipeline failures.
=> fix: add secret recover permissions for azure batch

yarn.lock
The package underscore from 1.13.0-0 and before 1.13.0-2, from 1.3.2 and before 1.12.1 are vulnerable to Arbitrary Code Execution via the template function, particularly when a variable property is passed as an argument as it is not sanitized.
Fix vulnerable packages
=> Update underscore package to a non vulnerable version

packages/azure-services/src/azure-batch/pool-load-generator.spec.ts, packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/crawler/src/apify/apify-resource-creator.ts, packages/crawler/src/page-operations/click-element-operation.ts, packages/crawler/src/page-processors/page-processor-base.ts, packages/resource-deployment/runtime-config/runtime-config.ci.json, packages/resource-deployment/runtime-config/runtime-config.dev.json, packages/resource-deployment/runtime-config/runtime-config.ppe.json, packages/resource-deployment/runtime-config/runtime-config.prod.json, packages/resource-deployment/runtime-config/runtime-config.selftest.json, packages/service-library/src/batch/batch-task-creator.spec.ts, packages/service-library/src/batch/batch-task-creator.ts, packages/service-library/src/data-providers/website-scan-result-aggregator.spec.ts, packages/service-library/src/data-providers/website-scan-result-aggregator.ts, packages/service-library/src/data-providers/website-scan-result-provider.spec.ts, packages/service-library/src/data-providers/website-scan-result-provider.ts, packages/storage-documents/src/website-scan-result.ts, packages/web-api-scan-runner/src/crawl-runner/crawl-runner.spec.ts, packages/web-api-scan-runner/src/crawl-runner/crawl-runner.ts, packages/web-api-scan-runner/src/crawl-runner/discovered-url-processor.spec.ts, packages/web-api-scan-runner/src/crawl-runner/discovered-url-processor.ts, packages/web-api-scan-runner/src/crawl-runner/scan-feed-generator.spec.ts, packages/web-api-scan-runner/src/crawl-runner/scan-feed-generator.ts, packages/web-api-scan-runner/src/scanner/deep-scanner.spec.ts, packages/web-api-scan-runner/src/scanner/deep-scanner.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.ts
Enable deep scan known pages overlimit to include all seeded pages.
Fixed scan request message queue timeout
Deep scan request can contain overlimit list of the known pages. The request should process all seeded known pages even count is over deep scan limit.
=> Enable deep scan known pages overlimit

packages/service-library/src/index.ts, packages/web-api-client/src/a11y-service-client.spec.ts, packages/web-api-client/src/a11y-service-client.ts, packages/web-api-client/src/index.ts, packages/web-api-client/src/request-options.ts, packages/web-workers/src/contracts/activity-actions.ts, packages/web-workers/src/controllers/activity-request-data.ts, packages/web-workers/src/controllers/health-monitor-client-controller.spec.ts, packages/web-workers/src/controllers/health-monitor-client-controller.ts, packages/web-workers/src/e2e-test-scenarios/e2e-scan-scenario-definitions.spec.ts, packages/web-workers/src/e2e-test-scenarios/e2e-scan-scenario-definitions.ts, packages/web-workers/src/e2e-test-scenarios/single-scan-scenario.spec.ts, packages/web-workers/src/e2e-test-scenarios/single-scan-scenario.ts, packages/web-workers/src/orchestration-steps.spec.ts, packages/web-workers/src/orchestration-steps.ts
Combine scan request methods in A11yServiceClient, HealthMonitorClientController, and OrchestrationSteps into one scan request code path that takes an "options" object with optional settings (such as notification url, deepScan parameters, etc.)
Currently, we have multiple code paths for different variations on scan requests (in A11yServiceClient, we have postScanUrl, postScanUrlWithNotifyUrl, and postConsolidatedScan). Since we will need to enable deep scan requests on the client in order to run E2E tests, continuing this pattern would create many more code paths that all call the same basic code with different parameters. There will also be some overlap in the options that we will need to allow in different scenarios (for instance, we want to run single scans with and without a …
=> refactor(deep-scan-e2e-tests): Combine scan request methods

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/web-api/src/controllers/health-check-controller.spec.ts, packages/web-workers/src/controllers/health-monitor-orchestration-controller.spec.ts, packages/web-workers/src/e2e-test-scenarios/single-scan-scenario.spec.ts, packages/web-workers/src/e2e-test-scenarios/single-scan-scenario.ts, packages/web-workers/src/orchestration-steps.spec.ts, packages/web-workers/src/orchestration-steps.ts
Add a `waitForDeepScanCompletion` method to `OrchestrationSteps`. This PR also includes some refactoring to reduce duplicated code in the `waitFor` functions in `OrchestrationSteps`, and in the unit tests for this code.
To run E2E tests for deepScans, the orchestrator will need to be able to wait until the full deepScan has been completed.
Possible future work may include separating `waitFor` into a separate object, which would significantly simplify the `OrchestrationSteps` unit tests. Because `waitFor` depends on other code in `OrchestrationSteps,` that change would likely need to be part of a larger refactor of `OrchestrationSteps`, and is deferred for now.
=> feat(deep-scan-e2e-tests): waitForDeepScanCompletion

packages/functional-tests/src/functional-test-group-types.ts, packages/functional-tests/src/test-group-data.ts, packages/functional-tests/src/test-groups/deep-scan-post-completion-test-group.ts, packages/functional-tests/src/test-groups/deep-scan-reports-test-group.ts, packages/web-workers/src/e2e-test-scenarios/e2e-scan-scenario-definitions.ts
This PR adds some functional test groups for the deep-scan scenarios. These are not exercised yet, so this PR has no net behavior on the e2e test suite. We're just getting these files in ahead of time to simplify future reviews / testing.
These functional test groups will be driven from the e2e-scan-scenario orchestrators in future PRs. This enables us to check whether each deep scan request:
- ends up crawling the expected set of URLs
- provides access to a report for each URL (consolidated will be checked using existing consolidated report test group)
- maintains an overall scan status that's consistent with individual URL scan states
We thought about whether `expectedCrawledUrls?: string[];` should be provided other ways. Some alternatives include using snapshots, adding test group …
=> feat(deep-scan-e2e-tests): add functional test groups for deep-scan

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/e2e-test-site/site-content/index.html, packages/e2e-test-site/site-content/linked1/index.html, packages/e2e-test-site/site-content/linked1/inner-page.html, packages/e2e-test-site/site-content/linked2/index.html, packages/e2e-test-site/site-content/unlinked/other.html, packages/functional-tests/package.json, packages/functional-tests/src/test-groups/deep-scan-post-completion-test-group.ts, packages/health-client/src/health-checker.ts, packages/resource-deployment/scripts/deploy-e2e-test-site.sh, packages/web-workers/health-monitor-timer-func/function.json, packages/web-workers/src/e2e-test-group-names.ts, packages/web-workers/src/e2e-test-scenarios/create-scenarios.ts, packages/web-workers/src/e2e-test-scenarios/e2e-scan-scenario-definitions.spec.ts, packages/web-workers/src/e2e-test-scenarios/e2e-scan-scenario-definitions.ts, packages/web-workers/src/e2e-test-scenarios/scan-scenario-driver.spec.ts, packages/web-workers/src/e2e-test-scenarios/scan-scenario-driver.ts, packages/web-workers/src/orchestration-steps.spec.ts, packages/web-workers/src/orchestration-steps.ts, yarn.lock
This PR creates three new deep scan scenarios and runs these scans and E2E tests regularly in the service. The new scenarios include:
- deep scan with no additional options
- deep scan with knownPages
- deep scan with discovery pattern
For each deep scan, we validate that
- The individual scan statuses are consistent with the overall deep scan status
- The list of URLs crawled matches the expected URLs
- A report is created for each individual scan
- A consolidated report is created
Because this change requires significantly more scans to run as part of the E2E test, this PR also changes the health monitor timer function to run every 30 minutes instead of every 10 minutes.
This continues progress on the deep scan E2E test feature.
Future work deferred to other PRs:
- Add scenarioName to …
=> feat(deep-scan-e2e-tests): run deep scan e2e tests

packages/web-workers/src/controllers/health-monitor-orchestration-controller.spec.ts, packages/web-workers/src/e2e-test-scenarios/scan-scenario-driver.spec.ts, packages/web-workers/src/e2e-test-scenarios/scan-scenario-driver.ts, packages/web-workers/src/test-utilities/generator-function.ts
Improve E2E test error handling so that if one scan scenario throws an exception, the rest can continue running.
This PR also includes some improvements to the ScanScenarioDriver unit tests, which verify that all the generators created from OrchestrationSteps were executed, instead of just checking that they were initialized.
This will give us more accurate E2E results on the dashboard. Currently, if an exception is thrown midway through a run, we get a lot of incomplete results on the dashboard, which tells us nothing about which scenario or tests failed.
Note that even if a request fails for a scan scenario, the rest of the tests associated with that scenario still need to run. This is because the health check API endpoint looks for the Finalizer test group and checks that no tests in …
=> feat(deep-scan-e2e-tests): e2e test error handling

packages/functional-tests/src/functional-test-group-types.ts, packages/functional-tests/src/test-groups/deep-scan-post-completion-test-group.ts, packages/functional-tests/src/test-groups/deep-scan-pre-completion-notification-test-group.ts, packages/functional-tests/src/test-groups/deep-scan-status-consistency-test-group.ts, packages/web-workers/src/e2e-test-scenarios/e2e-scan-scenario-definitions.spec.ts, packages/web-workers/src/e2e-test-scenarios/e2e-scan-scenario-definitions.ts
This PR reflects paired work with @pownkel and adds two e2e deep scan changes:
- we check that the overall scan state is consistent with individual scan states; e.g. the overall state should be completed iff the individual states are completed
- we check that deep scan notifications are deferred until all individual URLs are crawled
=> feat(deep-scan-e2e-tests): add deep scan status consistency & notification e2e tests

packages/functional-tests/src/test-groups/deep-scan-pre-completion-notification-test-group.ts, packages/health-client/src/health-checker.ts
- Fix failing deep scan notification E2E test
- increase timeout for E2E tests in deployment pipeline
Fix pipeline failures
=> fix: deep scan notification e2e test

packages/scanner-global-library/src/factories/rule-exclusion.ts
This change keeps the service's ruleset in sync with web's. Web will start treating duplicate-id as a best-practice/non-violation as of issue https://github.com/microsoft/accessibility-insights-web/issues/4102 / PR https://github.com/microsoft/accessibility-insights-web/pull/4127 .
See https://github.com/microsoft/accessibility-insights-web/issues/4102
n/a
=> feat(duplicate-id): treat duplicate-id rule as best-practice to match web

packages/scanner-global-library/src/navigation-error-mappings.ts, packages/scanner-global-library/src/navigation-error-patterns.ts, packages/scanner-global-library/src/page-response-processor.spec.ts, packages/scanner-global-library/src/page-response-processor.ts
This PR updates our navigation-error processing so that more URLs fall into specific buckets like `UrlNavigationTimeout` or `SslError` rather than the catch-all `NavigationError`.
PR parts:
- small refactor of navigation-error mappings into separate file
- adding more error signatures like `net::ERR_CERT_AUTHORITY_INVALID` based on what we saw last WCP run
- update `Navigation timeout` string because of puppeteer update ([original code](https://github.com/puppeteer/puppeteer/blob/3773229ac276a84a4de113e74290abc3bbf60499/lib/LifecycleWatcher.js#L140), [new code](https://github.com/puppeteer/puppeteer/blob/18143b3573e3e9e637ae43c3f757bed8b752634f/src/common/LifecycleWatcher.ts#L194))
- Tested in Azure resource group with affected URLs from last month
Specific failure cases help the user …
=> fix: update NavigationError processing to capture more specific errors

packages/cli/package.json, packages/cli/src/cli.ts, packages/cli/src/crawler/crawler-parameters-builder.spec.ts, packages/cli/src/crawler/crawler-parameters-builder.ts, packages/cli/src/index.ts, packages/cli/src/runner/crawler-command-runner.spec.ts, packages/cli/src/runner/crawler-command-runner.ts, packages/cli/src/validate-crawl-arguments.ts, packages/cli/src/validate-scan-arguments.ts
This PR exposes a `validateScanArguments` function and `CrawlerParametersBuilder` so we can use them to validate the action inputs in https://github.com/microsoft/accessibility-insights-action/pull/564. 
I moved `crawler-parameter-builder` to the `crawler` folder so the output directory of the package makes more sense:
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         4/29/2021   4:08 PM                converter
d-----         4/29/2021   4:08 PM                crawler
d-----         4/29/2021   4:08 PM                scan-result-providers
d-----         4/29/2021   4:08 PM                scanner
-a----         4/29/2021   4:09 PM         310860 ai-scan-cli.js
-a----         4/29/2021   4:09 PM         313448 …
```
=> feat(gh-action-crawling): expose cli input validation objects from accessibility-insights-scan package

packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts
Encode scan request URL before comparison with axe scanned URL to avoid false positive redirection error.
Fix customer issue.
False positive redirection error when scanning URLs with culture specific chars.
=> Compare encoded URLs after page scan

packages/resource-deployment/scripts/delete-pools-if-needed.sh, packages/resource-deployment/scripts/install-parallel.sh, packages/resource-deployment/scripts/setup-key-vault.sh, packages/resource-deployment/templates/key-vault-create.template.json
Remove the enableSoftDeleteOnKeyvault flag from deployment scripts
Azure has removed the option to opt out of soft delete, and all our pipelines set soft delete to true by default, so there is no reason to keep this flag.
=> chore: remove soft delete keyvault flag

packages/cli/package.json
Updates `accessibility-insights-scan` to v0.8.0 in preparation for releasing and consuming in action
Using a new v0.x version because the new same-origin behavior is a breaking change.
Keep action/cli rulesets in sync with web/service
n/a
=> feat(axe-core-4.2.1): bump accessibility-insights-scan to v0.8.0

packages/cli/README.md, packages/cli/package.json, packages/cli/src/module-name-mapper.ts, packages/cli/src/runner/url-command-runner.ts, packages/crawler/src/global-overrides.ts, packages/web-api-scan-runner/src/module-name-mapper.ts
Fix package path under package content only to support client global installation.
Update readme with WSL install steps.
[Validation deployment](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_releaseProgress?_a=release-pipeline-progress&releaseId=7914)
=> Fix package path under package content only

.github/dependabot.yml
Increase dependabot PRs limit to include more required updates per schedule interval.
=> Increase dependabot PRs limit

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts
Increase max number of failed scan retries
Mitigate the concurrency issue when building consolidated report for websites with 100 pages 
When website scan runs it queues all discovered pages to scan. Some pages will fail to update consolidated report blob at the same time. Increasing number of retries will span failed pages scan requests longer with more probability to update the report blob.
=> Increase max number of failed scan requests retries

packages/azure-services/src/azure-batch/batch-task-config-generator.spec.ts, packages/azure-services/src/azure-batch/batch-task-config-generator.ts, packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts
Encode docker parameters to prevent parsing by Batch API
Batch API try parse docker parameters and fails if URL with parameters is not encoded
=> Encode docker parameters

packages/cli/src/report/report-disk-writer.ts, packages/scanner-global-library/src/index.ts, packages/scanner-global-library/src/page-configurator.spec.ts, packages/scanner-global-library/src/page-configurator.ts, packages/scanner-global-library/src/page-navigator.spec.ts, packages/scanner-global-library/src/page-navigator.ts
Fallback to load partial page resources on page navigation timeout. This will allow to scan pages with streaming video controls when headless browser fails wait for network idle state.
=> Fallback to load partial page resources

packages/scanner-global-library/src/factories/rule-exclusion.ts
This PR brings the service in line with web and the other products. Per Fer, we have moved the scrollable-region-focusable to "needs review" in web, and it will be removed in other products since we don't have a concept for "needs review". It is in relation to the following issue: https://github.com/microsoft/accessibility-insights-web/issues/3987
feature work addressing https://github.com/microsoft/accessibility-insights-web/issues/3987
=> feat(axe-core-4.3.2): exclude scrollable-region-focusable rule

packages/resource-deployment/scripts/enable-system-identity-for-batch-vmss.sh, packages/resource-deployment/scripts/function-app-create.sh
Fix cosmos RBAC role json path to be relative to the script location, not the working directory from which the script is run.
This will fix the current canary deployment failures.
=> fix: Use relative path for cosmos db RBAC role template

package.json, packages/axe-result-converter/package.json, packages/azure-services/package.json, packages/cli/package.json, packages/common/package.json, packages/crawler/package.json, packages/e2e-web-apis/package.json, packages/functional-tests/package.json, packages/health-client/package.json, packages/logger/package.json, packages/scanner-global-library/package.json, packages/service-library/package.json, packages/storage-documents/package.json, packages/web-api-client/package.json, packages/web-api-scan-job-manager/package.json, packages/web-api-scan-request-sender/package.json, packages/web-api-scan-runner/package.json, packages/web-api-send-notification-job-manager/package.json, packages/web-api-send-notification-runner/package.json, packages/web-api/package.json, packages/web-workers/package.json, yarn.lock
This PR was created by the Combine PRs action by combining the following PRs:
* #1707 chore(deps-dev): bump jest from 27.1.1 to 27.2.0
* #1706 chore(deps): bump applicationinsights from 2.1.6 to 2.1.7
* #1705 chore(deps-dev): bump eslint-plugin-unicorn from 35.0.0 to 36.0.0
* #1703 chore(deps): bump @azure/storage-blob from 12.6.0 to 12.8.0
* #1702 chore(deps-dev): bump typescript from 4.4.2 to 4.4.3
* #1699 chore(deps): bump pretty-format from 27.1.1 to 27.2.0
* #1698 chore(deps-dev): bump commander from 7.2.0 to 8.2.0
* #1697 chore(deps-dev): bump @typescript-eslint/parser from 4.31.0 to 4.31.1
* #1693 chore(deps): bump leveldown from 6.0.0 to 6.0.2
=> Update combined dependencies

packages/cli/README.md, packages/cli/src/cli.ts, packages/cli/src/crawler/crawler-parameters-builder.spec.ts, packages/cli/src/crawler/crawler-parameters-builder.ts, packages/cli/src/scan-arguments.ts, packages/crawler/src/crawler/puppeteer-crawler-engine.spec.ts, packages/crawler/src/crawler/puppeteer-crawler-engine.ts, packages/crawler/src/crawler/simple-crawler-engine.spec.ts, packages/crawler/src/crawler/simple-crawler-engine.ts, packages/crawler/src/main.ts, packages/crawler/src/types/crawler-run-options.ts
Allow the user to choose to run the scan engine using only a single crawler worker.
This option will be used to help making the scan engine result deterministic, basically if the number of URLs in the website is > the MaxURLs, we should set singleWorker to true so we would get the same result every run.
In the baselining feature, we need to make sure that the scan result is deterministic, so in the GH action and the ADO extension, we will set singleWorker to true.
=> feat(baseline-implementation): Add singleWorker option to the scan engine

packages/cli/src/baseline/baseline-options-builder.ts
#1743 added a bad command line validation. Since scanArguments.updateBaseline is a bool with a default value of false, it will never be null. As a result, the check that throws an error is wrong... and always throws. Simple fix is to throw if it's non-false (as opposed to non-null)
Unbreak CLI
=> fix: Correct CLI error that blocks scanner from running as expected

packages/cli/src/baseline/__snapshots__/baseline-engine.spec.ts.snap, packages/cli/src/baseline/baseline-engine.spec.ts, packages/cli/src/baseline/baseline-engine.ts
The current code to detect baseline changes ignores the metadata.fileFormatVersion field. This field always gets written to a constant value, so this change would only take effect if the user manually edited the field. Definitely not a blocker for the MVP, but I want to capture the behavior while it's in my mind.
Make code behave as intended
=> feat(pr-baseline-2): Update if fileFormatVersion changes

package.json, yarn.lock
Upgrade validator to version 13.7.0
CVE-2021-3765
Vulnerable versions: < 13.7.0
Patched version: 13.7.0
validator.js prior to 13.7.0 is vulnerable to Inefficient Regular Expression Complexity
=> Update package version

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/scanner-global-library/package.json, packages/scanner-global-library/src/index.ts, packages/scanner-global-library/src/privacy-page-scanner.spec.ts, packages/scanner-global-library/src/privacy-page-scanner.ts, packages/scanner-global-library/src/privacy-scan-result.ts, packages/service-library/package.json, packages/service-library/src/dev-utilities/banner-detection-test.ts, packages/storage-documents/src/index.ts, packages/storage-documents/src/privacy-scan-types/privacy-page-scan-report.ts
Create PrivacyPageScanner, which takes a Page object, checks for the banner XPath, and returns a (currently incomplete) privacy scan report
Detect the privacy banner on a page
=> Detect consent banner

packages/privacy-scan-core/src/cookie-collector.spec.ts, packages/privacy-scan-core/src/cookie-collector.ts, packages/privacy-scan-core/src/cookie-scenarios.ts, packages/privacy-scan-core/src/index.ts, packages/privacy-scan-core/src/privacy-page-scanner.spec.ts, packages/privacy-scan-core/src/privacy-page-scanner.ts, packages/privacy-scan-core/src/types.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts, packages/service-library/src/dev-utilities/banner-detection-test.ts, packages/storage-documents/src/privacy-scan-types/privacy-page-scan-report.ts
- Add MVP cookie scenarios
- Collect cookies for each scenario
Enables the privacy scanner to collect cookies for specific consent scenarios and return discovered cookies to WCP
=> Collect cookies for consent scenarios

packages/privacy-scan-runner/src/combined-report/combined-privacy-scan-result-processor.spec.ts, packages/privacy-scan-runner/src/combined-report/combined-privacy-scan-result-processor.ts, packages/privacy-scan-runner/src/combined-report/privacy-report-reducer.spec.ts, packages/privacy-scan-runner/src/combined-report/privacy-report-reducer.ts, packages/privacy-scan-runner/src/runner/runner.spec.ts, packages/privacy-scan-runner/src/runner/runner.ts, packages/privacy-scan-runner/src/scanner/privacy-scanner.spec.ts, packages/privacy-scan-runner/src/scanner/privacy-scanner.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts, packages/service-library/src/data-providers/privacy-scan-combined-report-provider.spec.ts, packages/service-library/src/data-providers/privacy-scan-combined-report-provider.ts, packages/service-library/src/index.ts, packages/service-library/src/web-api/api-contracts/scan-result-response.ts, packages/storage-documents/src/on-demand-page-scan-result.ts, packages/storage-documents/src/privacy-scan-types/privacy-scan-combined-report.ts
- Run privacy scanner in batch job and save individual report in json format
- Combine individual privacy reports for scans that share the same consolidatedId and baseUrl and save the combined report in json format
This PR connects all pieces of the privacy scanner so the service can run a privacy scan end-to-end and generate both individual and combined reports
A future PR will move combined report generation logic into the new report generator job
=> Privacy report generation

packages/functional-tests/src/functional-test-group-types.ts, packages/functional-tests/src/test-groups/privacy-scan-reports-test-group.ts, packages/privacy-scan-runner/src/combined-report/privacy-report-reducer.spec.ts, packages/privacy-scan-runner/src/combined-report/privacy-report-reducer.ts, packages/scanner-global-library/src/page.ts, packages/web-api-client/src/a11y-service-client.spec.ts, packages/web-api-client/src/a11y-service-client.ts, packages/web-api-client/src/request-options.ts, packages/web-workers/src/e2e-test-scenarios/e2e-scan-scenario-definitions.spec.ts, packages/web-workers/src/e2e-test-scenarios/e2e-scan-scenario-definitions.ts
- Page reload handles undefined navigation response
- Deduplicate URLs in combined privacy report (currently, we may get duplicate results if a scan fails and reruns)
- Add an E2E test with the privacy scan flag
Fixes some minor bugs in the privacy scanner and ensures E2E test coverage
=> Privacy scan bugfix

packages/privacy-scan-core/src/cookie-collector.spec.ts, packages/privacy-scan-core/src/cookie-collector.ts, packages/privacy-scan-core/src/test-utilities/promisable-mock.ts, packages/scanner-global-library/src/page.spec.ts
Use the Chrome devtools protocol instead of puppeteer's cookies() method to get cookies.
Puppeteer's cookies() method only returns first party cookies. We need to be able to return third-party cookies as well.
=> Include third party cookies in privacy scan results

packages/crawler/src/apify/apify-settings.ts, packages/crawler/src/crawler.spec.ts, packages/crawler/src/crawler.ts, packages/crawler/src/crawler/crawler-configuration.spec.ts, packages/crawler/src/crawler/crawler-configuration.ts, packages/crawler/src/crawler/simple-crawler-engine.spec.ts, packages/crawler/src/setup-crawler-container.spec.ts, packages/crawler/src/setup-crawler-container.ts, packages/crawler/src/types/ioc-types.ts, packages/scanner-global-library/src/index.ts, packages/scanner-global-library/src/navigation-hooks.spec.ts, packages/scanner-global-library/src/navigation-hooks.ts, packages/scanner-global-library/src/page-navigator.spec.ts, packages/scanner-global-library/src/page-navigator.ts, packages/service-library/src/dev-utilities/banner-detection-test.ts, packages/web-api-scan-runner/src/scanner/axe-scanner.spec.ts
Make some refactors in anticipation of the Apify v2 and Node 16 update. This PR does not change any behavior or update any dependencies.
- Create NavigationHooks class and move pre-navigation logic and post-navigation verification into that class
- the Apify v2 interface accepts preNavigationHook and postNavigationHook instead of a gotoFunction. Eventually, NavigationHooks will be passed to the crawler package instead of calling PageNavigator.navigate
- Replace CrawlerRunOptions container binding with a function to set CrawlerRunOptions in CrawlerConfiguration
- Not related to the apify update, but makes it clearer that CrawlerRunOptions is set at runtime and makes it easier to debug when it is called before being set
- Remove an UnresolvedPromiseRejection warning in unit test
- The …
=> (Node 16 update) Create NavigationHooks and make other refactors

packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts
Send scan completion notification immediately if the scan failed (and the notification is applicable)
Fixes a bug where, if the last scan in a consolidated report group fails when using the consolidated report workflow, the scan completion notification is never sent.
=> Send notification if scan failed

README.md
Dependabot's README badges broke when the old non-GitHub Dependabot migrated to GitHub. This PR removes the broken badge.
Fixes broken link/image at top of README
There isn't currently a replacement for the badge feature in the native GitHub Dependabot. https://github.com/dependabot/dependabot-core/issues/1912 tracks the request to add it, but hasn't seen activity in some time.
=> chore: remove obsolete Dependabot badge from README

packages/resource-deployment/runtime-config/runtime-config.dev.json, packages/service-library/src/combined-report-provider/combined-axe-result-builder.spec.ts, packages/service-library/src/combined-report-provider/combined-axe-result-builder.ts, packages/service-library/src/combined-report-provider/combined-scan-result-processor.spec.ts, packages/service-library/src/combined-report-provider/combined-scan-result-processor.ts, packages/service-library/src/data-providers/page-scan-run-report-provider.spec.ts, packages/service-library/src/data-providers/page-scan-run-report-provider.ts
Fixed axe result blob deserialization. The axe scan results were incorrectly deserialized into non-array object.
Fix consolidated  report stata data issue.
=> Fixed axe result blob deserialization

packages/report-generator-runner/src/report-processor/report-processor.ts, packages/report-generator-runner/src/runner/runner.ts, packages/resource-deployment/runtime-config/runtime-config.ci.json, packages/resource-deployment/runtime-config/runtime-config.dev.json, packages/resource-deployment/runtime-config/runtime-config.ppe.json, packages/resource-deployment/runtime-config/runtime-config.prod.json, packages/resource-deployment/runtime-config/runtime-config.selftest.json, packages/resource-deployment/templates/batch-account-dev.parameters.json, packages/resource-deployment/templates/batch-account-prod.parameters.json, packages/resource-deployment/templates/batch-account.template.json, packages/resource-deployment/templates/report-generator-schedule.template.json, packages/service-library/src/combined-report-provider/combined-axe-result-builder.spec.ts, packages/service-library/src/combined-report-provider/combined-axe-result-builder.ts, packages/service-library/src/combined-report-provider/combined-scan-result-processor.spec.ts, packages/service-library/src/combined-report-provider/combined-scan-result-processor.ts, packages/service-library/src/data-providers/website-scan-result-aggregator.ts, packages/service-library/src/data-providers/website-scan-result-provider.spec.ts, packages/service-library/src/data-providers/website-scan-result-provider.ts, packages/service-library/src/web-api/web-api-error-codes.ts, packages/web-api/src/controllers/scan-request-controller.spec.ts, packages/web-api/src/controllers/scan-request-controller.ts
- Increased limit to support 5000 pages for a single scan request.
- Switch to use larger batch of db documents when processing in parallel to eliminate node processes creation operations.
- Added client error codes to indicate validation error when too many know pages is sent in a request, and invalid URLs provided.
- Revert to use consolidated urls count from a previous consolidated blob result.
- Upgraded VM to SKU with higher CPU count
=> Performance optimization to support high number page under single scan request

packages/crawler/src/authenticator/authenticator-factory.spec.ts, packages/crawler/src/authenticator/azure-portal-authenticator.spec.ts
This appends the `Placeholder` prefix to test passwords to signal to CredScan that they are not real passwords.
CredScan Compliance 
- [ n/a] Added relevant unit test for your changes. (`yarn test`)
=> Mark test passwords as placeholder for CredScan Compliance

packages/privacy-scan-core/src/privacy-page-scanner.ts, packages/privacy-scan-runner/src/scanner/scan-feed-generator.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts, packages/service-library/src/data-providers/website-scan-result-aggregator.ts, packages/web-api/src/controllers/base-scan-result-controller.ts, packages/web-api/src/controllers/batch-scan-result-controller.spec.ts, packages/web-api/src/controllers/batch-scan-result-controller.ts, packages/web-api/src/controllers/scan-result-controller.spec.ts, packages/web-api/src/controllers/scan-result-controller.ts, packages/web-api/src/converters/scan-response-converter.spec.ts, packages/web-api/src/converters/scan-response-converter.ts
Return pending run state for retrying failed scans to avoid false positive results.
Return an actual browser error to a client if any.
=> Return pending run state for retrying failed scans

packages/crawler/src/authenticator/azure-portal-authenticator.spec.ts, packages/crawler/src/authenticator/azure-portal-authenticator.ts
This adds the following stability improvements to the current auth browser automation:
- using `page.waitForNavigation()` in a `Promise.all` statement with the action that causes the navigation, as recommended in the puppeteer docs.
- adds an `authenticationSucceeded` check, and moves it to the top of the process. This was done because azure portal would unreliably finish navigating after auth before the auth check would retry. I couldn't track down exactly why this is happening but my hypothesis is that among the many auth redirects puppeteer would sometimes think it was done navigating when it wasn't. This checks before it goes through another auth attempt to ensure it truly didn't work.
Before these changes I was getting auth errors about 1 out of every 3 runs via the CLI. I have run …
=> feat(ado-auth-part-2): auth stability improvements

packages/cli/src/cli.ts, packages/cli/src/crawler/crawler-parameters-builder.ts, packages/cli/src/scan-arguments.ts, packages/cli/src/validate-scan-arguments.ts, packages/crawler/src/authenticator/authenticator-factory.spec.ts, packages/crawler/src/authenticator/authenticator-factory.ts, packages/crawler/src/authenticator/azure-active-directory-authenticator.spec.ts, packages/crawler/src/authenticator/azure-active-directory-authenticator.ts, packages/crawler/src/crawler/puppeteer-crawler-engine.spec.ts, packages/crawler/src/crawler/puppeteer-crawler-engine.ts, packages/crawler/src/types/crawler-run-options.ts
This adds `authType` to the `Authenticator` in the `CLI` package. This allows us to specify which `authType` will be used in the `AuthenticatorFactory`. It also renames the `AzurePortalAuthenticator` to `AzureActiveDirectoryAuthenticator`, as it is a more accurate description of the purpose of the class.
Feature work, this also allows the authType to be passed through from the ADO Extension.
=> feat(ado-auth-part-2): add authType to Authenticator

packages/report-generator-job-manager/src/worker/worker.spec.ts, packages/report-generator-job-manager/src/worker/worker.ts, packages/report-generator-runner/src/runner/request-selector.spec.ts, packages/report-generator-runner/src/runner/request-selector.ts, packages/report-generator-runner/src/runner/runner.spec.ts, packages/service-library/src/batch/batch-task-creator.spec.ts, packages/service-library/src/batch/batch-task-creator.ts, packages/service-library/src/data-providers/report-generator-request-data-provider.ts, packages/storage-documents/src/report-generator-request.ts
Reduce report generation concurrency. The large websites will have high contention when generating accessibility combined report on blob write operation. Converting report job manager to schedule single report batch per website.
=> Reduce report generation concurrency

packages/resource-deployment/templates/batch-account-ppe-pr.parameters.json, packages/resource-deployment/templates/batch-account-prod.parameters.json, packages/scanner-global-library/src/page-navigator.spec.ts, packages/scanner-global-library/src/page-navigator.ts
Retry page reload on HTTP 304 response to mitigate transient reload state.
=> Retry page reload on HTTP 304 response

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, yarn.lock
Increased pending response delay to ensure request get processed by Cosmos trigger at high load
=> Increased pending response delay

packages/azure-services/src/azure-batch/batch-task-config-generator.spec.ts, packages/azure-services/src/azure-batch/batch-task-config-generator.ts, packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/web-api-scan-request-sender/src/sender/scan-request-selector.spec.ts, packages/web-api-scan-request-sender/src/sender/scan-request-selector.ts
Ensure abandon or terminated scan marked as failed in a storage.
=> Ensure abandon scan marked as failed

packages/scanner-global-library/src/page-client-lib.ts
Terminate browser page script on timeout when it freezes. Browser freeze will block scan task if not terminated.
=> Terminate browser page script when it freezes

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/report-generator-runner/src/runner/runner.spec.ts, packages/report-generator-runner/src/runner/runner.ts, packages/resource-deployment/templates/batch-account-prod.parameters.json, packages/storage-documents/src/on-demand-page-scan-result.ts, packages/storage-documents/src/report-generator-request.ts, packages/web-api-scan-request-sender/src/sender/on-demand-dispatcher.spec.ts, packages/web-api-scan-request-sender/src/sender/on-demand-dispatcher.ts, packages/web-api-scan-request-sender/src/sender/scan-request-selector.spec.ts, packages/web-api-scan-request-sender/src/sender/scan-request-selector.ts, packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts
Added abandoned scan state validation to mark stale scan as failed.
=> Added abandoned scan state validation

packages/scanner-global-library/src/page-navigator.spec.ts, packages/scanner-global-library/src/page-navigator.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts, packages/scanner-global-library/src/web-driver.ts
Fallback on browser with local cache removed when reload with cache fails with HTTP 304
Added page navigation fallback on timeout for reload page operation
=> Reload page with local cache disabled on HTTP 304

packages/scanner-global-library/src/page-navigator.ts, packages/scanner-global-library/src/page-timeout-config.ts
Increase initial web page load timeout to support long running network activities.
=> Increase web page load timeout

packages/scanner-global-library/src/page-navigator.spec.ts, packages/scanner-global-library/src/page-navigator.ts, yarn.lock
Allow HTTP 304 on page reload when initial page load is timed out
=> Allow HTTP 304 on page reload when timed out

packages/crawler/src/authenticator/azure-active-directory-authenticator.spec.ts, packages/crawler/src/authenticator/azure-active-directory-authenticator.ts
This pull request will make improvements to authentication errors:
- throw errors in the Azure active directory flow to stop the scanner from continuing. Previously, if unable to authenticate, the scanner would log the error and continue to scan the login page; resulting in a false positive.
- add a try/catch statement when entering the account name and throw a specific error from the login page. Previously, if a pipeline entered an invalid account name, it would return a timeout error.
- remove attempts. Now that auth will throw errors, the `handleRequestFunction` will retry up to 3 times and removes the need for auth to kick off additional attempts.
Improve user experience when authenticating.
=> Update authentication to throw errors and catch account name errors

package.json, packages/axe-result-converter/package.json, packages/azure-services/package.json, packages/cli/package.json, packages/common/package.json, packages/crawler/package.json, packages/e2e-test-site/package.json, packages/e2e-web-apis/package.json, packages/functional-tests/package.json, packages/health-client/package.json, packages/logger/package.json, packages/parallel-workers/package.json, packages/privacy-scan-core/package.json, packages/privacy-scan-job-manager/package.json, packages/privacy-scan-runner/package.json, packages/report-generator-job-manager/package.json, packages/report-generator-runner/package.json, packages/resource-deployment/package.json, packages/scanner-global-library/package.json, packages/service-library/package.json, packages/storage-documents/package.json, packages/web-api-client/package.json, packages/web-api-scan-job-manager/package.json, packages/web-api-scan-request-sender/package.json, packages/web-api-scan-runner/package.json, packages/web-api-send-notification-job-manager/package.json, packages/web-api-send-notification-runner/package.json, packages/web-api/package.json, packages/web-workers/package.json
This PR reverts a Lerna workaround @pownkel added in #2009 which became obsolete with our removal of Lerna in #2210. The workaround was breaking the ability to run `yarn cbuild` on Windows machines - this PR restores that capability.
The upgrade to yarn 3 in #2210 accidentally broke all run scripts which transitively refer to a `npm-run-all` command in non-WSL Windows developer environments. Notably, this breaks `yarn cbuild` from the root of the repo.
This manifested as a failing `yarn cbuild` command with output like this:
<details>
<summary>full example output snippet</summary>
```
➤ YN0000: [parallel-workers]: Process started
➤ YN0000: [scanner-global-library]: Process started
➤ YN0000: [parallel-workers]:
➤ YN0000: [parallel-workers]: > parallel-workers@1.0.0 clean
➤ YN0000: …
```
=> chore: fix cbuild on windows by reverting obsolete npm-path workaround

packages/azure-services/src/azure-batch/batch-task-config-generator.spec.ts, packages/azure-services/src/azure-batch/batch-task-config-generator.ts, packages/scanner-global-library/src/page-navigator.spec.ts, packages/scanner-global-library/src/page-navigator.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts
Added page indirect redirection handler to support case when page was redirected by a script. The indirect redirection may result empty puppeteer response result and fail scan.
Refactored PageNavigator() to unify page load workflow for navigate and reload scenarios.
Increased shared memory allocated to a runner container.
=> Added page indirect redirection handler

packages/privacy-scan-runner/src/combined-report/privacy-report-reducer.spec.ts, packages/privacy-scan-runner/src/combined-report/privacy-report-reducer.ts, packages/web-api-scan-request-sender/src/sender/on-demand-dispatcher.ts
Set website page scan state on delete to correctly reflect in combined scan result API response.
=> Set website page scan state on delete

packages/scanner-global-library/src/factories/axe-puppeteer-factory.spec.ts, packages/scanner-global-library/src/factories/axe-puppeteer-factory.ts, packages/scanner-global-library/src/page-configurator.spec.ts, packages/scanner-global-library/src/page-configurator.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts
Fallback to legacy mode on axe-core/puppeteer scan error.
Fixed browser viewport mode.
=> Fallback to legacy mode on axe-core/puppeteer scan error

packages/cli/package.json, packages/cli/src/cli.ts
This adds a `process.exit()` call at the end of the CLI execution to fix a bug where the CLI seems to hang after everything has completed.
This also bumps the scan package version number in preparation for re-release.
Fixes bug found during ADO Extension release validation
=> fix: add process exit to end of cli execution

packages/cli/package.json, packages/crawler/src/authenticator/azure-active-directory-authenticator.spec.ts, packages/crawler/src/authenticator/azure-active-directory-authenticator.ts
This adds a check for the KMSI (Keep Me Signed In) page that shows up conditionally based on a machine learning algorithm that detects high risk logins. It also bumps the scan package version in preparation for release.
More information on the KMSI page can be found here: https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/customize-branding#learn-about-the-stay-signed-in-prompt
Fix for auth
My initial implementation did not use the try/catch block, but instead was performing a `page.$eval` and looking for the selector. I changed it to a `waitForSelector` with a 5000ms timeout to ensure that we aren't missing the dialog due to a possible race condition where the page doesn't fully render before the `page.$eval` executes.
=> fix: Update auth flow to handle KMSI page

packages/privacy-scan-runner/src/runner/runner.spec.ts, packages/privacy-scan-runner/src/runner/runner.ts
A previous change serialized a BrowserError to string before passing it into Runner.setRunResult. This had the unintended side effect of resulting in all BrowserErrors being reported as InternalError, instead of being mapped to the corresponding ScanRunErrorCode.
This change explicitly converts Error and BrowserError objects into ScanError objects before passing them to setRunResult. This works because both BrowserError and ScanError objects have an errorType member and the BrowserErrorTypes and ScanErrorTypes align. Error has no overlap with ScanError so it is mapped to InternalError - which is what the conversion handling would ultimately do with a string anyway.
For reference see also ScanResponseConverter.createFailedScanResponse and ScanErrorConverter.getScanRunErrorCode; this is the …
=> Ensure that the most precise error information is included in a scan run result

packages/scanner-global-library/src/page-navigator.spec.ts, packages/scanner-global-library/src/page-navigator.ts
Merge page navigation and wait for network activity completion operations. This will resolved unnecessary wait cycle of 40 seconds per page navigation operation. The wait operation after page navigation has been completed will almost result timeout as there is nothing to wait for.
Resolve privacy scanner performance issue.
=> Merge page navigation and wait for network activity completion operations

packages/web-workers/.vscode/tasks.json, packages/web-workers/extensions.csproj
Revert CosmosDB nuget version after dependabot update as it currently breaks CosmosDB trigger functionality.
=> Revert CosmosDB nuget version

packages/scanner-global-library/src/page.ts
Add null check to log statement.
The logger is undefined when running the ai-scan CLI tool in --url mode (not crawling). This caused the tool to crash with an unhandled exception every time it was run. We probably did not detect this earlier because most consumers use the --crawl mode. However, "ai-scan --url <myurl>" is the first command example given in the readme, so it is a good idea to fix this.
A nicer way to fix this would be to initialize a logger with a console client in ai-scan, but this is a more involved fix. For the immediate need this gets the job done. The existing code has the logger as optional and null checks throughout, so this scenario was probably imagined and just this statement omitted the null check unintentionally.
=> Quick and dirty fix for unhandled exception when running ai-scan --url

packages/azure-services/src/key-vault/secret-names.ts
Add values to secretNames for scanBehindAuthUsername and scanBehindAuthPassword. These correspond to the names of secrets in the service key vault. The secret value for scanBehindAuthUsername is expected to be the alias of a valid account to be used when scanning sites that require authentication. The secret value for scanBehindAuthPassword is the corresponding password for the account.
The secrets are configured manually on the key vault at or after creation time; since the key vault persists through redeployments this is not expected to add a maintenance burden.
Allow the service to securely retrieve account credentials for authenticating sites at runtime.
=> Add secret names for scan-behind-auth service account credentials.

package.json, packages/axe-result-converter/package.json, packages/axe-result-converter/src/__snapshots__/combined-report-data-converter.spec.ts.snap, packages/axe-result-converter/src/combined-report-data-converter.spec.ts, packages/axe-result-converter/src/combined-report-data-converter.ts, packages/cli/package.json, packages/crawler/package.json, packages/scanner-global-library/package.json, packages/scanner-global-library/src/factories/rule-exclusion.ts, packages/service-library/package.json, packages/web-api-scan-runner/package.json, yarn.lock
This PR:
* Updates `axe-core` to v4.6.3
* Updates `accessibility-insights-report` to corresponding v4.6.3
* Removes `link-in-text-block` and `meta-viewport` from the rule exclusion list, matching the new AI4Web behavior enabling them as automated checks
* Enables a new report feature to include "Related paths" for failure cards of axe results with "relatedNodes" info by propogating this axe property in `combined-report-data-converter.ts`
* Bumps the `accessibility-insights-scan` minor version to `1.6.0` in anticipation of a corresponding release for that package
Screenshot of combined report segment with new Related paths UX generated using the following CLI command in this PR branch: `node C:\repos\accessibility-insights-service\packages\cli\dist\ai-scan-cli.js --crawl --url …
=> feat(axe-core-4.6): Update to axe-core 4.6.3, enabling link-in-text-block, meta-viewport, and "Related paths" in reports

packages/cli/README.md
Adds `authType`, `serviceAccountName`, and `serviceAccountPassword` to the CLI README.
Document authentication options.
=> chore: Update CLI README to document authentication options

packages/scanner-global-library/src/user-agent-plugin.spec.ts, packages/scanner-global-library/src/user-agent-plugin.ts, packages/scanner-global-library/src/web-driver.ts
Override browser user agent string to prevent server side request rejection.
=> Override browser user agent string

packages/scanner-global-library/src/network/page-operation-handler.spec.ts, packages/scanner-global-library/src/network/page-operation-handler.ts, packages/scanner-global-library/src/network/page-request-interceptor.spec.ts, packages/scanner-global-library/src/network/page-request-interceptor.ts, packages/scanner-global-library/src/page-navigator.ts, packages/scanner-global-library/src/page-timeout-config.ts
Bypass service worker on page load to intercept page navigation network trace.
=> Bypass service worker on page load

packages/report-generator-job-manager/src/worker/worker.spec.ts, packages/report-generator-job-manager/src/worker/worker.ts, packages/report-generator-runner/src/report-processor/report-processor.ts, packages/report-generator-runner/src/runner/request-selector.spec.ts, packages/report-generator-runner/src/runner/request-selector.ts, packages/report-generator-runner/src/runner/runner.spec.ts, packages/report-generator-runner/src/runner/runner.ts, packages/resource-deployment/scripts/function-app-create.sh, packages/resource-deployment/templates/blob-storage.template.json, packages/service-library/src/combined-report-provider/combined-scan-result-processor.spec.ts, packages/service-library/src/combined-report-provider/combined-scan-result-processor.ts, packages/service-library/src/data-providers/page-scan-request-provider.spec.ts, packages/service-library/src/data-providers/page-scan-request-provider.ts, packages/service-library/src/data-providers/report-generator-request-data-provider.spec.ts, packages/service-library/src/data-providers/report-generator-request-data-provider.ts, packages/web-api-scan-request-sender/src/sender/on-demand-dispatcher.spec.ts, packages/web-api-scan-request-sender/src/sender/on-demand-dispatcher.ts, packages/web-api-scan-request-sender/src/sender/scan-request-selector.spec.ts, packages/web-api-scan-request-sender/src/sender/scan-request-selector.ts
Moved scan request query limit from DB to service process to avoid stale/abandon requests.
Restricted maximum blob size of consolidated accessibility scan results.
=> Moved scan request query limit from DB to service process

azure-pipeline/build-artifacts-and-run-tests-job.yaml, packages/api-contracts/ai-scan-api.yaml, packages/privacy-scan-runner/src/scanner/scan-feed-generator.spec.ts, packages/privacy-scan-runner/src/scanner/scan-feed-generator.ts, packages/service-library/src/web-api/api-contracts/scan-result-response.ts, packages/storage-documents/src/on-demand-page-scan-batch-request.ts, packages/storage-documents/src/on-demand-page-scan-request.ts, packages/storage-documents/src/on-demand-page-scan-result.ts, packages/storage-documents/src/website-scan-result.ts, packages/web-api-scan-runner/src/crawler/scan-feed-generator.spec.ts, packages/web-api-scan-runner/src/crawler/scan-feed-generator.ts, packages/web-api/src/controllers/base-scan-result-controller.ts, packages/web-api/src/controllers/batch-scan-result-controller.spec.ts, packages/web-api/src/controllers/scan-request-controller.ts, packages/web-api/src/controllers/scan-result-controller.spec.ts, packages/web-api/src/controllers/scan-result-controller.ts, packages/web-api/src/converters/scan-response-converter.spec.ts, packages/web-api/src/converters/scan-response-converter.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.spec.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.ts
Disable deep scan result for descendant scan REST API response to preserve actual scan response. The original scan run state had cumulated state for all descendant scans. Disabling deep scan result for descendant scan allow return an actual scan run state instead of cumulated state.
=> Disable deep scan result for descendant scan response

packages/web-api-scan-runner/src/crawler/discovery-pattern-factory.spec.ts, packages/web-api-scan-runner/src/crawler/discovery-pattern-factory.ts, packages/web-api-scan-runner/src/website-builder/page-metadata-generator.spec.ts, packages/web-api-scan-runner/src/website-builder/page-metadata-generator.ts, packages/web-api/src/controllers/scan-request-controller.ts
Enable scan URLs from the same domain location when scan request URL was redirected to different path.
=> Enable scan URLs from the same domain location

packages/api-contracts/ai-scan-api.yaml, packages/scanner-global-library/src/authenticator/login-page-detector.ts, packages/scanner-global-library/src/browser-error.ts, packages/scanner-global-library/src/index.ts, packages/scanner-global-library/src/page-navigation-error-patterns.ts, packages/scanner-global-library/src/page-response-processor.spec.ts, packages/scanner-global-library/src/page-response-processor.ts, packages/service-library/src/web-api/scan-run-error-codes.ts, packages/storage-documents/src/on-demand-page-scan-result.ts, packages/web-api-scan-runner/src/runner/runner.spec.ts, packages/web-api-scan-runner/src/runner/runner.ts, packages/web-api-scan-runner/src/scanner/page-scan-processor.spec.ts, packages/web-api-scan-runner/src/scanner/page-scan-processor.ts, packages/web-api-scan-runner/src/website-builder/page-metadata-generator.spec.ts, packages/web-api-scan-runner/src/website-builder/page-metadata-generator.ts, packages/web-api/src/converters/scan-error-converter.spec.ts, packages/web-api/src/converters/scan-error-converter.ts, packages/web-api/src/converters/scan-response-converter.spec.ts, packages/web-api/src/converters/scan-response-converter.ts
Added REST API error codes for unscannable URLs.
```
{
"run": {
"state": "completed",
"error": {
"code": "ForeignResourceRedirection | UnsupportedResource",
"codeId": 9014 | 9015,
}
}
}
```
=> Added REST API error code for unscannable URLs

packages/api-contracts/ai-scan-api.yaml, packages/logger/src/otel-config-provider.ts, packages/service-library/src/data-providers/page-scan-request-provider.spec.ts, packages/service-library/src/data-providers/page-scan-request-provider.ts, packages/storage-documents/src/on-demand-page-scan-batch-request.ts, packages/storage-documents/src/on-demand-page-scan-request.ts, packages/storage-documents/src/on-demand-page-scan-result.ts, packages/web-api-scan-request-sender/src/sender/on-demand-dispatcher.spec.ts, packages/web-api-scan-request-sender/src/sender/on-demand-dispatcher.ts, packages/web-api-scan-request-sender/src/sender/scan-request-selector.spec.ts, packages/web-api-scan-request-sender/src/sender/scan-request-selector.ts, packages/web-api/src/controllers/__snapshots__/batch-scan-result-controller.spec.ts.snap, packages/web-api/src/controllers/base-scan-result-controller.ts, packages/web-api/src/controllers/scan-result-controller.spec.ts, packages/web-api/src/converters/scan-response-converter.spec.ts, packages/web-api/src/converters/scan-response-converter.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.spec.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.ts
Converted dispatcher to process scan types separately to prevent suppression one queue by other one when scanner is blocked.
=> Converted dispatcher to process scan types separately

packages/scanner-global-library/src/authenticator/azure-login-page-client.spec.ts, packages/scanner-global-library/src/authenticator/azure-login-page-client.ts, packages/scanner-global-library/src/dev-tools-session.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts, packages/scanner-global-library/src/puppeteer-options.ts, packages/scanner-global-library/src/web-driver.spec.ts, packages/scanner-global-library/src/web-driver.ts
- Preserve authentication cookies to keep resource authenticated when reloaded.
- Updated Microsoft Entra ID client
=> Preserve authentication cookies

jest.config.base.js, packages/azure-services/package.json, packages/functional-tests/package.json, packages/privacy-scan-runner/package.json, packages/privacy-scan-runner/src/scanner/page-scan-processor.ts, packages/privacy-scan-runner/src/scanner/privacy-scanner.ts, packages/report-generator-runner/package.json, packages/resource-deployment/scripts/create-env-file-for-debug.sh, packages/service-library/package.json, packages/service-library/src/crawler/discovered-url-processor.spec.ts, packages/service-library/src/crawler/discovered-url-processor.ts, packages/web-api-scan-runner/package.json, packages/web-api-send-notification-runner/package.json, packages/web-workers/src/controllers/scan-batch-request-feed-controller.spec.ts, packages/web-workers/src/controllers/scan-batch-request-feed-controller.ts, yarn.lock
- Preserve URLs from a client scan request for backward compatibility
- Updated Cosmos DB npm package
=> Preserve URLs from a client scan request

packages/resource-deployment/scripts/docker-scanner-image/build-scanner-image.ps1
Removed command option (forward slash) char from command string since Windows net tool fails when it is presented even in an option value.
=> Removed command option char from command string

packages/cli/README.md, packages/cli/package.json, packages/cli/src/cli.ts, packages/cli/src/crawler/crawler-parameters-builder.spec.ts, packages/cli/src/crawler/crawler-parameters-builder.ts, packages/cli/src/scan-arguments.ts, packages/crawler/src/apify/apify-request-queue-creator.spec.ts, packages/crawler/src/apify/apify-request-queue-creator.ts, packages/crawler/src/common/url.spec.ts, packages/crawler/src/common/url.ts, packages/crawler/src/crawler/crawler-configuration.spec.ts, packages/crawler/src/crawler/crawler-configuration.ts, packages/crawler/src/page-operations/enqueue-active-elements-operation.ts, packages/crawler/src/page-processors/page-processor-base.spec.ts, packages/crawler/src/page-processors/page-processor-base.ts, packages/crawler/src/types/crawler-run-options.ts
Added new optional parameter keepUrlFragment to enable crawling for URLs having hash fragments for ai-scan cli and crawler packages.
The default value of it is false so that existing scan work as is.
[Feature 2114928](https://dev.azure.com/mseng/1ES/_workitems/edit/2114928): ADO Extension should be able to crawl hash-routing SPA apps
=> Enable crawling for URLs having hash fragments for ai-scan cli

packages/azure-services/package.json, packages/azure-services/src/credentials/credentials-provider.spec.ts, packages/azure-services/src/credentials/credentials-provider.ts, packages/azure-services/src/credentials/msi-credential-provider.spec.ts, packages/azure-services/src/credentials/msi-credential-provider.ts, packages/azure-services/src/register-azure-services-to-container.ts, packages/resource-deployment/scripts/create-env-file-for-debug.sh, packages/resource-deployment/scripts/create-sp-for-debug.sh, yarn.lock
Use az cli auth credentials for local app debugging instead of service principal.
=> Use az cli auth credentials for local app debugging 

packages/privacy-scan-runner/src/processor/page-scan-processor.spec.ts, packages/privacy-scan-runner/src/processor/page-scan-processor.ts, packages/scanner-global-library/src/page.ts, packages/service-library/src/website-builder/page-metadata-generator.spec.ts, packages/web-api-scan-runner/src/processor/page-scan-processor.spec.ts, packages/web-api-scan-runner/src/processor/page-scan-processor.ts
Capture page state at the end of workflow to prevent page layout break.
=> Capture page state at the end of workflow

packages/scanner-global-library/src/dev-tools-session.spec.ts, packages/scanner-global-library/src/dev-tools-session.ts, packages/scanner-global-library/src/page.spec.ts, packages/scanner-global-library/src/page.ts
Take a snapshot of the page using the browser CDP protocol to prevent Puppeteer's internal timeout error.
=> Capture a snapshot of the page using the browser CDP protocol

packages/resource-deployment/scripts/install-parallel.sh
Deployment of test website is dependent on APIM service. The deployment will fail for new resource group when APIM service is not available before test website deployment. Moved test website deployment to the end to fix the dependency.
=> fix: updated install script to fix test website and apim service dependency.

packages/scanner-global-library/src/axe-scanner/axe-puppeteer-scanner.spec.ts, packages/scanner-global-library/src/axe-scanner/axe-puppeteer-scanner.ts
Override document readyState property to allow axe scanner complete validation.
=> Override document readyState property

packages/common/src/configuration/__snapshots__/service-configuration.spec.ts.snap, packages/common/src/configuration/service-configuration.ts, packages/functional-tests/src/common-types.ts, packages/privacy-scan-runner/docker-image-config/Dockerfile, packages/resource-deployment/runtime-config/runtime-config.dev.json, packages/scanner-global-library/src/axe-scanner/axe-puppeteer-scanner.spec.ts, packages/scanner-global-library/src/axe-scanner/axe-puppeteer-scanner.ts, packages/scanner-global-library/src/page.ts, packages/service-library/src/combined-report-provider/combined-results-blob-provider.ts, packages/service-library/src/combined-report-provider/combined-scan-result-processor.spec.ts, packages/service-library/src/combined-report-provider/combined-scan-result-processor.ts, packages/service-library/src/web-api/api-contracts/health-report.ts, packages/web-api-scan-runner/docker-image-config/Dockerfile, packages/web-api-scan-runner/run-in-docker-container.cmd, packages/web-workers/src/orchestration/orchestration-steps.spec.ts
Fetch page metadata in advance to prevent dev-tool protocol from timing out on pages with high activity.
Fixed bugs.
=> Preload page metadata

packages/cli/package.json, packages/crawler/src/authenticator/azure-active-directory-authenticator.spec.ts, packages/crawler/src/authenticator/azure-active-directory-authenticator.ts
Service accounts having password authentication preference set by default will skip the Forms Authentication Page (page which gives option to select authentication type Password or Sign in with PIN). This pull request handle the scenario to checks for password page load if forms authentication page load timeout. 
addresses issue #2569
=> fix: handle service account password authentication preference

packages/resource-deployment/scripts/enable-batch-node-identity.sh
Create RBAC role per resource group to avoid name collision.
=> Create RBAC role per resource group

packages/privacy-scan-runner/docker-image-config/privacy-scan-runner.ps1, packages/privacy-scan-runner/run-in-terminal.ps1, packages/web-api-scan-runner/docker-image-config/web-api-scan-runner.ps1, packages/web-api-scan-runner/run-in-terminal.ps1
Increasing the Node.js memory limit.
=> Increasing the Node.js memory limit

packages/scanner-global-library/src/network/page-analyzer.spec.ts, packages/scanner-global-library/src/network/page-analyzer.ts
Handle page redirection case when other detection has failed.
=> Handle page redirection case

packages/cli/package.json, packages/crawler/src/authenticator/azure-active-directory-authenticator.spec.ts, packages/crawler/src/authenticator/azure-active-directory-authenticator.ts
scan is failing with below error due to waiting for 30 sec on #FormsAuthentication selector. Reduced the timeout to 10 seconds. 
```Authentication failed. Authentication requires a non-people service account. To learn how to set up a service account, visit: https://aka.ms/AI-action-auth. Error: Waiting for selector `input[type="password"]` failed: waitForFunction failed: frame got detached.```
=> fix: update timeout for authentication in accessibility insights scan package

packages/cli/package.json, packages/crawler/src/crawler/site-crawler-engine.ts
Update crawler engine for accessibility insights scan package to fix issue raised due to crawlee version upgrade(#2580)
1. A new flag `retireInactiveBrowserAfterSecs` in @crawlee v3.9.1 checks for inactive browsers. The default value is 10 seconds. During AAD Auth, the browser remains inactive for 10 seconds while waiting for FormsAuthenticator and password selectors. Therefore, we have increased this time to prevent the browser from closing prematurely.
2. Removed user data folder. Crawler will maintain temp directory for each session. Below are the details for making this change:
- SiteCrawlerEngine starts once per crawler CLI instance. It manages sessions and changes them based on max usage count (number of times session used while processing Urls, default 50) or session age (default …
=> fix: cli crawler engine updates for crawlee version upgrade to 3.11

packages/api-contracts/openapi.json, packages/resource-deployment/scripts/docker-scanner-image/build-scanner-image.ps1, packages/resource-deployment/scripts/docker-scanner-image/install-font-packages.ps1, packages/service-library/src/web-api/api-contracts/scan-result-response.ts, packages/storage-documents/src/on-demand-page-scan-result.ts, packages/web-api-scan-runner/docker-image-config/Dockerfile, packages/web-api-scan-runner/run-in-docker-container.cmd, packages/web-api-scan-runner/src/agent/agent-report-generator.spec.ts, packages/web-api-scan-runner/src/agent/axe-result-converter.spec.ts, packages/web-api-scan-runner/src/agent/html-result-converter.spec.ts, packages/web-api-scan-runner/src/agent/sarif-result-converter.spec.ts, packages/web-api-scan-runner/src/report-generator/report-generator.spec.ts, packages/web-api-scan-runner/src/report-generator/report-generator.ts, packages/web-api-scan-runner/src/runner/runner.ts, packages/web-api-scan-runner/src/scanner/agent-scanner.ts, packages/web-api-scan-runner/src/scanner/high-contrast-scanner.ts, packages/web-api-scan-runner/src/scanner/scanner-dispatcher.spec.ts
This pull request includes several changes to the codebase, focusing on updating enums, modifying scripts for Docker image building, and enhancing test cases. The most important changes are summarized below:
* Updated the `state` property in `openapi.json` to reference `RunState` instead of a string enum.
* Added `error` to the `ScanState` enum in `openapi.json`.
* Updated `ScanState` and `RunState` enums in `scan-result-response.ts` and `on-demand-page-scan-result.ts` to include `error` and `completed` states. [[1]](diffhunk://#diff-b98d83874f9b69c1e3a373bf295d7aeac697c7e43f365180c2de478fac031a3fL4-R10) [[2]](diffhunk://#diff-5955e953841a00eb4c2746a3cc280db3d05a3b0e2ebd6bfc4d695d71bc351515L20-R28)
* Refactored `build-scanner-image.ps1` to handle separate shares for `WinSxS` and `Fonts`. …
=> refactor: remove workaround for Playwright and extend scan reporting

package.json, packages/axe-result-converter/package.json, packages/cli/package.json, packages/crawler/package.json, packages/service-library/package.json, packages/web-api-scan-runner/package.json, yarn.lock
This pull request updates the `accessibility-insights-report` dependency across multiple packages in the repository from version `5.2.0` to `7.0.0`. This ensures all packages use the latest version of the library, likely to incorporate new features, bug fixes, or performance improvements.
Dependency updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L95-R95): Updated `accessibility-insights-report` dependency to version `7.0.0` in the root package file.
* [`packages/axe-result-converter/package.json`](diffhunk://#diff-5d02697f92ec66562e8de45c75ab37913364f2f0eab90e9129861e8411d20d79L38-R38): Updated `accessibility-insights-report` dependency to version `7.0.0`.
* [`packages/cli/package.json`](diffhunk://#diff-6e2e2a1851648938b325ba84 …
=> chore: update accessibility-insights-report dependency to version 7.0.0

patches/puppeteer++puppeteer-core+24.15.0.patch
This pull request updates the Puppeteer patch to address browser instability by disabling a problematic experimental feature flag in the Chrome launcher. This change aims to improve reliability when launching Chrome instances via Puppeteer.
Browser stability improvement:
* In `ChromeLauncher.js`, the `'OptimizationHints'` feature flag is now commented out and disabled, with a note indicating it was causing browser instability.
=> fix: disable 'OptimizationHints' to prevent browser instability
